### ISSUE TITLE
Support for ZMQ.DISH and ZMQ.RADIO Sockets in jeromq

### ISSUE THREAD

**Issue by thstasy** [zeromq/jeromq#1000]
Hello `jeromq` Developers,

I am working on a project that requires ZeroMQ's UDP socket types (`ZMQ.DISH` and `ZMQ.RADIO`). While I see that these sockets are supported in the C++ version of ZeroMQ (introduced in version 4.2), I am encountering a compilation error in Java when attempting to use `ZMQ.DISH`.

The error message is as follows:
`[ERROR] /path/to/ZmqTmDataLink.java:[19,39] cannot find symbol [ERROR] symbol: variable DISH [ERROR] location: class org.zeromq.ZMQ`

I've updated to the latest version of `jeromq`, but the issue persists, suggesting that `jeromq` may not yet support these UDP-based socket types.

Could you please confirm whether `ZMQ.DISH` and `ZMQ.RADIO` are currently supported in `jeromq`? If not, is there any plan to include support for these socket types in future releases? Additionally, is there any recommended workaround for using ZeroMQ over UDP in Java?

Thank you for your assistance!

Best regards,  
Tsai-Hsuan Stasy Hsieh

**Comment by fbacchella** [comment]
Can you show the offending line ? UDP is indeed not supported, but RADIO/DISH is: https://github.com/zeromq/jeromq/tree/master/jeromq-core/src/main/java/zmq/socket/radiodish

**Comment by thstasy** [comment]
Oh sure, I'll reproduce it ASAP on Monday. Thank you!

Fabrice Bacchella ***@***.***> 於 2024年9月27日 週五 15:06 寫道：

**Comment by thstasy** [comment]
Hi, 
Here is the offending line(underlined in blue), and the error message log screenshots:
![Screenshot from 2024-09-30 11-41-13](https://github.com/user-attachments/assets/1b15a62e-f3c6-4f89-9e7e-36c6d4c7f099)
![Screenshot from 2024-09-30 11-43-40](https://github.com/user-attachments/assets/b69cefaa-3597-44a4-903a-31be79b8ee63)

**Comment by fbacchella** [comment]
Screenshoots are not very usefull to search for text.

If you look at the source code: https://github.com/zeromq/jeromq/blob/master/jeromq-core/src/main/java/org/zeromq/ZMQ.java
```

You can have a look at https://github.com/zeromq/jeromq/blob/master/jeromq-core/src/main/java/org/zeromq/SocketType.java.
// Socket types, used when creating a Socket. Note that all of the int types here is
// deprecated, use SocketType instead
```

**Comment by fbacchella** [comment]
Better documentation was added in b4bdc98, closing this ticket as there is nothing to add.
