### ISSUE TITLE
Once socket enters exceptional state via SNDHWM or RCVHWM and nonblocking is used

### ISSUE THREAD

**Issue by ljackson** [zeromq/jeromq#113]
version 0.3.1

The socket will never be able to come out of the exceptional state as the recv and send methods continue to return exceptional state e.g. null.

I have some new code I am about to opensource that uses the NIO selectablechannel and I found that the default HWM of 1000 under large load can cause the socket to get into the exceptional state and never come out. If I get around to it I will add a unit test to reproduce.

**Comment by daveyarwood** [comment]
@ljackson Do you have any additional information about this issue? There is not enough information here to investigate or take action.

**Comment by daveyarwood** [comment]
Closing this issue, as there has been no further conversation.
