### ISSUE TITLE
Jeromq has no logging

### ISSUE THREAD

**Issue by fernandezpablo85** [zeromq/jeromq#128]
Though there are some log imports commented out, namely on Mailbox.java and Pipe.java.

Is this by design? do you guys don't want logging on jeromq?

**Comment by daveyarwood** [comment]
There has been a lot of great discussion here, but ultimately I agree with @trevorbernard:

> This bikeshedding is going no where. Pull request are much more valuable. Just be cognizant that jeromq runs on mobile devices as well.

If anyone is interested in adding logging to JeroMQ in any form, a PR would be great, and we will likely merge it if there are no demonstrable performance problems.
