### ISSUE TITLE
JeroMQ pub/sub crashes when used across platforms

### ISSUE THREAD

**Issue by kbinpgh** [zeromq/jeromq#138]
I have an ARM device that runs a native C build of ZMQ v 3.2.0. I'd like it to be able to communicate with a host running a Java application built with JeroMQ (v 3.2.2 iirc). However, when I setup pub/sub endpoints, the native C endpoint runs into an assertion failure and exits: 

"Assertion failed: options.recv_identity (......\src\socket_base.cpp:990)"

From network traces, I can see that the flags preceding the message data are differently populated by JeroMQ and by libzmq, which is likely the cause of the problem. 

Are there any protocol incompatibilities between the two versions in use? I fail to see how that is possible, since they only differ by a patch version. Any help is appreciated...

**Comment by daveyarwood** [comment]
@kbinpgh Do you have any additional insight on this issue? I think it should be closed unless we can point to a definitive issue in the JeroMQ codebase.

**Comment by daveyarwood** [comment]
Closed due to lack of discussion / follow-up.
