### ISSUE TITLE
setLinger() throws CtxTerminatedException on shutdown

### ISSUE THREAD

**Issue by HeinrichHartmann** [zeromq/jeromq#147]
I am trying to shutdown sockets and context properly in the following situation:
- Thread B is blocking on send() and has buffered messages waiting for delivery.
- Thread A wants to shutdown the application.

Following #116 and [interrupt.java](https://github.com/zeromq/jeromq/blob/master/src/test/java/guide/interrupt.java) the correct shutdown pattern seems to be:
1. Thread A calls ctx.term() and blocks
2. In thread B send() throws an ETERM exception.
3. Catch ETERM exception and close socket in catch block

This works if there are no outgoing messages queued at the socket. Otherwise
ctx.term() will wait until the (infinite) linger period is expired. Therefore we have 
to call setLinger(0) before closing the socket (cf. [ZContext.java#L128](https://github.com/zeromq/jeromq/blob/56c5e4102737ad3e9cdaf1fe91ef4d49453a011b/src/main/java/org/zeromq/ZContext.java#L128)).
However, doing so will raise a CtxTerminatedException.

The obvious workaround is to set the linger period when creating the socket, but this  is not always intended. What is the best practice to handle this situation?

Also, I noticed that the libzmq 4.0.0 has improved its shutdown behavior, e.g. by introducing a new non-blocking context shutdown method. Are there plans to port this feature to jeromq?

Here is a minimal test case ([gist](https://gist.github.com/HeinrichHartmann/9681888)).

```
import org.zeromq.ZMQ;
import org.zeromq.ZMQException;

public class TermOnSend {
    public static void main(String[] args) {
        final ZMQ.Context ctx = ZMQ.context(1);

        Thread threadB = new Thread(new Runnable() {
            @Override
            public void run() {
                ZMQ.Socket socket = ctx.socket(ZMQ.PUSH);

                try {
                    socket.send("Some message"); // blocks
                } catch (ZMQException e) {
                    socket.setLinger(0); // throws zmq.ZError$CtxTerminatedException
                    socket.close();
                }
            }
        });

        threadB.start();

        // give thread B some time to start up
        try {
            Thread.sleep(20);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        ctx.term(); // blocks and does not return
    }
}
```

**Comment by daveyarwood** [comment]
So the question here is, should we allow `setLinger` as a special case that will not throw the CtxTerminatedException?

If so, it looks like it would just be a matter of changing [these lines](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/SocketBase.java#L217-L219) to:

```java
if (ctxTerminated && option != zmq.ZMQ.ZMQ_LINGER) {
    throw new ZError.CtxTerminatedException();
}
```

**Comment by miniway** [comment]
This looks fine until jeromq adopts the new context shutdown

**Comment by daveyarwood** [comment]
I'm working on a PR for this, but am currently blocked by #372 (how do I run the examples?)
