### ISSUE TITLE
Unit Test testEventConnectRetried failed with branch 0.3.4.

### ISSUE THREAD

**Issue by urbcoder** [zeromq/jeromq#181]
Failed tests:   testEventConnectRetried(org.zeromq.TestZMQ): No event was received

The unit test failed on my Windows 7 machine.  Is ZMQ.EVENT_CONNECT_RETRIED fully implemented?

**Comment by daveyarwood** [comment]
Is this fixed in 0.3.5?

**Comment by eirenik** [comment]
No; was exactly the same for me.

**Comment by daveyarwood** [comment]
Seems like potentially a race condition causing the test to fail sometimes.

I wonder if the fact that the timeout needs to be 1000+ ms in order for the test to pass means we need to fix something in the code somewhere, or if it would be sensible to increase the timeout to 2000 for the test case?

**Comment by daveyarwood** [comment]
Closed via https://github.com/zeromq/jeromq/commit/42ce030bffae941630f1e2d10623826d5d580d86#diff-392de23da68953cd46e5b67897c97132.
