### ISSUE TITLE
Support for ZMQ_TCP_KEEPALIVE_INTVL

### ISSUE THREAD

**Issue by urbcoder** [zeromq/jeromq#182]
Is there a plan to bring in support for CNT, IDLE, and INTVL?  Currently Options.java returns 0 for these.

**Comment by daveyarwood** [comment]
http://api.zeromq.org/4-2:zmq-setsockopt

These are ZMQ 4.2 features, so I think these features may be part of #59 .

**Comment by daveyarwood** [comment]
I believe these features have been added. Please re-open if that is not the case.
