### ISSUE TITLE
On Getting an Out-of-Band Snapshot

### ISSUE THREAD

**Issue by gkaltman** [zeromq/jeromq#196]
Hi,
I have a question related to the scenario described in the Guide, chapter "Getting an Out-of-Band Snapshot". To synch the client and the server, the Guide says: 

> "The client first subscribes to updates and then makes a state request. This guarantees that the state is going to be newer than the oldest update it has."

What if the state request gets executed on the server before the subscribe request? Can we get into the following scenario?

A. The state request is executed and the client gets the state.
B. Updates flow but they are not caught by the client because the subscribe request has not been yet received by the server.
C. The subscribe request is received by the server. The client will get the following updates but missed those from B

Thank you.

**Comment by kallehuttunen** [comment]
@gkaltman Did you ever find an answer for this?

**Comment by trevorbernard** [comment]
Yes it is possible that subscribing to the stream takes longer than requesting the state. One way to check if you're eventually consistent system is indeed correct is to use a monotonically increasing sequence number on each event. You subscribe to an event stream and queue up any events that come in then request an out of band snapshot. The snapshot will also have a version # of it's current state. Drop all events that are less than and equal to the state's version number.. Then replay any subsequently queued events if they exist. if the queue is empty, check the next event's sequence number that comes in. If there is a greater than 1 difference between the state's version #, then you have a consistency problem. Just retry the logic until you have a consistent view of the world.

**Comment by kallehuttunen** [comment]
Thanks for the answer. In that case I think the text in the guide is bit misleading, because it states that

> The client first subscribes to updates and then makes a state request. This guarantees that the state is going to be newer than the oldest update it has.

This makes it sound that to guarantee consistency it's enough to just do the subscription first.
