### ISSUE TITLE
zmq.Poller.run() throws an IllegalStateException, but I'm not able to catch it

### ISSUE THREAD

**Issue by erichfosse** [zeromq/jeromq#209]
The exception only occurs when running on a Raspberry Pi, and this is my stack trace:

Exception in thread "iothread-2" java.lang.IllegalStateException: BOTTOM
        at zmq.Req$ReqSession.push_msg(Req.java:187)
        at zmq.V1Decoder.message_ready(V1Decoder.java:139)
        at zmq.V1Decoder.next(V1Decoder.java:49)
        at zmq.DecoderBase.process_buffer(DecoderBase.java:124)
        at zmq.StreamEngine.in_event(StreamEngine.java:307)
        at zmq.IOObject.in_event(IOObject.java:101)
        at zmq.Poller.run(Poller.java:237)
        at java.lang.Thread.run(Thread.java:744)

This happens when the connection to a REP socket gets unstable (i.e. network trouble or problems with the application running the REP socket).
In the application that crashes, I'm able to catch most of the IllegalStateExceptions, and when they do occur, I simply close the socket, and re-open it. I'd like to do that here as well, but I can't see where I'm supposed to catch this one.

Any help is appreciated.

**Comment by stephanarts** [comment]
I have the same problem with 0.3.4, I will make a new build and test it there.

**Comment by stephanarts** [comment]
Two unittests failed, one that could not access google (which is caused by my test-server) and this one:

> -------------------------------------------------------------------------------
> Test set: org.zeromq.ZBeaconTest
> -------------------------------------------------------------------------------
> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.025 sec <<< FAILURE!
> test(org.zeromq.ZBeaconTest)  Time elapsed: 20.01 sec  <<< FAILURE!
> java.lang.AssertionError: expected:<1> but was:<0>
> 	at org.junit.Assert.fail(Assert.java:88)
> 	at org.junit.Assert.failNotEquals(Assert.java:743)
> 	at org.junit.Assert.assertEquals(Assert.java:118)
> 	at org.junit.Assert.assertEquals(Assert.java:555)
> 	at org.junit.Assert.assertEquals(Assert.java:542)
> 	at org.zeromq.ZBeaconTest.test(ZBeaconTest.java:52)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
> 	at java.lang.reflect.Method.invoke(Method.java:597)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
> 	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
> 	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
> 	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
> 	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
> 	at java.lang.reflect.Method.invoke(Method.java:597)
> 	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
> 	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)

What could be wrong here?

**Comment by stephanarts** [comment]
I've ignored the above error and deployed our Apereo CAS Server with the latest version of jeromq on our acceptance-environment.

**Comment by stephanarts** [comment]
This appears to work.

**Comment by erichfosse** [comment]
@trevorbernard Sorry about the delayed response.
I've now tested the latest master on a Raspberry Pi model B+ running on raspbian, and four different computers, respectively running on Windows 7, Windows 8, Ubuntu 14.04 and OSX 10.9, and I haven't managed to reproduce the the issue.

Thanks for your help, Trevor!

**Comment by trevorbernard** [comment]
Awesome, good to hear!
