### ISSUE TITLE
memory benchmarking

### ISSUE THREAD

**Issue by nsampietro** [zeromq/jeromq#231]
Thanks for maintain and extend this marvelous library. I'm just getting my feet wet with JeroMQ, my apologies if the below question sounds trivial.  

I was benchmarking the heap memory usage of the test programs: perf.LocalThr and perf.RemoteThr on this scenario: 
Message size: 2097152 B (2MB) , TCP , 1000 message. 

A few hundred messages after it start the client ( perf.RemoteThr ) reach almost 1GB of memory and crash. Now, it's easy to see why this is happening, for each message, a new chunk of memory is being allocated. I only have to reuse the same message buffer every time.  After that minor change, the heap stays flat at 6 MB.    

The problem I'm facing now is on the "server" side (perf.LocalThr). This code is not running out of memory, but it's using about 100 Mb ...I would like to use the same memory buffer for all incoming messages. I thought this operation was meant to do that :

   zmq_recviov(SocketBase s, byte[][] a, int count, int flags)  on class zmq.ZMQ . ( I wonder why it's not static).

But, this is not the case. The underlining logic also allocates new memory for each incoming message. What I'm missing here?.

Thanks

**Comment by nsampietro** [comment]
#### Pipeline
 
Hello. I have being doing some testing with a simple program that creates a pipeline using JeroMQ push/pull sockets. Code can be found here : https://github.com/nsampietro/jeromqMemTest


Graphically:

source :arrow_right: 	| Step 1 :arrow_right: | Step 2 :arrow_right: | ...Step N :arrow_right: | sink 
------------| ------------- | ------------- | -------------| -------------

The goal was to see how different settings ( HWM, protocol, steps, etc. ) affects the memory usage. I used VisualVM 1.3.8 to monitor the VM heap. The program receives six input parameters : 

Attribute 	| Description
------------| -------------
msg size 	| Message size in bytes
msg count 	| Total number of messages to send down the pipeline.
steps 		| Number of pipeline Steps(N). Note: Total will be N + 2 (source and sink).
HWM 		| Hight Water Mark on pull/push sockets.
protocol 	| protocol ( tcp  / inproc / ipc )
start port 	| Number used to generate the intermediate endpoints addresses.

#### VM Settings
-server -XX:+UseConcMarkSweepGC
-XX:+TieredCompilation
-XX:+AggressiveOpts
-XX:+UseCompressedOops
-XX:+UseBiasedLocking 
-XX:+UseNUMA

-Dcom.sun.management.jmxremote.port=3333 
-Dcom.sun.management.jmxremote.ssl=false 
-Dcom.sun.management.jmxremote.authenticate=false

## Results
Here the result for the first three tests where I set the HWM = 1 trying to achieve minimum memory usage.

#### Test 1. 
Attribute 	| Value
------------| -------------
msg size 	| 2097152 (2MB)
msg count 	| 500
steps 		| 1
HWM 		| **1**
protocol 	| **inproc**
start port 	| 9000

![test1](https://cloud.githubusercontent.com/assets/7051478/5674422/f5b32d70-9777-11e4-8500-a54e21bb9678.png)


#### Test 2. 
Change protocol to **tcp**
![test2](https://cloud.githubusercontent.com/assets/7051478/5674423/f918e86a-9777-11e4-8ffd-fda001730a2f.png)

#### Test 3. 
Change protocol to **ipc**

![test3](https://cloud.githubusercontent.com/assets/7051478/5674425/fe31b20a-9777-11e4-95f1-2d1b74fe642f.png)

#### Comments
With tcp or ipc protocols a few pipeline steps can make memory grow fast if HWM is not set to a proper low value. More realistic tests case scenarios can be explored using this tool. Hopefully it will help gain more insight on memory usage for the pipeline problem.

**Comment by daveyarwood** [comment]
I don't believe there is any further action needed on this issue -- please reopen if you feel differently.
