### ISSUE TITLE
Node not starting when using zmq 

### ISSUE THREAD

**Issue by alvarotrigo** [zeromq/jeromq#237]
I'm porting my node application to another Windows machine (Windows 2012 Server 64 bits) and I'm having troubles to start the webserver.

Whenever I add `node app.js` in the shell to start it, it just doesn't do anything, doesn't show any error and quit the script:

![capture](https://cloud.githubusercontent.com/assets/1706326/5855806/1d82a5ee-a234-11e4-9302-de7b3f87cfca.PNG)

The exact same version of my node application is working without troubes in other 2 Windows 7 64bits machines. So **I'm quite sure that the problem is no on the application itself**, but in some missing software or dlls needed to run ZMQ.

Whenever I comment this line referencing ZMQ (and the related ones) the application runs as expected. It is only when I this line when the application is not able to run:

> var zmq = require('zmq_rep');

What am I missing?

I've installed multiple versions of Microsoft Visual C++ (2008, 2010, 2012, 2013), but not sure if they are needed at all... 

I'm trying to run it on Windows Server 2012 R2 Standard. 
64 bits.

**Comment by trevorbernard** [comment]
Hi @alvarotrigo, JeroMQ is a native Java port of libzmq. You should be asking your question in the appropriate binding's issue tracker or the ZeroMQ mailing list. I'm afraid you won't get much node zmq help here.

**Comment by alvarotrigo** [comment]
Oh, right, sorry :D My mistake.
