### ISSUE TITLE
socket creation causes ~50 open named pipes on CentOS

### ISSUE THREAD

**Issue by davetroiano** [zeromq/jeromq#241]
Creation of a single ZeroMQ socket on CentOS 7.0.1406 causes about 50 named pipes to be opened.  I don't see a jump like this on MacOS 10.10.2 or Ubuntu 12.04.  We're on Oracle's JDK 1.7.0_71 and JeroMQ 0.3.4.  If I debug and step through, I find that it happens in the same stack from [this "Too many open files" issue](https://github.com/zeromq/jeromq/issues/183), in particular right when I step over a native call to create a named pipe.  On large machines we can have hundreds of ZeroMQ sockets open, and we've upped soft /hard ulimits to 100k and 200k to accommodate.  This is plenty on other OSes but not on CentOS 7 given the number of pipes that we see being opened.  We can always add another zero to the ulimit, but has anyone else noticed this behavior discrepancy?

**Comment by trevorbernard** [comment]
Have you also tested OpenJDK as well?

**Comment by davetroiano** [comment]
I have not, I will give that a shot

**Comment by davetroiano** [comment]
I do not observe the same issue with OpenJDK.  thanks for the idea

**Comment by trevorbernard** [comment]
It might be work check out 7u75 as well since it's the latest oracle stable release

**Comment by davetroiano** [comment]
I jumped the gun a little.  There a clear step down in the number of open files -- I see about half the number of open files with OpenJDK compares to Oracle's.  There's still a big discrepancy compared to what I observe on Ubuntu / MacOS though.

**Comment by daveyarwood** [comment]
It's been 2-1/2 years and the codebase has changed significantly. Closing this issue for the time being -- feel free to reopen if this is observed to still be an issue.
