### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by jacek99** [zeromq/jeromq#243]
Looking at this project, it is not clear what license is it released under.

There is a copy of both GPL and LGPL in the root. GPL would make it unusable on our project.

Please clearly create a LICENSE file that specifies explicitly the license, so our legal team can evaluate it and approve, or at least state it explicitly in the main README.md .

Thanks

**Comment by jacek99** [comment]
Hi, it is still not clear. It states it is released under LGPL, but then it refers to COPYING which clearly specifies GPL.

What part of the code is under GPL? The docs?

If GPL does not apply at all, I would recommend you remove COPYING and any references to it. It's an immediate red flag and no-go during any legal license evaluation.

**Comment by hintjens** [comment]
The license is explicitly specified in each source file. The presence of
license texts in the project is for convenience, it does not constitute the
license grant.

The LGPL is always constructed as a derivation of the GPL, thus always
comes as COPYING plus COPYING.LESSER.

**Comment by jacek99** [comment]
OK, thanks. I will point the legal team to this discussion in case they have any concerns.

Appreciate your time, thank you
