### ISSUE TITLE
Closing a socket twice prevent context termination

### ISSUE THREAD

**Issue by CodingFabian** [zeromq/jeromq#245]
Given I use the http://zguide.zeromq.org/java:hwserver
and I modify the http://zguide.zeromq.org/java:hwclient so that i accidentally call 

      requester.close();
      requester.close();

the client no longer terminates but hangs in the reaper thread.

I discovered the issue when i accidentally used try-with-resources (which calls close) but still called close myself.

I am not sure what would be a nice fix, but maybe close() should check if the tag is dead already before sending itself to reaper?

**Comment by trevorbernard** [comment]
Fix commited

**Comment by CodingFabian** [comment]
Thanks for the quick fix @trevorbernard
