### ISSUE TITLE
Spinning in Selector.wait_event when sending message

### ISSUE THREAD

**Issue by manishag** [zeromq/jeromq#251]
Here is the stack trace of spinning thread...CPU usage is 100%.

```
   sun.nio.ch.EPollArrayWrapper.interrupt(Native Method)
   sun.nio.ch.EPollArrayWrapper.interrupt(Unknown Source)
   sun.nio.ch.EPollSelectorImpl.wakeup(Unknown Source)
   java.nio.channels.spi.AbstractSelector$1.interrupt(Unknown Source)
   java.nio.channels.spi.AbstractSelector.begin(Unknown Source)
   sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source)
   sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
   sun.nio.ch.SelectorImpl.select(Unknown Source)
   zmq.Signaler.waitEvent(Signaler.java:136)
   zmq.Mailbox.recv(Mailbox.java:105)
   zmq.SocketBase.processCommands(SocketBase.java:821)
   zmq.SocketBase.send(SocketBase.java:659)
   org.zeromq.ZMQ$Socket.send(ZMQ.java:1302)
   org.zeromq.ZMQ$Socket.send(ZMQ.java:1291)
   com.webaction.jmqmessaging.TcpSender.send(TcpSender.java:49)
```

This happens if you interrupt this thread when it is sending the message and waiting. Is it a known issue?

**Comment by miniway** [comment]
Basically interrupting thread is not welcomed in JeroMQ as Java close Pipe at the interrupt. I've recently added a workaround for thread interrupt. Could you try the latest snapshot?

**Comment by manishag** [comment]
Thanks for your response miniway. I have tried the latest snapshot but it did not help. I believe fix for this issue https://github.com/zeromq/jeromq/issues/172 is what you fixed but it did not fix my issue.

**Comment by daveyarwood** [comment]
Closing this issue, as interrupting the thread is not something I believe we're supporting.

**Comment by daveyarwood** [comment]
See also: #303, which seems related, but does not involve Thread.interrupt.
