### ISSUE TITLE
monitor - endpoints remains

### ISSUE THREAD

**Issue by kmualem** [zeromq/jeromq#256]
Jeromq - Version 0.3.4

I'm currently working on a web application and encountering into a situation which I cannot start a monitor on inproc address X because it's not unregistered before and will remain forever...

I'm using Req socket and Pair to monitor my response from a Router socket.
The idea is to get the updated connectivity status from the monitor thread and if it's not connected, to destroy the sockets and  re-send.

The idea of the code: 

```java
Socket socket = zContext.socket(ZMQ.REQ);
socket.monitor("inproc://test", ZMQ.EVENT_ALL);

// start monitor thread and inside Pair socket
MonitorThread mt = new MonitorThread(zContext, "inproc://test");
new Thread(mt).start()

socket.connect("tcp://127.0.0.1:5556");
socket.send("test".getBytes());
socket.setReceiveTimeOut(100);
byte[] data = socket.recv();

if (data == null) {  // check flag in mt and resend if needed
  socket.monitor(null, 0);  // should stop the monitor
  // stop the monitor Pair socket inside the mt
  // stop and recreate the socket & monitor
  // send again
}
```

it looks like after several loops, the Reaper thread not succeed (or on delay) to stop the monitor of the Req socket - `socket.monitor(null, 0);` and then, the creation of the monitor is stuck! - `socket.monitor("inproc://test", ZMQ.EVENT_ALL);`

Can you please help me?

_EDIT: code formatting - @daveyarwood_

**Comment by daveyarwood** [comment]
@kmualem Is this issue still present with the latest version of JeroMQ?

**Comment by kmualem** [comment]
This is an old issue which I tried before few years. Currently, I'm not using the monitor in our code so I don't have an exact answer for it. Sorry!

**Comment by daveyarwood** [comment]
No worries! I'm closing this issue for now. Feel free to reopen if the issue persists with the latest version of JeroMQ.
