### ISSUE TITLE
Interop with libzmq 4.1.1?

### ISSUE THREAD

**Issue by jameswm** [zeromq/jeromq#257]
Is jeromq taking on zmq 4.1.1 features any time soon?  Has there been any interop testing between libzmq 4.1.1 and jeromq?

**Comment by miniway** [comment]
Unfortunately there're no active progress toward the zmtp 2.0 and the security features yet

**Comment by hintjens** [comment]
FWIW there are Curve25519 classes in pure Java these days:
https://github.com/WhisperSystems/curve25519-java

**Comment by jameswm** [comment]
ok - how about just interop testing with zmq 4.1.1 endpoints that aren't using the newer features?

**Comment by hintjens** [comment]
Interop should work out of the box, with libzmq 4.x.

**Comment by jameswm** [comment]
ok thanks - I'll give it a shot.
