### ISSUE TITLE
Sender thread hangs even after socket destroyed

### ISSUE THREAD

**Issue by manishag** [zeromq/jeromq#259]
I have sender thread that is stuck in the following stack because the client got disconnected while server was sending so the queue became full. I have a separate heartbeat to get notified about client disconnects so when I get the event, I go and destroy the socket using context.destroySocket(socket). That seem to not be enough to unstuck the thread. Can you please help me with correct steps on how to unstuck this thread?

	  at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:200)
	  at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	  - locked <0x11d7> (a sun.nio.ch.KQueueSelectorImpl)
	  - locked <0x11d8> (a java.util.Collections$UnmodifiableSet)
	  - locked <0x11d9> (a sun.nio.ch.Util$2)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	  at zmq.Signaler.wait_event(Signaler.java:135)
	  at zmq.Mailbox.recv(Mailbox.java:105)
	  at zmq.SocketBase.process_commands(SocketBase.java:793)
	  at zmq.SocketBase.send(SocketBase.java:635)
	  at org.zeromq.ZMQ$Socket.send(ZMQ.java:1206)
	  at org.zeromq.ZMQ$Socket.send(ZMQ.java:1197)
	  at com.webaction.jmqmessaging.IpcSender.send(IpcSender.java:54)
	  - locked <0x11da> (a org.zeromq.ZMQ$Socket)

Thanks and really appreciate the help!

Manish

**Comment by miniway** [comment]
Could you please make sure `context.createSocket()` and `context.destroySocket(socket)` are called within the same thread and the created socket is not shared by other thread?

**Comment by manishag** [comment]
Thanks for the response miniway. I was not aware that create and destroy socket should be done in the same thread. Is it still a restriction if I use shadow context to create the socket and destroy the shadow context instead of destroying the socket?

**Comment by miniway** [comment]
It's fine to use shadow context as long as `shadowContext.createSocket()` and `shadowContext.destorySocket(socket)` are invoked on the same thread. So to speak, you should destroy socket where you've created.

**Comment by manishag** [comment]
Thanks again Miniway. Is there a section in guide which explains the reasoning behind this restriction to create and destroy socket in the same thread? The way we are using it is we create a sender thread which creates a socket and sends messages. The sendtimeout is set to -1 because we want reliable delivery of the messages until the client goes away. When the client dies, sender thread is stuck so we need to notify the sender thread that it is ok to drop the messages and exit. The only way we can do it is from a different thread by calling socket.destroy() but since it is from a different thread, it is not working.

If I have to ensure that create and destroy happens in the same thread then I will have to send messages on a different thread from the one I created the socket from which seems little wierd. If I can understand the reasoning behind this restriction, it will help me clarify the model.

Thanks again.

**Comment by miniway** [comment]
In the zeromq quide, http://zguide.zeromq.org/page:all#Making-a-Clean-Exit

> First, do not try to use the same socket from multiple threads. Please don't explain why you think this would be excellent fun, just please don't do it.

Same restriction is applied on most of other bindings.

If you want to check a peer is dead or not, you might need to add a heardbeat. Depending on socket types, socket will drop message or wait forever until a peer is back. You can see lots of example on the guide.
