### ISSUE TITLE
What parts of JeroMQ are thread-sensitive?

### ISSUE THREAD

**Issue by rcsenkbeil** [zeromq/jeromq#260]
Hi, I am fairly new to JeroMQ and was hoping to get a little clarification on using multiple threads for creating/destroying sockets as well as sending/receiving.

[This comment](https://github.com/zeromq/jeromq/issues/259#issuecomment-112984899) states that you need to create and destroy the socket in the same thread, which is easy enough to manage; however, I currently have some small code that is sending messages to the socket in one thread while receiving messages in a different thread. Is there danger in doing that? Are there other threading concerns that I should be concerned with regarding JeroMQ?

As a side note, aside from spinning up new threads, is there an issue with creating a ZMQ context per socket (and using that context with just that socket) versus using a ZMQ context for multiple sockets? I think the ZMQ context (created via `ZMQ.context(1)`) is what keeps the global state, right? 

My small code I was discussing above created a context per socket and then processed sends and receives in different threads. It has not had any problems that I have seen when spinning up 10s of sockets and later killing them. No problems with messages (so far), either.

FYI, I am using `ZMsg.newStringMsg(...).send(socket)` and `ZMsg.recvMsg(socket)` since I found it as it is a nice abstraction on top of the standard `send` and `sendMore` methods. It was also nice to use since it was similar to the `ZMQMessage` found in [akka-zeromq](http://doc.akka.io/docs/akka/2.3.4/scala/zeromq.html), but with even more benefits.

**Comment by miniway** [comment]
Unfortunately It would be danger unless guard the socket with a lock. Please try using `ZMQ.Poller` and a kind of event driven approach.

`ZMQ.context(N)` creates own selector and N of socket worker (IOThread). Even though it's small, it will consume resources and not give you much benefit. Try creating context per thread / or per application with shadowed context, then increasing N if you handle many sockets.

**Comment by rcsenkbeil** [comment]
Thanks. :)
