### ISSUE TITLE
filedescriptors associated with socket never closed

### ISSUE THREAD

**Issue by kmarivoe** [zeromq/jeromq#264]
We have an application that is potentially running for months, and it regularly opens/destroys zmq sockets. We notice that after a while it starts to throw 'too many open file' exceptions, and monitoring the open file handles with 'lsof' also shows that the number of open pipes keeps accumulating while our application is running.

We are using jeromq, latest SNAPSHOT.

After some investigation I have a sneaking suspicion that the culprit is in the jeromq implementation:
- pipes are allocated in the Signaler class
- this signaler is used by a MailBox
- this MailBox is used by the socket
- the socket is managed by the Ctx
- the Ctx, when it destroys a socket just does (Ctx.java, destroySocket method):
```java
           int tid = socket.getTid();
            emptySlots.add(tid);
            slots[tid] = null;
```
(so it just sets the pointer to 'null', it doesn't close the socket.

I didn't find any other place in the source code where the socket/mailbox/signaler was closed.

Following small program reproduces the issue:
```java
    public static void main(String[] args)
    {
        ZContext context = new ZContext();

        while(true) {
            ZMQ.Socket socket = context.createSocket(ZMQ.DEALER);
            socket.connect("inproc://test1");

            context.destroySocket(socket);
        }
    }
```
I know it's not good practice to open/close sockets in tight loops (and our application also doesn't do this), but TMHO this should run without going out of file descriptors after a few seconds.

Any help on this would be appreciated. It seems to be quite easy to fix this (call socket.close before setting the socket reference to null), but wanted to check if this goes against some common practices/correct use of the API.

Regards,
Kim

**Comment by colini** [comment]
I have noticed this pipe "leak" as well.  But in my application the jvm appears to close the pipes during garbage collection.  Apparently the pipes have a finalizer.  Unfortunately the Oracle linux java 7 Pipe class appears to be native code so I can't (easily) confirm this.

**Comment by kmarivoe** [comment]
Hi,

Thanks for your comment. It seems that on Linux with the Oracle JDK there is no finalizer: the lsof count stays on the same level when I trigger garbage collection manually using jconsole. Also when I leave the application running for multiple days the socket count keeps on going up.

Regards,
Kim

**Comment by kmarivoe** [comment]
Ok,

let me take that back: running gc manually seems to fix the issue. Just when you thought that the days of manual garbage collection were over....

Kim

**Comment by spyhunter99** [comment]
Seeing the same issue on 0.33 on Android

**Comment by miniway** [comment]
Thanks for the information I'll take a look.

**Comment by trevorbernard** [comment]
@kmarivoe: Can you try again with latest 0.3.5-SNAPSHOT? I just deployed a build to central

**Comment by kmarivoe** [comment]
Deployed latest version, problem solved.
