### ISSUE TITLE
Problem: JeroMQ doesn't support authentication and security

### ISSUE THREAD

**Issue by trevorbernard** [zeromq/jeromq#267]

**Comment by pietsmit** [comment]
hi Trevor, I am very interested in tackling this problem. Does this issue not depend on the #59  issue? If so, should I rather focus on #59 first? I cannot see that anyone is working on these issues, and I am quite surprised. Am I missing something?

**Comment by trevorbernard** [comment]
Yes it does -- the latest ZMTP version is 3.1. You can find the RFC here: http://rfc.zeromq.org/spec:37. There has been plenty of interest but no one has stepped up with patches. Reading and understanding the RFC is a good start. Like you suggested, I would update to the latest supported ZMTP protocol first then add support for plain security, then curve.

**Comment by pietsmit** [comment]
Thanks, it is quite a task. Hopefully I'll get permission to tackle it, as I believe it would benefit my company a lot. I am currently busy reading the spec. :)

**Comment by trevorbernard** [comment]
I'd be more than happy to help out where I can

**Comment by djelenc** [comment]
Hi all,

I'm very interested in moving towards ZMTP 3.0 and implementing security the features. Have you guys made any progress on this? 

If not, would you be willing to cooperate in pushing this forward? I've been reading the ZMTP RFCs (1-3) and studying the engine classes, and it seems that this is no small task. However, I'd like to give this thing a bit of a push.

**Comment by hintjens** [comment]
I'm happy to help. It's not as big a problem as you might think. We just
need a nacl library in Java, then we can copy the logic of the C++ code, or
the libcurve library. I'm ready to help with the details. I'd guess 2-3
days of work to get the basics working.

**Comment by djelenc** [comment]
Awesome! As for crypto lib, there is a project called [tweetnacl-java](https://github.com/ianopolous/tweetnacl-java) that we may use.

**Comment by hintjens** [comment]
That seems ideal, we're already using tweetnacl as the default encryption
layer in libzmq.

**Comment by hieuleGE** [comment]
Hi all, my name is Hieu and I'd like to help out too. I've been looking forward to a security layer for JeroMQ for one of my web application project. Please let me know

**Comment by djelenc** [comment]
Ok, cool. There seems to be a consensus that ZMTP/3.0 would be nice to have, but patches are missing. Let's fix that.

Before I start messing with internals, I'd like to clear up a few questions pertaining to the JeroMQ ZMTP/2.0 implementation. So.

According to [ZMTP/2.0](http://rfc.zeromq.org/spec:13), the backwards-compatible implementation should:

* Send a 10-octet signature consisting of "%xFF length %x7F" where 'length' is the length of the sender's identity (0 or more octets) plus 1. The length MUST be 8 octets in network byte order. This [occurs in these 3 lines.](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/StreamEngine.java#L235)
* Read the first octet from the other peer
  * If this octet [is not %FF](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/StreamEngine.java#L486), then the other peer is using ZMTP/1.0.
  * If this octet is %FF, then we read nine further octets, and inspect the last octet (the 10th). If [the least significant bit is 0, then the other peer is using ZMTP/1.0.](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/StreamEngine.java#L498)
  * If the least significant bit is not 0, the peer is using ZMTP/2.0 or a later version. We read two further octets, which indicate the **protocol revision**, and the socket type of the other peer. We then encode/decode all further frames on that connection using the ZMTP/2.0 framing syntax. This [happens here.](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/StreamEngine.java#L504) However, the comment on [line 510](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/StreamEngine.java#L510) would be more correct to say Protocol revision (meaning ZMTP/2), right?

Now, what confuses me are the if/elseif/else statements on lines [523](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/StreamEngine.java#L523), [555](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/StreamEngine.java#L555) and [564](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/StreamEngine.java#L564).

To my understanding, current JeroMQ implementation has the peer deciding whether to talk ZMTP/1 or ZMTP/2. Why do we then have three mutually exclusive branches?

**Comment by trevorbernard** [comment]
One of the nice attributes of JeroMQ is that it's a direct port of libzmq v3.2.x and the heart of the logic is essentially the same, save for a few things like I/O and code evolution. Since you have a point of reference, you can follow the progression and intent from v.3.2.5 to v.4.1.4 if you wanted to (albeit slowly). You also have the various ZMTP RFCs for reference.

This has been a few years in the making, I look forward to this happening.

**Comment by tikismoke** [comment]
Hi all,
Domogik project is going to implement curve for security reason.
I maintain the android client wich use org.zeromq:jeromq:0.3.6 but in a soon future my apps would no more been working with such a security.

What's the status of curve implementation in jeromq?

**Comment by daveyarwood** [comment]
@tikismoke If I'm not mistaken, there has been no progress on this.
