### ISSUE TITLE
JeroMQ and C implementation.

### ISSUE THREAD

**Issue by armona** [zeromq/jeromq#279]
I was setting up a connection the other day, where I have two applications.

Sender (JeroMQ) -> PUSH socket
Broker (C library) -> ROUTER to DEALER proxy

For some reason, JeroMQ and the C refuses to send messages after the handshake process.
I tried different setups, the pyzmq and the C implementation works well, but for some reason the JeroMQ is not working. 

Have anyone encountered this issue before?

**Comment by miniway** [comment]
could you specify the versions of each you used at your test? Also it would be much helpful if you paste test cases you have.

**Comment by ArmonA** [comment]
Sorry for the late response. I was able to figure out the issue after some debugging. It seems that I "forgot" to close the socket after using it, therefore JeroMQ didn't send the messages (there was a small quantity of them).
