### ISSUE TITLE
Router socket throws EHOSTUNREACH when sockets overflows

### ISSUE THREAD

**Issue by kmarivoe** [zeromq/jeromq#280]
Hi,

There seems to be an issue in the 'Router' socket: when this socket overflows it gets in a state where it throws a EHOSTUNREACH exception.

The sequence of events that leads to this state:
- we pass a message to 'zMsg.send(...)', and after some steps this ends up in the Router. xsend(Msg msg) method
- the first frame is processed, the identity is correctly extracted, but it can't write to the selected pipe:
```java
                    currentOut = op.pipe;
                    if (!currentOut.checkWrite()) {     <-- RETURNS FALSE
                        op.active = false;
                        currentOut = null;
                        if (mandatory) {     <-- MANDATORY is TRUE
                            moreOut = false;
                            errno.set(ZError.EAGAIN);     <-- this is set
                            return false;
                        }
                    }
```
- currentOut.checkWrite returns false because the pipe is full:
```java
    public boolean checkWrite()
    {
        if (!outActive || state != State.ACTIVE) {   <--- outActive is false
            return false;
        }

        boolean full = hwm > 0 && msgsWritten - peersMsgsRead == (long) (hwm);

        if (full) {
            outActive = false;
            return false;
        }

        return true;
    }
```

- Now, this is all fine, but a bit higher up in the call chain, this happens:
```java
        boolean ret = true;
        Iterator<ZFrame> i = frames.iterator();
        while (i.hasNext()) {
            ZFrame f = i.next();
            ret = f.sendAndKeep(socket, (i.hasNext()) ? ZFrame.MORE : 0); <-- this returns FALSE
        }
```
The loop moves on to the next frame which is empty, and that then triggers (in Router.xsend again):
```java
                   moreOut = false;
                    errno.set(ZError.EHOSTUNREACH);
                    return false;
```

Shouldn't the loop check for the 'false' value and return this to the caller instead of continuing with the next frame?

**Comment by miniway** [comment]
Good catch! It should not continue with the next frame at the send failure.
