### ISSUE TITLE
Possibility to Define ByteBuffer Type for Msg

### ISSUE THREAD

**Issue by markif** [zeromq/jeromq#281]
We use your great library to send big data blobs (one message around 16MB). After receiving the data, we need to buffer the messages for a short period. To overcome OutOfMemoryErrors we use DirectByteBuffers.

Have you considered providing users the possibility to define which type of ByteBuffer Msg should use when receiving data (e.g. users can specify a IntFunction<ByteBuffer> (or a similar interface for < Java 8) that returns a ByteBuffer based on the requested capacity)? In our case, this feature would prevent an additional copy step (HeapByteBuffer of Msg -> DirectByteBuffer).

**Comment by miniway** [comment]
Thank you for the idea. Even though we're trying our best to make JeroMQ compatible and interchangeable with JZMQ, there's one non compatible feature at the` StreamEngine` and the related configuration. https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/Options.java#L301

Please send us a pull request on your idea, we could start deeper discussion on it.
