### ISSUE TITLE
ZMQ_TCP_KEEPALIVE_IDLE option ignored

### ISSUE THREAD

**Issue by galves** [zeromq/jeromq#286]
This should allow you to set the the time after which the the first keep alive probe is sent but it is ignored.

**Comment by miniway** [comment]
This is known issue on JeroMQ. There's no POJO way to set the `tcp keep idle` socket option.

**Comment by galves** [comment]
OK thanks for the clarification.  Please can we add this to the Not supported Features list.

**Comment by daveyarwood** [comment]
This has been added to the list of unsupported features.
