### ISSUE TITLE
Whether can provide local ip socket bind function

### ISSUE THREAD

**Issue by narry** [zeromq/jeromq#293]
hi everyone：
   In my environment, the host has multiple IP addresses, due to the limitations of the firewall, when I use the connect method, I need to specify the local socket IP address,whether can provide the local ip socket bind function? Thank you

**Comment by daveyarwood** [comment]
@narry Can you provide an example scenario? I'm not sure what you mean exactly by "local" socket IP address.

**Comment by daveyarwood** [comment]
It's been over a year; closing this issue as nonproductive.
