### ISSUE TITLE
Possible typo in the method name: setRouterHandlover

### ISSUE THREAD

**Issue by nurgasemetey** [zeromq/jeromq#294]
Hello guys,

It seemed to me that method name name should be **setRouterHandover**.

Source:
    https://github.com/zeromq/jeromq/blob/433914ad5f669f8b1d93d18898830ca217f8eec0/src/main/java/org/zeromq/ZMQ.java#L1077

**Comment by miniway** [comment]
good catch!, could you send a pull request for it?
