### ISSUE TITLE
ZBeacon Doesn't Ignore It's Own Beacons

### ISSUE THREAD

**Issue by kevinkreiser** [zeromq/jeromq#296]
The following code will every second print out:

```
/192.168.1.109
127.0.1.1
ZRE�
```

Ie. its own beacon, despite this version of the constructor telling it to ignore its own beacons:

```
import org.zeromq.ZMQ;
import org.zeromq.ZMQ.Socket;
import org.zeromq.ZContext;
import org.zeromq.ZBeacon;
import org.zeromq.ZBeacon.Listener;
import java.net.InetAddress;

public class zmq_test
{
    public static void main( String[] args )
    {
        try{
           zmq_test a = new zmq_test();
           a.run();
        }
        catch(Exception e){}
    }

    private Remote remote;
    private Thread service;

    public void run() {
        remote = new Remote();
        service = new Thread(remote);
        service.start();
    }

    public class Remote implements Runnable {
        private volatile boolean running = true;
        public Remote() {  }

        private byte[] make_beacon_message(int port) {
            //zre protocol
            byte msg[] = new byte[] { 'Z', 'R', 'E', '\1', '\0', '\0', '\0', '\0', '\0', '\0',
                                      '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0',
                                      (byte)((port >> 8) & 0xFF), (byte)(port & 0xFF) };
            return msg;
        }

        public void abort() {
            running = false;
        }

        public void run() {
            //random port in suggested IANA range
            ZContext context = new ZContext();
            Socket service = context.createSocket(ZMQ.REP);
            int port = service.bindToRandomPort("tcp://*", 49152, 65535);
            //beacon for service discovery on reserved zre discovery port
            byte[] msg = make_beacon_message(port);
            ZBeacon beacon = new ZBeacon("255.255.255.255", 5670, msg, true);
            beacon.setPrefix(new byte[]{'Z', 'R', 'E', 0x01});
            beacon.setListener(new Listener() {
                @Override
                public void onBeacon(InetAddress sender, byte[] beacon) {
                    System.out.println(sender.toString());
                    try{
                        System.out.println(InetAddress.getLocalHost().getHostAddress());}
                    catch(Exception e){}
                    System.out.println(new String(beacon));
                }
            });
            beacon.start();
            //listen for requests
            while(running) {
                byte[] bytes = service.recv();
                if(bytes != null) {
                    //TODO:
                }
            }
            try { beacon.stop(); } catch (Exception e){}
            service.close();
            context.close();
        }
    }

}
```

Indeed stepping through with the debugger one can see that this line:

https://github.com/zeromq/jeromq/blob/master/src/main/java/org/zeromq/ZBeacon.java#L211

Turns out to be `false` because usually you'll get something like `127.0.0.1` out of `InetAddress.getLocalHost().getHostAddress()` where as the `senderAddress.getHostAddress()` will be what you might see in `ifconfig` ie. `192.168.1.107` or something.

**Comment by sjohnr** [comment]
I was just working on porting ZBeacon to jzmq-api and got the same problem on the build server. Any ideas  about how to fix it? Is there a definitive way to determine that the sender returned by `DatagramChannel.receive(ByteBuffer)` is the same as `InetAddress.getLocalHost()`?

**Comment by kevinkreiser** [comment]
ive been using jeromq for android, and it is indeed quite easy to ignore ones one messages using information from: http://developer.android.com/reference/android/net/DhcpInfo.html

which has ones ip address from the perspective of the gateway. surely something similar exists in the standard java network apis?

**Comment by daveyarwood** [comment]
@kevinkreiser @sjohnr Are you still experiencing this problem using the latest version of JeroMQ?

**Comment by kevinkreiser** [comment]
@daveyarwood im happy if you want to close this issue. i worked around it and havent tried it without the work around since. its very possible that at this point i no longer need the work around so please dont hold the issue open on my account!

**Comment by daveyarwood** [comment]
Alright -- closing for now. We can always reopen this issue if it is found to still be a problem now.
