### ISSUE TITLE
ZBeacon Fatal Exception on Network Unreachable

### ISSUE THREAD

**Issue by kevinkreiser** [zeromq/jeromq#297]
So in the czmq implementation of `zbeacon` your network can go away, and you'll get messages like this:

    D: 15-11-01 20:10:42 zsys_udp_send: failed, reason=Network is unreachable
    D: 15-11-01 20:10:44 zsys_udp_send: failed, reason=Network is unreachable
    D: 15-11-01 20:10:46 zsys_udp_send: failed, reason=Network is unreachable

~~And when the network comes back it just starts working again. This is excellent and essentially how the other zmq socket types also seem to work (connectedness is pretty much hidden from the user of the api for most use cases).~~

Update: actually the czmq implementation doesnt start working again (just stops logging error messages) when the connection comes back. It doesn't crash the program though.

Unfortunately it seems the jeromq implementation `ZBeacon` is not yet robust to this. I am working on an android application and so handling intermittent connectivity is fairly important to me. Anyway here's a stack trace from when the wireless goes out:

    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime: FATAL EXCEPTION: Thread-16317
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime: Process: kevinkreiser.lapse, PID: 25311
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime: java.lang.RuntimeException: java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime:     at org.zeromq.ZBeacon$BroadcastClient.run(ZBeacon.java:150)
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime:  Caused by: java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime:     at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime:     at libcore.io.IoBridge.sendto(IoBridge.java:529)
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime:     at java.nio.DatagramChannelImpl.send(DatagramChannelImpl.java:313)
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime:     at org.zeromq.ZBeacon$BroadcastClient.run(ZBeacon.java:143)
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime:  Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime:     at libcore.io.Posix.sendtoBytes(Native Method)
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime:     at libcore.io.Posix.sendto(Posix.java:171)
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime:     at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:270)
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime:     at libcore.io.IoBridge.sendto(IoBridge.java:527)
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime:     at java.nio.DatagramChannelImpl.send(DatagramChannelImpl.java:313) 
    11-01 20:08:36.897 25311-25387/kevinkreiser.lapse E/AndroidRuntime:     at org.zeromq.ZBeacon$BroadcastClient.run(ZBeacon.java:143) 

I'll have a quick look at the code to see if I could offer up a PR to ~~make this warn when network is down and start working again when it comes back up~~ allow the calling application the ability to trap this exception.

**Comment by kylemallory** [comment]
I am seeing this same behavior in the current version, @c-rack I see this was closed a while ago, but there doesn't appear to be any explanation. Was this fixed?  Am I seeing something different? (I realize its been a "minute" since being closed).

**Comment by trevorbernard** [comment]
@kylemallory you can specify your own uncaughtexception handler

**Comment by kevinkreiser** [comment]
@kylemallory this was the PR that i made back then to address it: https://github.com/zeromq/jeromq/pull/299

**Comment by kylemallory** [comment]
Awesome.  Thanks!
