### ISSUE TITLE
Trailing bytes > limit should not be sent from array backed ByteBuffers

### ISSUE THREAD

**Issue by markif** [zeromq/jeromq#305]
There is an issue when array backed ByteBuffers are handed to Msg. In case ByteBuffer's position = 0 and limit < capacity the full underlying array (with trailing bytes > limit) will be sent.

Additionally, there are cases when someone (like me) wants to send ByteBuffers with position > 0.

**Comment by markif** [comment]
I have created a pull request (https://github.com/zeromq/jeromq/pull/306) concearning this issue. Let me know what you think.

**Comment by trevorbernard** [comment]
Looks good -- merged

**Comment by yagnasrinath** [comment]
I think trailing bytes(exactly 7) are still being added to larger frames(Like 4MB) in the latest versions as well.
