### ISSUE TITLE
Busy-Wait in ZBeacon.BroadcastServer

### ISSUE THREAD

**Issue by dreadworks** [zeromq/jeromq#318]
As I was wondering why my little application consumes 100% CPU on one of the cores when using the ZBeacon implementation, I stumbled upon

https://github.com/zeromq/jeromq/blob/7b848367f4163fd5b5aba27613f6eef52042b42e/src/main/java/org/zeromq/ZBeacon.java#L189

Which stems from the original implementation. Is there a reason for using a non-blocking wait?
Anyway, I changed it locally to `true` and everything is still working but without spinning the cpu clock.

**Comment by vimalanandans** [comment]
I face same problem. I couldn't use this Zbeagon for the same reason.

**Comment by daveyarwood** [comment]
Closed via #470, which provides an extra argument in the ZBeacon constructor that allows you to disable the blocking behavior by passing in `false`.
