### ISSUE TITLE
Netstat: JeroMQ don't really close Sockets (after programm closed)

### ISSUE THREAD

**Issue by msfox** [zeromq/jeromq#321]
[ZeroMQTest.zip](https://github.com/zeromq/jeromq/files/119161/ZeroMQTest.zip)
I have a problem with open sockets, if java programm are closed. I extracted the important code from my large project. Run the code an open a comandLine. Run "netstat -a -n". Now you see, that many sockets (ports >50.000) are waiting.
Closing ports in JeroMQ with (look at attached file)
`_internalSocket.setReceiveTimeOut(1);
_internalSocket.setLinger(1);
_internalSocket.unbind(_internalConnectionString);
_zeroMqContext.destroySocket(_internalSocket);
_externalPeerSocket.setReceiveTimeOut(1);
_externalPeerSocket.setLinger(1);
_externalPeerSocket.disconnect(_externalConnectionString);
_zeroMqContext.destroySocket(_externalPeerSocket);
_zeroMqContext.destroy();`
Note: The many starts and closeds simulate the many junit-test. There is the same problem.

**Comment by c-rack** [comment]
Could you please give some example lines from your "netstat -a -n" output?

I assume you see many `CLOSE_WAIT` states, but that is normal and explained here:
https://superuser.com/questions/173535/what-are-close-wait-and-time-wait-states

**Comment by msfox** [comment]
Am 05.02.2016 um 18:28 schrieb Constantin Rack:
>
> Could you please give some example lines from your "netstat -a -n" output?
>
> I assume you see many |CLOSE_WAIT| states, but that is normal and 
> explained here:
> https://superuser.com/questions/173535/what-are-close-wait-and-time-wait-states
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/zeromq/jeromq/issues/321#issuecomment-180455074>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by msfox** [comment]
Hello,

my own Windows is a german language. Here is the state "WARTEND".
I ask my colleague with an english WindowsOS. He said the state of ports 
is "TIME_WAIT".

TIME_WAIT isn't normaly...

Best Reguards
Maik

Am 05.02.2016 um 18:28 schrieb Constantin Rack:
>
> Could you please give some example lines from your "netstat -a -n" output?
>
> I assume you see many |CLOSE_WAIT| states, but that is normal and 
> explained here:
> https://superuser.com/questions/173535/what-are-close-wait-and-time-wait-states
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/zeromq/jeromq/issues/321#issuecomment-180455074>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by msteinhoff** [comment]
From what I see, TIME_WAIT is perfectly normal and is not something you should worry about.

A quick google search yields this SO post with a detailed explanation why TIME_WAIT happens:
http://serverfault.com/a/329846

**Comment by daveyarwood** [comment]
@msfox It appears that it is expected behavior for sockets to remain in TIME_WAIT state for some time after destroying sockets. Would you say this issue can be closed?

**Comment by daveyarwood** [comment]
No response in over a year, and I think TIME_WAIT is expected behavior, as described above. Closing this issue.
