### ISSUE TITLE
No snapshot artifact on sonatype

### ISSUE THREAD

**Issue by ppatelclearpool** [zeromq/jeromq#325]
https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/

**Comment by HughPowell** [comment]
I'd also like this to use the new ZSocket implementation.  Can anyone do this or do we need special privileges from Sonatype?  If anyone can, I'll have a poke around and see what I can do.

**Comment by miniway** [comment]
@trevorbernard could you please handle this? I think I got the permission but I might misconfigured my dev env. I'm getting `401 Unauthorized` at deploy

**Comment by HughPowell** [comment]
Do we want to automatically deploy on a successful build?  If we do then https://gist.github.com/neothemachine/4060735 suggests it's possbile.

Would this require an automatic version bump as well?

**Comment by trevorbernard** [comment]
@miniway I will add it to my todo list over the next couple of days

@HughPowell I will attempt to automatically deploy snapshot builds to central
