### ISSUE TITLE
What is the status of the MPL license changes to this project?

### ISSUE THREAD

**Issue by lbustelo** [zeromq/jeromq#326]
The MPL statement at http://zeromq.org/area:licensing has been there for a while but it is hard to tell what projects it will apply to.

Is there any work in progress on moving this project to MPL?

**Comment by hintjens** [comment]
We've done this for some smaller projects and most newer projects. The
larger, older ones are a challenge.

**Comment by lbustelo** [comment]
So can I read that as "Not Likely" for this project? 

We use Jeromq in https://github.com/apache/incubator-toree. This is a Kernel for Jupyter. Apache will not let us put a release until we resolve our dependency on LGPL. Are there any options for Scala/JVM that have a friendlier license and are kept up-to-date?

**Comment by c-rack** [comment]
We could give it a try. There are 38 contributors and all of them must agree with the change. It's a challenge, but maybe worth the effort. @hintjens do you want to do this or shall I handle this?

**Comment by hintjens** [comment]
It's not unlikely for JeroMQ, it'd need a review of the contributors. We
did this successfully for CZMQ, and was not painful.

**Comment by hintjens** [comment]
38 is going to be fine. You can use the zyre issue as a template. If you
can handle it, that'd be great. See:
https://github.com/zeromq/zyre/issues/327

**Comment by lbustelo** [comment]
@hintjens @c-rack I think this is excellent... Thanks!

**Comment by c-rack** [comment]
Opened #327 for the license migration

**Comment by c-rack** [comment]
Actually, there are only 32 contributors. 38 is the figure including contributors including merge commits.

**Comment by lbustelo** [comment]
Any sense of how hard it would be to get those last 8 folks to participate in #327

**Comment by hintjens** [comment]
This is how it always happens. Someone needs to contact them individually
and ask them to go check the issue. There will be one or two who don't
respond ever.

In those cases you need to remove/rewrite their code, after a week or so.
It is not a problem: you made a best effort to contact them and if they
don't reply then they clearly don't care about their code, and this will
satisfy any judge (which is what you always aim for with such matters).

**Comment by lbustelo** [comment]
@hintjens We took the liberty of sending an email to the remaining contributors this morning... It got the attention of one more.

**Comment by c-rack** [comment]
@lbustelo thanks for doing that!

@hintjens do you think it would be worth adding a section to C4.1 process how to handle license changes? For example: contributors have to respond within 4 weeks; otherwise silence equals consent. If the contribution is made after such addition to C4.1, it would be much easier to change licenses in future, also for other projects that have adopted this process.

**Comment by hintjens** [comment]
You can't regulate this unless you make every contributor explicitly accept
the C4, which is onerous.
