### ISSUE TITLE
latency is very high when using router and dealer and having some load

### ISSUE THREAD

**Issue by meteorgan** [zeromq/jeromq#329]
I wrote an example of router and dealer.<br/>

In server, using router and dealer to receive client request and do load balance, just like the example.

    public class MtServer {
	    private static Logger logger = LoggerFactory.getLogger(MtServer.class);
	    static class Worker extends Thread {
		private ZMQ.Socket worker;
		
		public Worker(ZMQ.Context context) {
			worker = context.socket(ZMQ.REP);
			worker.connect("inproc://workers");
		}
		
		public void run() {
			while(true) {
				byte[] recs = worker.recv();
				String message = new String(recs);
				String threadName = Thread.currentThread().getName();
				logger.info("thread[{}] receive [{}]", threadName, message);

				logger.info("server added [{}]", message);
				worker.send(message.getBytes(), 0);
				logger.info("server send [{}] back to client", message);
			}
		}
	}
	
	public static void main(String[] args) {
		ZMQ.Context context = ZMQ.context(1);
		ZMQ.Socket clients = context.socket(ZMQ.ROUTER);
		clients.bind("tcp://*:5556");
		
		ZMQ.Socket workers = context.socket(ZMQ.DEALER);
		workers.bind("inproc://workers");
		for(int i = 0; i < 2; ++i) {
			Worker worker = new Worker(context);
			worker.start();
		}
		
		ExecutorService executors = Executors.newFixedThreadPool(1);
		for(int i = 0; i < 30; ++i) {
			executors.submit(new Runnable() {
				public void run() {
					double pi = 0;
					for(int i = 0; i < 100000000; i++) {
						pi += Math.pow(-1, i) / (2 * i + 1) * 4;
					}
					logger.info("pi = {}", pi);
				}
			});
		}
		logger.info("add all jobs");
		
		ZMQ.proxy(clients, workers, null);
		
		clients.close();
		workers.close();
		context.term();
	}
    }

In client, send message every 100ms, and wait to receive response.

    public class HwClient extends Thread {
	    private static Logger logger = LoggerFactory.getLogger(HwClient.class);
	
	    @Override
	    public void run() {
		String id = UUID.randomUUID().toString().replace("-", "");
		ZContext context = new ZContext();
		ZMQ.Socket requester = context.createSocket(ZMQ.REQ);
		requester.connect("tcp://127.0.0.1:5556");
		
		int seq = 0;
		while(!Thread.currentThread().isInterrupted()) {
			String message = id + "-" + seq;
			requester.send(message.getBytes(), 0);
			
			logger.info("client[{}] send [{}] to server", id, message);
			long t1 = System.currentTimeMillis();
			byte[] r = requester.recv();
			long t2 = System.currentTimeMillis();
			logger.info(id + " receive [{}] back from server spend {}ms", message, t2-t1);
			
			try {
				TimeUnit.MILLISECONDS.sleep(100);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
			seq++;
		}
		
		context.close();
	}
	
	   public static void main(String[] args) {
		HwClient client = new HwClient();
		client.start();
	}
    }

My problem is sometimes the latency for client to receive response(t2 - t1) is very large, in this example is maybe 8s and related to the time of computing pi in server, if I reduce the loop times in computing pi, the latency will reduce too. Is I did anything wrong? any advice, thanks!

**Comment by msteinhoff** [comment]
Why are you computing pi in the server?
From what I see it is not related to the ZMQ sockets at all.
Does the problem still exists when you remove the pi code?

**Comment by meteorgan** [comment]
if removing the pi code, then there is no large latency. I compute pi to add some load to the server, my problem is why compute pi affect the latency.

**Comment by msteinhoff** [comment]
I don't know, I have no experience with high-load systems.
@trevorbernard @miniway is such behavior expected?

**Comment by meteorgan** [comment]
It seems relate to thread schedule, if i add TimeUnit.MICROSECONDS.sleep(1) in the pi code, it works fine. And I have written simlar code(no router and dealer, server just receives message, and writes back to client, while having a thread compute pi) in netty and java socket, all have this problem.

**Comment by msteinhoff** [comment]
Okay, so I'd say it's not JeroMQ related. Would you close the issue then?
