### ISSUE TITLE
Pub/Sub with 2 Android devices

### ISSUE THREAD

**Issue by mbmc** [zeromq/jeromq#339]
I'm able to run a pub/sub example on a single device, but if I use 2, one can't get any messages.

Publisher:
```
context = ZMQ.context(1);
socket = context.socket(ZMQ.PUB);
socket.bind("tcp://*:5556"); // device IP is 192.168.10.100
socket.send(TOPIC + " " + message)
```

Subscriber:
```
context = ZMQ.context(1);
socket = context.socket(ZMQ.SUB);
socket.subscribe(TOPIC.getBytes());
socket.connect("tcp://192.168.10.100:5556"); // device IP is 192.168.10.101
final String message = new String(socket.recv());
```

Both devices are on the same network, and seems that all ports are opened. Any help will be appreciated, thanks.

**Comment by mbmc** [comment]
If the publisher is started on a windows 10 machine, the subscriber is working on mac and android.
If started on mac or android, the port seems not to be visible from another device.

**Comment by mbmc** [comment]
The issue seemed to be related to a DHCP problem in my local network. Once I switched to a different network, things worked as expected.

**Comment by andrewchilicki** [comment]
Hello,
I am running into the same issue now as well; seems to be only the side that calls "connect" rather than "bind" is working. Can you please explain more about how you solved the network DHCP issue? Thanks!

**Comment by AdamWardVGP** [comment]
Apologies if commenting here isn't the right place to do so, but I personally encountered a similar problem myself on Android but with the 'hello world' Req/Rep tutorial.

My issue happened to be that android emulators are actually isolated from the network that the development machine itself is connected to: https://developer.android.com/studio/run/emulator-networking#networkaddresses

I've switched to testing with two physical devices myself and resolved my issue that way.

The Android docs do have solutions for running two interconnected emulators side by side but I personally haven't tried it yet:
https://developer.android.com/studio/run/emulator-networking#connecting

**Comment by ananddvlp** [comment]
i am using netmq publisher in windows server...i want o connect zeromq subscriber from android app ..plz share zromq java android code ..
