### ISSUE TITLE
sub cann't recv() the message

### ISSUE THREAD

**Issue by hahafeixiu** [zeromq/jeromq#343]
# I would like to know the specific code location discard message？ThankYou!!

The jeromq version I used is 0.3.4; And the code is shown in the followings:
# the middle is :

```
Socket frontend = ctx.createSocket(ZMQ.XSUB);
frontend.bind(frontConnectStr);
Socket backend = ctx.createSocket(ZMQ.XPUB); // Backend socket talks to workers over TCP
backend.bind(backConnectStr);
ZMQ.proxy(frontend, backend, null); // Connect backend to frontend via a proxy
```
# the sub is:

```
ZMQ.Context context = ZMQ.context(1);
ZMQ.Socket subscriber = context.socket(ZMQ.SUB);
subscriber.connect(bindAddr);
subscriber.subscribe(subChannel.getBytes());
// Initialize random number generator
while (!Thread.currentThread ().isInterrupted ()) {              
  byte[] sendData = subscriber.recv(0);
```

The problem is: when much message is quickly published, the sub can not receive it (any message can't be received);  
I have confirmed the packets and found that the message has arrived at the sub by wireshark; 
The code runs normally, so I think the missed packets in the sub may be the problem.
so I need to know the specific code location about the discard message, can someone help me? Thank you! 
Any suggestion or guidance is welcomed,thank you!

_EDIT: code formatting - @daveyarwood_

**Comment by AjitNambiar** [comment]
To put it right , this is a slow consumer issue. The subscriber Queue keeps growing while the dequeuing  is slow. How can we make Subscriber discard stale data and accept only latest ones. e.g say any data older than 1 second or 10 seconds be discarded. OR at least have some feature where we setRcvHWM on subscriber and the subscriber discards all elements in queue and start afresh when HWM is reached.

Please let me know if there is anything already there to take care of slow consumers.

Thank you.

**Comment by daveyarwood** [comment]
Is that a bug in JeroMQ or a more general issue with ZeroMQ?

**Comment by AjitNambiar** [comment]
Since jeromq is pure java implementation of 0mq,
This issue can be solved in jeromq by providing option to set queue size at subscriber

**Comment by daveyarwood** [comment]
What I mean is, is this a general problem with the ZeroMQ model? If it is, I'd be curious how other ZMQ libraries solve it.

**Comment by daveyarwood** [comment]
It isn't clear that this is an issue with JeroMQ specifically; closing.
