### ISSUE TITLE
Reusing buffers after sending - possible?

### ISSUE THREAD

**Issue by devilboy505** [zeromq/jeromq#344]
I was wondering if it's possible to reuse byte arrays or ByteBuffer instances after calling send(), or will it result in data corruption? There are some background threads in the ZMQ context, so is it possible that these threads still need the buffer intact after the main thread has moved on from calling send?

Best,
greg

**Comment by miniway** [comment]
Unfortunately no. `send` is internally queueing to a internal array.

**Comment by devilboy505** [comment]
You are right. I tried reusing buffers and it resulted in data corruption.

What would be the right place to add a callback function to add the array back to a pool of reusable arrays once done sending or notify us in a similar fashion?

Thanks,
greg

**Comment by markif** [comment]
MsgAllocator (https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/MsgAllocator.java) might be a starting point. You can register your custom MsgAllocator in https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/Options.java (e.g. socket.base().setSocketOpt(zmq.ZMQ.ZMQ_MSG_ALLOCATOR, new MyNewReusingByteBuffersMsgAllocator()). 

Cheers,
Fabian

P.S.
How about adding your implementation to jeromq?

**Comment by daveyarwood** [comment]
It seems that the answer (or at least, one answer) to the original question is that it is possible via MsgAllocator. Closing this issue, as there has not been any further conversation.

**Comment by ptitjes** [comment]
Just for memory, if anyone comes by here, (and as said [here](https://github.com/zeromq/jeromq/issues/351)) there is no callback to the `Msg` instance to signify it is of no use anymore.

For instance, in `Dist` (of the PUB/SUB implementation), message frames that are not matching any subscription are simply dropped: https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/socket/pubsub/Dist.java#L155
