### ISSUE TITLE
When will jeromq rely on libzmq 4.x.x?

### ISSUE THREAD

**Issue by richardchankiyin** [zeromq/jeromq#346]
I want to use jeromq with features ZMQ_REQ_RELAXED and ZMQ_REQ_CORRELATE. However these features are just available in libzmq 4.x.x instead of libzmq 3.2.5. Please let me know how I can use them in jeromq. Thanks.

**Comment by trevorbernard** [comment]
@richardchankiyin Someone will have to port over those features into JeroMQ. Would gladly merge in those features if you submit a pull request.

**Comment by dermesser** [comment]
FWIW, I might submit a PR for this soon-ish (depending on my free time). JFYI.
