### ISSUE TITLE
Is there any callback say the ByteBuffer on send can be recycled (especially reused)?

### ISSUE THREAD

**Issue by GazitGu** [zeromq/jeromq#351]
Hi jeromq team,

Is there a future callback to say the the bytebuffer has been finished used and hence can be returned to pool to reused later? currently i am using socket.sendByteBuffer(bytebuffer) to reduce copy, but i didn't find any method to day when the ByteBuffer can be recycled? i know Netty has a future callback to say that the bytebuffer has completed, and in that callback method i can return the bytebuffer to pool.

thanks for your work.

Gazit

**Comment by trevorbernard** [comment]
@GazitGu Unfortunately, there isn't a callback . Would be more than happy to merge in a pull request if you submitted a pull request
