### ISSUE TITLE
Race condition on monitor

### ISSUE THREAD

**Issue by gbonnefille** [zeromq/jeromq#353]
Our application is a sort of server, opening and closing connections to many clients.
Under heavy load, our application fails to close its connections and stay deadly-locked.

After some analysis, there are many different sources for these dead-lock. Many of them are already reported as issues (#328, #332).

We also found a source of bug which seems not reported yet: a race condition on monitor socket.

Looking at the code, the `monitor_socket` field of `SocketBase` (https://github.com/zeromq/jeromq/blob/v0.3.4/src/main/java/zmq/SocketBase.java#L73) can be accessed concurrently by the user Thread and the internal Thread. So, when the user requests to unregister the monitor socket, the internal thread can fall in a case where it has to emit an event via a monitor socket freshly destroyed.

**Comment by gbonnefille** [comment]
This bug is probably related/solved by #62 .

**Comment by gbonnefille** [comment]
I tried to fix this issue by adding lock (as I did not find any other lock-free solution). It is against the version 0.3.4. Cf. https://github.com/gbonnefille/jeromq/tree/fix-monitor-race-condition-v0.3.4

What are your opinions about this solution?

**Comment by daveyarwood** [comment]
@gbonnefille A specific lock for monitors has been introduced. Are you still having this issue using the latest version of JeroMQ?

**Comment by gbonnefille** [comment]
The code was significantly refactored between my hacks and the newer version, but I think the issue on race condition is solved.
