### ISSUE TITLE
When will an MPL release of the project be made?

### ISSUE THREAD

**Issue by lbustelo** [zeromq/jeromq#360]
Huge 👍 for all the work that went on in #327. Is there an idea of when a release would be made with this new license?

I noticed that the last PR #359 failed on [travis](https://travis-ci.org/zeromq/jeromq/builds/158785683).

**Comment by daveyarwood** [comment]
I'm new here -- not sure what exactly it would entail to be ready for the next release. I imagine we at least need to get the unit tests passing.

A curious thing is that if you look at [the commits](https://github.com/zeromq/jeromq/commits/master), the Travis build only fails sometimes. I wonder if we have some tests that are non-deterministic?

cc @trevorbernard

**Comment by rgbkrk** [comment]
Under C4:

> To make a stable release a Maintainer shall tag the repository. Stable releases SHALL always be released from the repository master.

Basically, any maintainer can opt to make a release. It's probably a good idea to post this to the zmq mailing list so it doesn't drown into issues.

@somdoron - any tips? This would really help a project relying on jeromq that needed the license change from #327.

**Comment by somdoron** [comment]
@rgbkrk Try to contact one of the project maintainer, I'm not sure about jeromq process...

**Comment by trevorbernard** [comment]
I just released v0.3.6 which is licensed under MPLv2

**Comment by rgbkrk** [comment]
Thank you @trevorbernard!

**Comment by lbustelo** [comment]
Thanks!!!

Gino B.
