### ISSUE TITLE
ZMQ.Proxy(router, dealer, null) eating CPU continuously even there are no messages

### ISSUE THREAD

**Issue by sjaini44u** [zeromq/jeromq#365]
Hi 

I am using jeromq library for client server asyn communication, using dealer router communication pattern.
i start proxy between router and dealer socket at application initialization .
Request reply works pretty much fine, but after handling bunch of request, suddenly cpu usage stucks at more than 30% and never comes down. Also GC behavior becomes volatile and abnormal. Request reply still works but there is no sign of relief for CPU usage which becomes concern.

With JProfiler and JVisualVM , it came out that culprit is ZMQ.Proxy.
Could someone please suggest solution for that

**Comment by daveyarwood** [comment]
I wonder if this is an issue specifically with ZMQ.Proxy, or something else?

Do you observe the same CPU-intensive behavior if, instead of using ZMQ.Proxy, you explicitly check each socket for messages as in [this example in the ZMQ guide](http://zguide.zeromq.org/java:rrbroker)?

**Comment by sjaini44u** [comment]
Will try as mentioned and come back to you. Thanks

**Comment by sjaini44u** [comment]
It is showing same behavior . Cpu usage constantly stuck at 30%. JProfiler shows ZMQ.PollItem.readyOps eating the CPU. Any suggestion please

**Comment by andreasweber** [comment]
We had similar issues with CPU usage and file handles with 0.3.5 when using a Poller. We decided to go back to version 0.3.4 - although it's not perfect, it seems to be more stable than 0.3.5. (see #328 and #332). Maybe you should give it a try.
BTW, I haven't tried newest version 0.3.6 yet ...

**Comment by sjaini44u** [comment]
thanks andreasweber , i will give it a try

**Comment by daveyarwood** [comment]
Various improvements have been made to the polling code since this issue was created / since version 0.3.4.

@sjaini44u @andreasweber I'm curious if this is still an issue with the latest version of JeroMQ?

**Comment by daveyarwood** [comment]
We haven't had confirmation that this is still an issue with the latest release of JeroMQ, so closing this issue for now. Feel free to reopen if the issue persists with the latest version.
