### ISSUE TITLE
The change log for 0.3.6 is empty

### ISSUE THREAD

**Issue by garydgregory** [zeromq/jeromq#371]
The change log (changelog.md) for 0.3.6 is empty!

What's new?

**Comment by trevorbernard** [comment]
https://github.com/zeromq/jeromq/compare/v0.3.5...v0.3.6

**Comment by paulvi** [comment]
Missing docs as not as bad no releases at at for `jzmq`
https://github.com/zeromq/jzmq/issues/442

With some releases at least there is hope that some bugs would be fixed

**Comment by daveyarwood** [comment]
I think that going forward, it would be nice if the CHANGELOG had a useful summary of changes for each release. Right now it looks like we're just dumping the commit summary for every commit between the tags, which is not very useful.

**Comment by daveyarwood** [comment]
Another good habit we could get into would be to include an "Unreleased" section at the top of the CHANGELOG, so we can keep track of these changes as we merge them. That way, when it comes time to push a new release, we would only need to change "Unreleased" to the new version number.

**Comment by daveyarwood** [comment]
I'm working on summarizing 0.3.6 -- will make a PR.

**Comment by colini** [comment]
I agree a proper changelog would be nice.  I've used this format on some other projects and it's worked pretty well:  http://keepachangelog.com/en/0.3.0/
