### ISSUE TITLE
ZMQ.Socket.disconnect disappears

### ISSUE THREAD

**Issue by raycursif** [zeromq/jeromq#373]
Hi,

I just find that ZMQ.Socket.disconnect disappears in 0.3.6 in this commit https://github.com/zeromq/jeromq/commit/69df737397b2e735bbeff3a921bc006f15b7dacd

Does that means diconnect is not necessary, just a close can do disconnect too ? 

regards

**Comment by trevorbernard** [comment]
The likely reason for the commit to disappear was because we couldn't get into contact with the commit author when changing the license from LGPLv2 to MPLv2. Feel free to submit a pull request adding disconnect back.

**Comment by bvella** [comment]
I submitted a pull request for this. 

Until this is merged and released in another version, you can use the unbind(addr) method which has the same implementation,

However, i think it makes more sense to paid disconnect with connect and unbind with bind.

**Comment by raycursif** [comment]
@trevorbernard @bvella great just see comments, thanks
