### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by trevorbernard** [zeromq/jeromq#384]
Hi all,

I've been happily the steward for ZeroMQ on the JVM for many years now but unfortunately, I don't have the time or energy to give these projects the attention they need. I'm looking for someone to step up and take over managing the releases to Maven Central. I will help ensure a smooth transition but I will unfortunately take an indefinite leave from jzmq/jeromq. It's been a blast but it's time to move on.

Warmest regards,
Trevor

**Comment by daveyarwood** [comment]
@trevorbernard I might be interested, if the release process isn't too time-consuming. Can you go through what you do when it's time for a new release?

**Comment by trevorbernard** [comment]
It's not a terrible difficult process but it requires a bit of work. There are plenty of document describing how to push artifacts to Maven Central. Typically this is how the release process goes. There is push from the community for a new build. The key is to use the the smallest supported version of Java (which is 7 I believe) then create a deterministic build. You need to the rights to deploy on central and sign the build with your or a trusted set of gpg keys.

**Comment by esialb** [comment]
I'm potentially willing to take this on.  I've got a number of artifacts myself on maven central and I'm quite familiar with the maven release process. @trevorbernard , is there anyone else involved in this project, or just you?  I don't want to be the guy who single-handedly deploys a broken release more often than necessary.

**Comment by trevorbernard** [comment]
@esialb There are many people and organizations involved in JeroMQ but historically, I've been the only person to deploy to central. I wouldn't be too worried about deploying a broken release, just fix it and increment the patch #. I've deployed a broken release or two in my day. Best regards. Trev

**Comment by daveyarwood** [comment]
@esialb I've been exploring the codebase lately and contributing some small fixes. I'm interested in continuing to explore and learn more about how everything works. Ping me if you're ever worried about deploying a broken release -- I can usually spare some time to look through the commits and help figure out what's changed since the last release.

**Comment by kylemallory** [comment]
Its a bit late, but... I'm getting into ZMQ/JMQ as a key technology of a new startup.  I'm hoping to contribute a bit to the code, but I'm not sure I'll have the time for maintenance.

Have you considered moving to Gitlab and using its CI/CD processes to automate releases?  I realize there is the rest of the ZeroMQ project also on GitHub, so I'm not sure this is even a possibility. I know GitHub has its own CI/CD integrations, though they all appear to be addons, and aren't free (If I remember correctly, Gitlab is free if number of pipelines (or time) ran is below a certain number a month.

**Comment by daveyarwood** [comment]
@trevorbernard I'm interested deploying releases to Maven Central and ensuring that that happens regularly.

I was wondering if you could document the release process that you've been following up until this point? I'm not too experienced with deploying to Maven Central, but am happy to learn.

**Comment by daveyarwood** [comment]
BTW @kylemallory, CI for deploying snapshots sounds like a great idea. I'll probably look into that once I have more general info about deploying artifacts.

**Comment by fbacchella** [comment]
To deploy release, I publish to bintray, let them handle the PGP sign and then synchronized to maven central.
My fork of jeromq for deploy of snapshot is here: 
https://github.com/fbacchella/jeromq/tree/publishing
