### ISSUE TITLE
How to prevent sending messages before connections are established?

### ISSUE THREAD

**Issue by mariusspan** [zeromq/jeromq#392]
I'm implementing a REQ/REP client-server on org.zeromq::jeromq:0.3.5 . In my case the REQ side (the client) is short lived serving only the purpose of sending a single request to the server (and reading it's response) after which the process returns.

The behavior that I'm currently experiencing is that the client's request does arrive into the server and consequently the client times-out while waiting for the server's response.

When I alter the client side so that it does the request/response cycle multiple times the server will service  a number of requests. Specifically the server seems to miss the first request. I believe this is determined by the fact the the TCP connection establishing is async and happens after the client gets to the point of sending the first request. 

I've attempted to prevent the client sending the first request before the connection was established using the Socket::setDelayAttachOnConnect(true) - the documentation is not quite straight forward for this method but seem to suggest that is suitable for my case. Unfortunately this did not change the behavior.

The next attempt to fix this was using Socket::monitor(..) API, on the client's connection, blocking until the connection was established. This the equivalent of having the connect block until the TCP connection is established. Based on this approach the unwanted behavior was prevented but this solution is to sophisticated for a simple feature.

Did anyone experience such behaviors? Is there a simpler way of achieving the connection establishing synchronization? Is the Socket::setDelayAttachOnConnect faulty?

**Comment by daveyarwood** [comment]
Have you tried polling? I think that's the approach I would use.

I haven't tried POLLOUT before, but I believe the purpose is to determine whether the socket you want to send to is available to receive messages.

If that doesn't work, you could also send a "ping" message to which the server should respond if it's up, and use the DONTWAIT option so that you don't block if the server isn't up yet. Then, you could repeatedly check POLLIN until you've received the "pong" message from the server, which would tell you that the server is up.

Once you've determined that the server is up via POLLOUT or POLLIN, you could then start sending the important messages.

**Comment by mariusspan** [comment]
Thanks for the suggestion, I'll give it a try and get back on this.

On the ping-pong suggestion: I thought about implementing the ping-pong before actually sending the request message (as you suggest) but discarded it as the ping-pong workaround implies server side handling as well which seams more invasive than the monitoring workaround (although monitoring is more sophisticated, but at least resides only on one side).

What about Socket::setDelayAttachOnConnect? Is this meant to block the I/O until the connection is established?

**Comment by mariusspan** [comment]
I've tried a poller approach which seams to exhibit similar behavior: the client sends the event, although not really connected, and because the server is slow (notice the sleep in the server's thread) the event does not reach the destination:

```java
public static void main(final String[] args) throws Exception {
        final int timeout = (int) TimeUnit.SECONDS.toMillis(5);

        new Thread(new Runnable() {
            @Override public void run() {
                try {
                    Thread.currentThread().sleep(timeout * 2);
                } catch (InterruptedException e) {
                }
                ZContext ctx = new ZContext();
                Socket cnx = ctx.createSocket(ZMQ.REP);
                cnx.bind("tcp://127.0.0.1:4444");
                Poller poller = new Poller(1);
                PollItem item = new PollItem(cnx, Poller.POLLIN);
                int index = poller.register(item);
                poller.poll(timeout);
                if (poller.pollin(index)) {
                    String req = poller.getItem(index).getSocket().recvStr();
                    System.out.println("Server got: " + req);
                    poller.getItem(0).getSocket().send("world");
                }
                System.out.println("Server out");
            }
        }).start();

        ZContext ctx = new ZContext();
        Socket cnx = ctx.createSocket(ZMQ.REQ);
        cnx.setReceiveTimeOut(timeout);
        cnx.connect("tcp://127.0.0.1:4444");

        Poller poller = new Poller(1);
        PollItem item = new PollItem(cnx, Poller.POLLOUT);
        int index = poller.register(item);
        poller.poll(timeout);
        if (poller.pollout(index)) {
            boolean sent = poller.getItem(index).getSocket().send("yellow");
            System.out.println("Client sent: " + sent);
            String recvStr = poller.getItem(0).getSocket().recvStr();
            System.out.println("Client recv: " + recvStr);
        }
        ctx.close();
        System.out.println("Client out");

    }
```

Running this will produce:
```
Client sent: true
Client recv: null
Client out
Server out
```
I'm quite new to jeromq so I might have it wrong. If so could you see anything that I might missed out?

**Comment by daveyarwood** [comment]
What you want to do is loop until pollin/pollout returns true, something like this::

```java
while (true) {
  poller.poll(timeout);
  if (poller.pollout(index)) { break; }
}

// server is definitely available now, can start sending messages
```

It also doesn't look like you are setting up your pollers correctly. The call to `register` should take a _socket_ (not a context) and a polling type (POLLIN/POLLOUT/POLLERR). You may want to have a look at the [mspoller](https://github.com/zeromq/jeromq/blob/master/src/test/java/guide/mspoller.java) example.

**Comment by mariusspan** [comment]
Originally I've put in the while loop but eventually I've removed it mainly because after the first Pooller::pool() call the Poller::pollout() returned true (basically meaning that the client did a single cycle of the loop) which allowed the client to send it's event although it had no established connection to the server. So, it seams to me that after the pollout returns true there is still not guaranty that the client has an established connection which in turn means that sending the event through this socket might not reach it's destination (at least for the case when the client side is short lived returning soon after the send call).

Based on this experiment I believe that monitoring the events for the client's socket remains the single option providing the guaranty. I'm going for this option but if you still see any others I'm more than happy to explore those.

**Comment by mariusspan** [comment]
I've did one more test on the poller approach and added set the delay attach on the client's socket (Socket::setDelayAttachOnConnect()) and this time the client side Poller::pollout() retured false when the client had not established connection, while for the case when the connection was established the pollout returned as expected true. This allows the client to lock into the busy loop until the connection gets established which should be enough to send the event. Based on this I believe the Poller approach will solve my case. Thank you for the suggestion.

**Comment by daveyarwood** [comment]
> Originally I've put in the while loop but eventually I've removed it mainly because after the first Pooller::pool() call the Poller::pollout() returned true (basically meaning that the client did a single cycle of the loop) which allowed the client to send it's event although it had no established connection to the server. So, it seams to me that after the pollout returns true there is still not guaranty that the client has an established connection which in turn means that sending the event through this socket might not reach it's destination (at least for the case when the client side is short lived returning soon after the send call).

I think we may both be misunderstanding what POLLOUT does. I wonder if maybe it just means that the client is free to place a message on the socket, which the server will pick up as soon as it starts? I know that there is a queuing component to ZeroMQ, where if the server (consumer) goes down, some amount of unconsumed messages will queue up until it comes back up and starts consuming them again. So, maybe if POLLOUT returns true, that doesn't necessarily mean that the server is up. Come to think of it, I don't think there is any way that the poller can know if the server is up or not, since that has nothing to do with ZeroMQ.

So, I would recommend trying my other suggestion: sending a non-blocking "ping" message and polling from the client side in an infinite loop until POLLIN is true and you receive a "pong" message from the server.

Monitoring might be a good solution, too, I've just never tried it and don't really know much about it.

**Comment by mariusspan** [comment]
Although ensuring that the message could be processes at the destination would be better, my aim was only to have the client side connected before sending the message. So the poller combine with the attach on connect setting would suffice my case. BTW the server responding with the pong message is not neccesarelly a guaranty that the next message (the business message this time) would get processed as the server might as well die imediatelly after sending the pong response.

**Comment by fredoboulo** [comment]
I'm definitely arriving after the battle, but is it necessary for your use case to have
`cnx.setReceiveTimeOut(timeout);` in the client side? 

If I use a much simpler version of your code, this is working as expected with the latest master:

```
    @Test
    public void testIssue392()
    {
        final int timeout = (int) TimeUnit.SECONDS.toMillis(5);

        new Thread(new Runnable()
        {
            @Override
            public void run()
            {
                zmq.ZMQ.msleep(timeout * 2);
                ZContext ctx = new ZContext();
                try {
                    Socket cnx = ctx.createSocket(ZMQ.REP);
                    cnx.bind("tcp://127.0.0.1:4444");
                    String request = cnx.recvStr();
                    System.out.println("Server got: " + request);
                    boolean sent = cnx.send("world");
                    System.out.println("Server out");
                }
                finally {
                    ctx.close();
                }
            }
        }).start();

        ZContext ctx = new ZContext();
        try {
            Socket cnx = ctx.createSocket(ZMQ.REQ);
            //            cnx.setReceiveTimeOut(timeout);
            cnx.connect("tcp://127.0.0.1:4444");

            boolean sent = cnx.send("yellow");
            System.out.println("Client sent: " + sent);
            String reply = cnx.recvStr();
            System.out.println("Client received: " + reply);
        }
        finally {
            ctx.close();
        }
    }

```

**Comment by mariusspan** [comment]
The receive timeout in the client was meant so that the client side (which is a short lived java process) would not hang in case when the server is not able to respond (due any reason) and react on this situation (not covered in this sample).

This issue is quite old and based on the discussions above I managed to find a solution for my original issue. I believe I forgot to close it.

@fredoboulo if you feel there is anything that needs further clarification please let me know, otherwise, at least from my point of view, this should be closed.
