### ISSUE TITLE
PUB - SUB not working

### ISSUE THREAD

**Issue by dream-x** [zeromq/jeromq#397]
Hello, 
jeromq 0.3.6
server:
```java
        try(ZMQ.Context ctx = ZMQ.context(1);
            ZMQ.Socket socket = ctx.socket(ZMQ.SUB)) {
                socket.bind("tcp://localhost:5556");
                while (true) {
                    System.out.println(socket.recvStr());
                }
            }
```
client:
```java
        try(ZMQ.Context context = ZMQ.context(1);
            ZMQ.Socket socket = context.socket(ZMQ.PUB)) {
                socket.connect("tcp://localhost:5556");
                System.out.println(socket.send("!!!!!!!asdadadasdasdad!!!!!!!"));
                socket.close();
            }
```

If swap PULL - PUSH this work great.

**Comment by daveyarwood** [comment]
I would recommend reading about PUB/SUB in the ZGuide: http://zguide.zeromq.org/page:all#Pros-and-Cons-of-Pub-Sub

> Pub-sub is like a radio broadcast; you miss everything before you join, and then how much information you get depends on the quality of your reception. 

In your example, you are setting up a PUB socket and immediately publishing one message and then closing it. On the other side, you are setting up a SUB socket and starting to receive messages. I'm guessing what is happening is the SUB socket is taking longer than you expect to subscribe, and it misses the publisher's one message.

Another potential issue is that you have the subscriber binding (server) and the publisher connecting (client). Typically it is the other way around -- the publisher binds and the subscriber connects. I haven't seen any ZGuide examples that do it the way you have it, and I suspect that it doesn't work that way. Maybe PUSH/PULL is more appropriate for your use case?

**Comment by daveyarwood** [comment]
Actually...

> Even if you synchronize a SUB and PUB socket, you may still lose messages. It's due to the fact that internal queues aren't created until a connection is actually created. **If you can switch the bind/connect direction so the SUB socket binds, and the PUB socket connects, you may find it works more as you'd expect.**

I stand corrected -- it is OK (maybe even better, in some cases) to bind the SUB and connect the PUB.

So, my theory is that the PUB socket started publishing messages before the SUB finished connecting/subscribing.

This might be helpful: http://zguide.zeromq.org/page:all#Missing-Message-Problem-Solver

**Comment by mariusspan** [comment]
Besides the synchronization issue between the peers I believe the subscription on the sub side is as well missing ( e.g. socket.subscribe("!!!!!!!".getBytes()); )

**Comment by dream-x** [comment]
@mariusspan @daveyarwood edited on your recommendations and docs reading, but not working whatever:

subscriber first run
```java
      try (ZMQ.Context ctx = ZMQ.context(1);
             ZMQ.Socket socket = ctx.socket(ZMQ.SUB)) {
            socket.connect("tcp://*:5556");
            socket.subscribe("A".getBytes());
            while (true) {
                System.out.print(socket.recvStr());
                System.out.print(socket.recvStr());
            }
        }
```

publisher
```java
      try (ZMQ.Context context = ZMQ.context(1);
             ZMQ.Socket socket = context.socket(ZMQ.PUB)) {
            socket.bind("tcp://*:5556");
            socket.sendMore("A".getBytes());
            socket.send("qweqeqeqe".getBytes());
            Thread.sleep(2000);
            socket.close();
        }
```

**Comment by mariusspan** [comment]
It seams to me you may still have the race condition between the peers: by the time the subscriber subscribes the publisher already sent its message. To confirm this you might add a sleep in the pub after binding.

**Comment by dream-x** [comment]
@mariusspan thanks for answer me, it works.

**Comment by mholzel** [comment]
I believe the underlying problem may have simply been that originally, he bound on the SUB socket, which AFAIK, is not implemented in JeroMQ, although it is definitely supported in the ZeroMQ spec.
