### ISSUE TITLE
client can not pull message which is pushed from server randomly

### ISSUE THREAD

**Issue by rogue2yjg** [zeromq/jeromq#398]
We have a router which is using jeromq 0.3.5. It hasn't any business logic and only take charge of message routing(receive a message from upstream system(uss) and send it to downstream system(dss)). All our other business systems(clients) connect to the router(server) by using PUSH-PULL mode.
The problem happens randomly as follows:
1. router can't receive message from uss
2. dss can't receive message from router
All the problems can be fixed by restarting uss、dss and router.But we don't figure it out so far.

p.s.
1. We haven't used heartbeat in uss、dss and router
2. Our OS is CentOS release 6.5
3. SO_KEEPALIVE OPTION
      net.ipv4.tcp_keepalive_time = 7200
      net.ipv4.tcp_keepalive_probes = 9
      net.ipv4.tcp_keepalive_intvl = 75

**Comment by rogue2yjg** [comment]
2. dss can't receive message from router
--->we have made sure that router received message from uss and sent it to dss without any error.

**Comment by daveyarwood** [comment]
> All our other business systems(clients) connect to the router(server) by using PUSH-PULL mode.

Can you elaborate more on this setup? Is it the case that clients are sending requests and receiving the results? If that's the case, I think you may want REQ/REP instead of PUSH/PULL.

It would be helpful to see some code, as well.

**Comment by rogue2yjg** [comment]
@daveyarwood 
1、Our data flow direction is unidirectional, we don't need response. In the future, we may use distributed deployment.So in this case, REQ/REP may not satisfy the needs.
2、We have 4 different clients, including eplus-proxy-->eplus-monitor-->eplus-monitor-center, the arrow represents data flow direction, and msg will first arrive our router before arriving the destination.
3、I can provide 3 code pieces representing sending msg from dss、routing msg by router、receiving msg by dss:

(1)sending msg from dss
protected void distribute(byte[] data) {
    socketWriteLock.lock();
    try {
        socket.send(data, 0);	
    } finally {
        socketWriteLock.unlock();
    }
}

(2)routing msg by router
public class ZMQForwarder implements Runnable {
	private final Poller poller;
	private final Socket inSocket;
	private final Socket outSocket;

	public ZMQForwarder(Context context, Socket inSocket, Socket outSocket) {
		this.inSocket = inSocket;
		this.outSocket = outSocket;
		this.poller = new Poller(1);
		this.poller.register(inSocket, Poller.POLLIN);
	}

	@Override
	public void run() {
		byte[] msg = null;
		boolean more = true;
		while (!Thread.currentThread().isInterrupted()) {
			try {
				// wait while there are requests to process
				if (poller.poll(250000) < 1) {
					continue;
				}
				msg = inSocket.recv(0);
				more = inSocket.hasReceiveMore();
				if (msg != null)
					outSocket.send(msg, more ? ZMQ.SNDMORE : 0);

			} catch (ZMQException e) {
				if (ZMQ.Error.ETERM.getCode() == e.getErrorCode()) {
					break;
				}
				throw e;
			}
		}
	}
}

(3)receiving msg by dss
public void run() {
	byte[] msg = null;
	while (!Thread.currentThread().isInterrupted()) {
		try {
			msg = socket.recv(0);
			String msgStr = new String(msg, ZMQ.CHARSET);
			worker.handleUp(msgStr);
		} catch (Exception e) {
			logger.error(CommonUtils.printExceptionErr(e));
		}
	}
}

**Comment by rogue2yjg** [comment]
@daveyarwood
Is there any problem with my code?

**Comment by daveyarwood** [comment]
```java
// wait while there are requests to process
if (poller.poll(250000) < 1) {
  continue;
}
msg = inSocket.recv(0);
```

This part looks potentially suspect. Usually the pattern looks like this:

```java
poller.poll(250000);

if (poller.pollin(0)) {
  msg = inSocket.recv(0);
}
```

`Poller.poll`, according to its doc string, returns the number of "number of events," but I'm not 100% sure that that corresponds to the number of sockets on which messages are ready to receive. In all of the examples I've seen, the pattern is to call `poller.poll()` (optionally with a timeout), and then check `poller.pollin(...)` with the index of the socket you want to check to see if there is a message.

Another thing worth noting is that I don't understand the need for `socketWriteLock` -- it's possible that that's causing some unintended behavior.

**Comment by rogue2yjg** [comment]
@daveyarwood 

actually, the full code segment of our router id below:

```java
public class ZMQForwarder implements Runnable {
	private final Poller poller;
	private final Socket inSocket;
	private final Socket outSocket;

	public ZMQForwarder(Context context, Socket inSocket, Socket outSocket) {
		this.inSocket = inSocket;
		this.outSocket = outSocket;
		this.poller = new Poller(1);
		this.poller.register(inSocket, Poller.POLLIN);
	}

	@Override
	public void run() {
		byte[] msg = null;
		boolean more = true;
		while (!Thread.currentThread().isInterrupted()) {
			try {
				// wait while there are requests to process
				if (poller.poll(250000) < 1) {
					continue;
				}
				msg = inSocket.recv(0);
				more = inSocket.hasReceiveMore();
				if (msg != null) {
                                    log('receive msg'); // log 1
                                    outSocket.send(msg, more ? ZMQ.SNDMORE : 0);
                                    log('send msg'); // log 2
                                }
			} catch (ZMQException e) {
				if (ZMQ.Error.ETERM.getCode() == e.getErrorCode()) {
					break;
				}
				throw e;
			}
		}
	}
}
```

In my code, we both record log before and after sending msg to down link client(outSocket.send).
But frequently we  encounter a problem that log 1 is printed and log 2 isn't printed. 
I suspect that outSocket is disconnected, but I have no evidence to prove my deduce. And there is no reason that socket should be disconnected. Sometimes, log 1 and log 2 are both not printed, according with your deduce.

**Comment by daveyarwood** [comment]
Where is the code that initializes and connects the sockets?

**Comment by rogue2yjg** [comment]
@daveyarwood 

The code of socket initialized in our router is below:
```java
import org.zeromq.ZContext;
import org.zeromq.ZMQ.Socket;

public class ZmqUtils {

	private static ZContext zmqManager = new ZContext();
	private static List<Thread> proxyThreads = new ArrayList<Thread>();

	public static void forwarderRoute(Socket src, Socket dest, String name) {
		Thread forwarder = new Thread(new ZMQForwarder(zmqManager.getContext(), src, dest), name);
		proxyThreads.add(forwarder);
		forwarder.start();
	}

	public static Socket createSocket(int type, String addr) {
		Socket socket = zmqManager.createSocket(type);
		socket.bind(addr);
		return socket;
	}
}
```

The code of socket initialized in our clients is below:
```java
import org.zeromq.ZContext;
import org.zeromq.ZMQ.Socket;

public class ZmqUtils {
	
	private static ZContext zmqManager = new ZContext();
	
	public static Socket createSocket(int type, String addr) {
		Socket socket = zmqManager.createSocket(type);
		socket.connect(addr);
		return socket;
	}
}
```

I suspect that socket is disconnected but is not closed, so socket reconnection is failing.

**Comment by daveyarwood** [comment]
> I suspect that socket is disconnected but is not closed, so socket reconnection is failing.

Can you explain more about this? It sounds like the problem might have to do with the client-side sockets, but I haven't seen any code where the sockets are actually connecting and sending messages.

**Comment by rogue2yjg** [comment]
@daveyarwood 
I can't explain it clearly, because there is no reason that the socket should be disconnected. But the appearance happened frequently when there is no msg sending in the link for a long time.

The code of sockets connecting and sending messages have been provided in my previous reply. Please check it clearly.

For example, the code of socket initialized in our router is below:
```java
import org.zeromq.ZContext;
import org.zeromq.ZMQ.Socket;

public class ZmqUtils {

	private static ZContext zmqManager = new ZContext();
	private static List<Thread> proxyThreads = new ArrayList<Thread>();

	public static void forwarderRoute(Socket src, Socket dest, String name) {
		Thread forwarder = new Thread(new ZMQForwarder(zmqManager.getContext(), src, dest), name);
		proxyThreads.add(forwarder);
		forwarder.start();
	}

	public static Socket createSocket(int type, String addr) {
		Socket socket = zmqManager.createSocket(type);
		socket.bind(addr);
		return socket;
	}
}
```

The code of socket initialized in our clients is below:
```java
import org.zeromq.ZContext;
import org.zeromq.ZMQ.Socket;

public class ZmqUtils {
	
	private static ZContext zmqManager = new ZContext();
	
	public static Socket createSocket(int type, String addr) {
		Socket socket = zmqManager.createSocket(type);
		socket.connect(addr);
		return socket;
	}
}
```

**Comment by rogue2yjg** [comment]
@daveyarwood 
Is there any problem in my code of my last reply?

**Comment by daveyarwood** [comment]
The code for `createSocket` looks fine AFAICT. What I was wondering about was the code where that method is actually used to create the sockets.

**Comment by rogue2yjg** [comment]
@daveyarwood 
1、up stream client(send msg to router)
```java
public class Api2MonitorStatusChangeUpHandler extends ServiceHandler {
	@Override
	public void push(Object data) {
		List<MonitorDataNew> obj = (List<MonitorDataNew>) data;
		String jsonStr = JSONUtil.getJsonString(obj);
		super.distribute(jsonStr);
	}
}
```

```java
import java.util.concurrent.locks.ReentrantLock;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.zeromq.ZMQ;
import org.zeromq.ZMQ.Socket;

import com.lneric.eplus.common.msg.service.config.ServiceConfig;
import com.lneric.eplus.common.util.ServiceUtils;
import com.lneric.eplus.common.util.ZmqUtils;


public abstract class ServiceHandler implements Runnable {
	protected Logger logger = LoggerFactory.getLogger(getClass());
	
	protected Socket socket;
	protected ServiceConfig serviceConfig;

	protected final ReentrantLock socketWriteLock = new ReentrantLock();

	protected void createSocket() {
		int type = ServiceUtils.getConnectionType(serviceConfig.getType()); // get socket type, e.g. ZMQ.PULL, ZMQ.PUSH
		this.socket = ZmqUtils.createSocket(type, serviceConfig.getAddr())); // get socket address
	}

	@Override
	public void run() {
	}
	
	protected void distribute(String data) {
		this.distribute(data.getBytes(ZMQ.CHARSET));
	}
	
	protected void distribute(byte[] data) {
		socketWriteLock.lock();
		try {
			socket.send(data, 0);	
		} finally {
			socketWriteLock.unlock();
		}
	}
	
	public Socket getSocket() {
		return socket;
	}

	public void setServiceConfig(ServiceConfig serviceConfig) {
		this.serviceConfig = serviceConfig;
	}

	public ServiceConfig getServiceConfig() {
		return serviceConfig;
	}
}
```

2、router receives msg from up stream client and sends it to down stream client
```java
import org.slf4j.Logger;
import org.zeromq.ZMQ.Socket;

import com.lneric.eplus.common.util.LoggerUtils;
import com.lneric.eplus.common.util.ServiceUtils;
import com.lneric.eplus.constants.msg.ProxyTarget;
import com.lneric.eplus.router.base.proxy.model.Router;
import com.lneric.eplus.router.base.proxy.model.RouterConfig;
import com.lneric.eplus.router.base.util.ZmqUtils;

public abstract class RouterHandler {

	private static final Logger logger = LoggerUtils
			.getLogger(RouterHandler.class);

	protected RouterConfig config;
	protected Socket srcSocket;
	protected Socket destSocket;

	protected void route(String name) {
		if (ServiceUtils.isPull(config.getSrcType())
				&& ServiceUtils.isPush(config.getDestType())) {
			ZmqUtils.forwarderRoute(srcSocket, destSocket, name);
		}
	}

	protected void start() {
		this.srcSocket = new Router(config, ProxyTarget.SRC).start();
		this.destSocket = new Router(config, ProxyTarget.DEST).start();
		this.route(ServiceUtils.getRouterHandlerDesc(config.getId(),
				config.getName()));
	}

	// getter and setter method
}
```

```java
import org.zeromq.ZMQ.Socket;

import com.lneric.eplus.common.util.ServiceUtils;
import com.lneric.eplus.constants.msg.ActionType;
import com.lneric.eplus.constants.msg.ProxyTarget;
import com.lneric.eplus.router.base.util.ZmqUtils;

public class Router {

	private String id;
	private String name;
	private String addr;
	private String type; // push、pull

	public Router(RouterConfig config, ProxyTarget target) {
		this.id = config.getId();
		switch (target) {
			case SRC:
				this.name = config.getSrcName();
				this.addr = config.getSrcAddr();
				this.type = config.getSrcType();
				break;
			case DEST:
				this.name = config.getDestName();
				this.addr = config.getDestAddr();
				this.type = config.getDestType();
				break;
		}
	}
	
	public Socket start() {
		return ZmqUtils.createSocket(ActionType.BIND, ServiceUtils.getConnectionType(type), addr);
	}
	
	// getter and setter method
}
```

3、down stream client(receives msg from router)
```java
import org.zeromq.ZMQ;

import com.lneric.eplus.common.msg.service.handle.ServiceHandler;
import com.lneric.eplus.common.msg.service.handle.Worker;
import com.lneric.eplus.common.msg.service.log.LogTemplate;
import com.lneric.eplus.common.util.CommonUtils;
import com.lneric.eplus.monitor.msg.service.worker.ManualStatusChangeWorker;

public class Api2MonitorStatusChangeUpHandler extends ServiceHandler {
	
	private Worker worker = ManualStatusChangeWorker.getInstance();
	
	@Override
	public void run() {
		byte[] msg = null;
		while (!Thread.currentThread().isInterrupted()) {
			try {
				msg = socket.recv(0);
				String msgStr = new String(msg, ZMQ.CHARSET);
				logger.debug(LogTemplate.STATUS_CHANGE_UP_PULL_FROM_API, msgStr);
				worker.handleUp(msgStr);
			} catch (Exception e) {
				logger.error(CommonUtils.printExceptionErr(e));
			}
		}
	}
}
```

**Comment by daveyarwood** [comment]
I wish I could be more helpful, but it's difficult for me to determine the problem because there is just too much code here -- there is too much potential for the problem to be something not related to JeroMQ.

What I would recommend is simplifying your code to something that resembles one of the [ZGuide examples](https://github.com/zeromq/jeromq/tree/master/src/test/java/guide) (your architecture sounds to me like the [parallel pipeline](http://zguide.zeromq.org/page:all#Divide-and-Conquer) pattern) and see if you can pinpoint a JeroMQ-related issue.

**Comment by rogue2yjg** [comment]
@daveyarwood 

Firstly, thanks you for discussing the problem with me and I will take your advice to simplify my code as ZGuide examples. But I have a question to consult with you in the end:
If there is no msg sending in the JeroMQ socket for a long time(e.g. a week), will the socket connection be lost  but the socket is still open?

**Comment by daveyarwood** [comment]
I have heard that that can be an issue. A good way to get client-side reliability is to retry failed requests, destroying and re-creating the socket each time so that you have a fresh connection.

**Comment by rogue2yjg** [comment]
@daveyarwood 
If that is an issue, when will it be fixed? In addition, if I send heartbeat msg every 5 minutes between our router and clients, does it work?,

**Comment by daveyarwood** [comment]
> Do you mean that the auto reconnection in client doesn't work in jeromq?

Is that a feature of ZeroMQ?

> In addition, if I send heartbeat msg every 5 minutes between our router and clients, does it work?,

I think that should help keep the connection open.

**Comment by rogue2yjg** [comment]
@daveyarwood 
OK，thanks~

**Comment by andreaslarssen** [comment]
Could this be connected to #364?

**Comment by daveyarwood** [comment]
As I posted in #364:

> As several people have mentioned, heartbeating and/or restarting nodes is an effective way of keeping the connection open. My impression is that this is an inherent issue with ZeroMQ in general, possibly even part of the design (i.e. maybe ZeroMQ makes no attempt to keep the connection open, and it's on us to design our architecture such that the connections stay in use / open).
