### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by hintjens** [zeromq/jeromq#4]
If you'd like to help click that lovely green "Merge Pull Request" button, and get eternal karma, add a comment confirming that you've read and understand the C4 process at http://rfc.zeromq.org/spec:16.

**Comment by daveyarwood** [comment]
I'll be happy to help, as well. I've read and understand the C4 process. ZMQ and jeromq are great!

**Comment by miniway** [comment]
@daveyarwood welcome abroad!

**Comment by daveyarwood** [comment]
Asking for maintainers in an issue seems like a misuse of issues. I think it might be time to close this issue.

At this point, the README makes it clear how to contribute, and points to a CONTRIBUTING.md added earlier this year with more detailed information, including a note about the C4 process. CONTRIBUTING.md does request that new contributors come to this issue and post that they have read and understand the C4 process, but the majority of contributors have not done this, so there is a question of process there. I feel like it ought to be sufficient for us to state that we follow the C4 process, and any contributors must adhere to it, and leave it at that.

I'm taking the liberty of closing this issue, but I won't be upset if someone feels we should re-open it.
