### ISSUE TITLE
Requesting a 0.4.0 release

### ISSUE THREAD

**Issue by daveyarwood** [zeromq/jeromq#406]
There have been [some nice changes](https://github.com/zeromq/jeromq/compare/v0.3.6...master) since 0.3.6 that I'd like to make use of.

Because #387 and #400 include breaking changes, I propose that this release be 0.4.0.

I'll be happy to update the CHANGELOG with a summary of the changes from 0.3.6 => 0.4.0, similar to what I did in #405. I'm not really interested in doing the release chore though. @esialb, would you be willing to do the release?

**Comment by trevorbernard** [comment]
@daveyarwood If you handle the CHANGELOG I'll push to central. We currently don't have anyone other than myself that has the permissions to push to central.

**Comment by daveyarwood** [comment]
Sounds good! :+1:

**Comment by daveyarwood** [comment]
@trevorbernard I have a PR ready that adds a changelog for an 0.4.0 release.

**Comment by jamessugrue** [comment]
Is there a planned release date for this?

**Comment by trevorbernard** [comment]
No planned date but it will happen relatively soon. I'll be issuing the release in the coming days. It would have happened sooner but I need to recreate my deployment setup.

**Comment by jamessugrue** [comment]
Thanks - can build locally anyway, just curious. Would be willing to help out with work on the library too.

**Comment by trevorbernard** [comment]
I just pushed `v0.4.0` to central. It'll be a few hours before it's synced up and can be seen on maven.org.

**Comment by daveyarwood** [comment]
Thanks @trevorbernard ! :beers:
