### ISSUE TITLE
Can you see that Publisher and Subscriber are connected?

### ISSUE THREAD

**Issue by audtjddld** [zeromq/jeromq#422]
Hi,
I use ZeroMQ to communicate messages between servers (Pub / Sub). At this time, get the server IP and port to send through ZooKeeper about the request destination.
The problem is that when the IP and Port are changed, a new Publisher is created (Socket create)
  I wonder if there is a way to know when the connection between subscriber is attached.

Please understand that English is poor and you have written it in translator.

**Comment by trevorbernard** [comment]
The idiomatic way to do it at the application level (e.g. some sort of heartbeat mechanism with timeouts). There is no reliable way to do this at the ZeroMQ socket level and is better handled by the application.

**Comment by audtjddld** [comment]
After the new publisher socket is created, the first message is often lost during the pending period. Is there a way to check if a message is lost or not?

Since I use the zookeeper to get the server information for the publisher and create a new publisher socket, there is a high probability that messages will be lost during that pending period. I do not think we should wait.

I thought in a customary way to find a way to solve this situation.
I do not understand ZeroMQ ideology properly or I do not know how to apply it.

Thank you for your reply. @trevorbernard

**Comment by audtjddld** [comment]
I heard your story and confirmed the ZMQ again.

At first, I did not understand your answer.

But when I saw the answer and checked the manual again, I could see what I was talking about.

Thank you for kindly responding to the question, not the issue.
@trevorbernard
