### ISSUE TITLE
Port Scanning on jeromq based application (OutOfMemoryError)

### ISSUE THREAD

**Issue by kmualem** [zeromq/jeromq#440]
Hi Guys,

We are facing a critical issue while a port scanning application is running against our jeromq based application, version 0.3.4. 

It seems like an issue in zmq.V1Decoder, it collects the traffic of the port scanning application, and then failed while initializing the Msg object due to the message size.

**Please see below the exception stack trace**:
java.lang.OutOfMemoryError: Java heap space
Exception in thread "iothread-2" java.lang.OutOfMemoryError: Java heap space
at zmq.Msg.<init>(Msg.java:64)
at zmq.V1Decoder.eight_byte_size_ready(V1Decoder.java:104)
at zmq.V1Decoder.next(V1Decoder.java:45)
at zmq.DecoderBase.process_buffer(DecoderBase.java:124)
at zmq.StreamEngine.in_event(StreamEngine.java:307)
at zmq.StreamEngine.plug(StreamEngine.java:240)
at zmq.SessionBase.process_attach(SessionBase.java:355)
at zmq.ZObject.process_command(ZObject.java:80)
at zmq.IOThread.in_event(IOThread.java:90)

After investigation of the heapdump, we noticed that in eight_byte_size_ready() the msg_size is a negative big number.
```
byte[] tmpbuf = new byte[] { -5, 24, -1, -5, 31, -1, -5, 32 };
final long msg_size = -353251116709840096;
```

The comparison in the V1Decoder eight_byte_size_ready function doesn't help as it looks like it's not expect to have a negative number.

```
if (maxmsgsize >= 0)
..
 if (msg_size > Integer.MAX_VALUE) {
..
```

We thought that the PLAIN authentication feature in 0.4.0 may help us to solve this problem, but we don't find any documentation or examples of how to use it in jeromq... 

Can you please help ?  Any comment is really appreciated!

Thanks a lot!
Kobi.

**Comment by kmualem** [comment]
Can someone please help me ?

**Comment by kmualem** [comment]
I wrote this issue before 24 days ago and didn't get any response yet :(
Can you please try to help me ? Can you please provide me javadoc / examples for the PLAIN authentication ?

**Comment by colini** [comment]
Looking at the latest on jeromq master branch, there is now a check in `zmq.io.coder.1V1Decoder.eightByteSizeReady()` to ensure the payload length read is >= 0:

```java
final long payloadLength = Wire.getUInt64(tmpbuf, 0)

if (payloadLength <= 0) {
    errno(ZError.EPROTO);
    return Step.Result.ERROR;
}
```

Based on your description this would likely solve the problem.  Can you run your test against jeromq version 0.4.2 (recently released to maven)?

**Comment by kmualem** [comment]
@colini  Thanks for your comment! I'll try to check it and will update... 

BTW Do you have an example for the PLAIN auth ?

**Comment by fredoboulo** [comment]
Hello,
you can have a look here for PLAIN auth: https://github.com/zeromq/jeromq/blob/master/src/test/java/zmq/io/mechanism/SecurityPlainTest.java
and here: https://rfc.zeromq.org/spec:24/ZMTP-PLAIN

**Comment by kmualem** [comment]
Thank you guys. Ill try it...

**Comment by daveyarwood** [comment]
@kmualem Any updates? Is this issue resolved, or are you still having trouble?

**Comment by kmualem** [comment]
Yes, It looks like the problem that I had is solved.

**Comment by trevorbernard** [comment]
Awesome
