### ISSUE TITLE
requesting 0.4.1 release

### ISSUE THREAD

**Issue by tjamesturner** [zeromq/jeromq#441]
it's been a few months since the last version bump. any chance we could get a release? i can update the changelog if @trevorbernard can do the push to nexus.

there have been some breaking changes in lesser-used features and internal repackaging, but i'm not sure if that justifies a 0.5.0 release yet.  for the most part it looks like we've had mostly bug fixes and cleanup since 0.4.0.

**Comment by scoheb** [comment]
I would like to second this request please!
Thanks

**Comment by trevorbernard** [comment]
I just released to 0.4.1 to central. It should by synced in a few hours.
