### ISSUE TITLE
ZMQ.Socket does not have disconnect() function

### ISSUE THREAD

**Issue by SergueiEK** [zeromq/jeromq#445]
Hello
Is there a particular reason why ZMQ.Socket class has no disconnect() function? 

Cheers,

**Comment by daveyarwood** [comment]
I believe it does: https://github.com/zeromq/jeromq/blob/eac7296f2fab399f0d84cf649b4a8aa3fbb7f846/src/main/java/zmq/ZMQ.java#L392

**Comment by SergueiEK** [comment]
Hi

You are right, I have to update to the newest version as I’m still using the version 0.3.6 where this function was not present.

Cheers,
Serguei
