### ISSUE TITLE
Divide by zero exception.

### ISSUE THREAD

**Issue by madrzak** [zeromq/jeromq#447]
Divide by zero occurs very occasionally on the subscriber in the PUB SUB pattern. Seems to occur more frequently when internet connection is weak. 

Code (crashes on the second line)
`String t = subscriber.recvStr();
  String msg = subscriber.recvStr();`

Exception:
java.lang.ArithmeticException: divide by zero
	at zmq.FQ.recvPipe(FQ.java:88)
	at zmq.FQ.recv(FQ.java:67)
	at zmq.XSub.xrecv(XSub.java:165)
	at zmq.SocketBase.recv(SocketBase.java:703)
	at org.zeromq.ZMQ$Socket.recv(ZMQ.java:1377)
	at org.zeromq.ZMQ$Socket.recvStr(ZMQ.java:1448)
	at org.zeromq.ZMQ$Socket.recvStr(ZMQ.java:1438)

**Comment by colini** [comment]
Which version of jeromq?

**Comment by madrzak** [comment]
'org.zeromq:jeromq:0.4.0'

**Comment by daveyarwood** [comment]
This line looks to be the culprit: https://github.com/zeromq/jeromq/blob/v0.4.0/src/main/java/zmq/FQ.java#L88

**Comment by colini** [comment]
Looking at `recvPipe()` I don't see how active could be 0 at line 88.  @madrzak are you sure your socket is only accessed by the thread that created it?  0MQ sockets are not thread safe.

**Comment by fredoboulo** [comment]
Code is quite the same in libzmq: https://github.com/zeromq/libzmq/blob/master/src/fq.cpp#L110
Worth to know is that a fix was made in LB to avoid a divide by zero Exception: https://github.com/zeromq/libzmq/blob/master/src/lb.cpp#L141, and that this fix already exists in Jeromq: https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/socket/LB.java#L117

A fix can also be made for that to avoid the exception, but if the socket is accessed from multiple threads, you will get unpredictable behaviour (with no crash). Could you provide a minimal test case that pinpoints the problem?

**Comment by daveyarwood** [comment]
> A fix can also be made for that to avoid the exception, but if the socket is accessed from multiple threads, you will get unpredictable behaviour (with no crash).

In that case, it seems like we should be catching the divide by zero exception and wrapping it with a more specific ZMQ exception.

**Comment by fredoboulo** [comment]
@madrzak May you provide us compilable code demonstrating the exception?

**Comment by madrzak** [comment]
@fredoboulo Unfortunately I am unable to give you code that demonstrates the exception every time. It was a very rare exception. And it has not happened in a while now. We probably should close this issue for now. Here's part of my implementation anyhow:


`private void startSocket() {
        context = ZMQ.context(1);
        thread = newZmqThread();

        thread.start();
    }

    private Thread newZmqThread() {
        return new Thread(() -> {
            //  Socket to talk to server
            System.out.println("New ZMQ Thread on: " + tenantZmqHost);
            subscriber = context.socket(ZMQ.SUB);

            subscriber.connect(tenantZmqHost);
            subscriber.subscribe(TOPIC_ACK.getBytes());
            subscriber.subscribe(Environment.TOPIC_REVISION.getBytes());
            subscriber.subscribe(Environment.TOPIC_PATROL.getBytes());
            subscriber.subscribe(Environment.TOPIC_ALL_PERMISSIBLE_EVENTS.getBytes());

            while (!Thread.currentThread().interrupted()) {
                try {
                    String t = subscriber.recvStr();
                    String msg = subscriber.recvStr();

                    if (t.substring(0, 1).equals(Environment.TOPIC_PATROL)) {
                        taskProcessor.processMessage(msg);
                    } else if (t.substring(0, 1).equals(Environment.TOPIC_REVISION)) {
                        revisionProcessor.processMessage(msg);
                    } else if (t.substring(0, 1).equals(Environment.TOPIC_ALL_PERMISSIBLE_EVENTS)) {
                        eventProcessor.processMessage(msg);
                    } else if (t.equals(Environment.TOPIC_ACK)) {
                        ackProcessor.processMessage(msg);
                    } else {
                        Log.i(TAG, "Other Msg received: " + t + " - " + msg);
                    }

                } catch (ZMQException e) {
                    Log.e(TAG, "killing zmq " + e.toString());
                    if (e.getErrorCode() == ZMQ.Error.ETERM.getCode()) {
                        break;
                    }
                }
            }
            subscriber.close();
        });
    }

    private void killZmqSocket() {
        new Thread(() -> {
            System.out.println("W: interrupt received, killing socket...");
            context.term();
            subscriber.close();
            try {
                thread.interrupt();
                thread.join();
            } catch (InterruptedException e) {

            }
        }).start();
    }

    private void restartZmqSocket() {
        new Thread(() -> {
            System.out.println("W: interrupt received, restarting socket...");
            context.term();
            subscriber.close();
            try {
                thread.interrupt();
                thread.join();
                tenantZmqHost = prefs.getZmqHost();
                startSocket();
            } catch (InterruptedException e) {

            }
        }).start();
    }
`

**Comment by fredoboulo** [comment]
Dzieki @madrzak :) I did not expect a systematic failing test anyway ... For the sake of completion, I would recommend to close the sockets and terminate the context as well in the thread receiving the messages

@daveyarwood Maybe an assert (active >0); would be enough for the time being ?

**Comment by daveyarwood** [comment]
That sounds reasonable to me. It's at least an improvement over the "divide by zero" exception.
