### ISSUE TITLE
ZMQ Sockets Don't Stay Open 

### ISSUE THREAD

**Issue by GitPlz** [zeromq/jeromq#449]
Updating my dependency from 0.4.0 to 0.4.1 or 0.4.2 introduces a bug in Windows, but not Mac where sockets get closed prematurely. 

Here's my relevant server code. The only change that has been made is updating org.zeromq:jeromq dependency from 0.4.0 to 0.4.2

public class JMQServer implements Runnable
{
    @Override
    public void run()
    {
        Context context = ZMQ.context(1);
        Socket receiver = context.socket(ZMQ.PULL);
        receiver.setReceiveTimeOut(20);
        receiver.bind(this.pubUrl);
        receiver.monitor("inproc://receiver.events", ZMQ.EVENT_ALL);

        // monitor events
        EventMonitor monitor = new EventMonitor(context, "Receiver", "inproc://receiver.events");
        Thread monitorThread = new Thread(monitor);
        monitorThread.setDaemon(true);
        monitorThread.start();
        
        Socket sender = context.socket(ZMQ.PUB);
        sender.bind(subUrl);
        sender.monitor("inproc://sender.events", ZMQ.EVENT_ALL);

        monitor = new EventMonitor(context, "Sender", "inproc://sender.events");
        monitorThread = new Thread(monitor);
        monitorThread.setDaemon(true);
        monitorThread.start();
        
		while ( !Thread.currentThread().isInterrupted())
		{
			String topic = receiver.recvStr();
			byte[] data = null;
			if ( topic != null && receiver.hasReceiveMore() )
			{
				data = receiver.recv();
			}
			
			if ( topic != null && data != null )
			{
				boolean rv1 = sender.sendMore(topic);
				boolean rv2 = sender.send(data, ZMQ.NOBLOCK);
			}
		}
	}

    public class EventMonitor implements Runnable
    {
        
        private final Context context;
        private final String addr;
        private final String name;
        
        public EventMonitor(Context context, String name, String addr)
        {
            this.context = context;
            this.addr = addr;
            this.name = name;
        }

        @Override
        public void run()
        {
            Socket monitor = context.socket(ZMQ.PAIR);
            monitor.connect(addr);

            while (true)
            {
                Event event = Event.recv(monitor);

               // when a client connects this log line executes every ~ 10ms when using 0.4.1 on Windows
              // when a client connects this log line executes only once when using 0.4.0
                logger.info("Received socket monitoring event on monitor {} with data: {} {} {}", 
                            this.name, 
                            event.getAddress(), 
                            event.getEvent(), 
                            event.getValue());
            }
        }

    }
}

This is what my logger output looks like when a client connects:

10:24:02.670 [Thread-1] INFO  JMQServer - Received socket monitoring event on monitor Sender with data: tcp://0.0.0.0:9002 32 null
10:24:02.671 [Thread-1] INFO  JMQServer - Received socket monitoring event on monitor Sender with data: tcp://0.0.0.0:9002 512 null
10:24:02.689 [Thread-0] INFO  JMQServer - Received socket monitoring event on monitor Receiver with data: tcp://0.0.0.0:9001 32 null
10:24:02.689 [Thread-0] INFO  JMQServer - Received socket monitoring event on monitor Receiver with data: tcp://0.0.0.0:9001 512 null
10:24:02.699 [Thread-1] INFO  JMQServer - Received socket monitoring event on monitor Sender with data: tcp://0.0.0.0:9002 32 null
10:24:02.699 [Thread-1] INFO  JMQServer - Received socket monitoring event on monitor Sender with data: tcp://0.0.0.0:9002 512 null
10:24:02.705 [Thread-0] INFO  JMQServer - Received socket monitoring event on monitor Receiver with data: tcp://0.0.0.0:9001 32 null
10:24:02.706 [Thread-0] INFO  JMQServer - Received socket monitoring event on monitor Receiver with data: tcp://0.0.0.0:9001 512 null
10:24:02.794 [Thread-0] INFO  JMQServer - Received socket monitoring event on monitor Receiver with data: tcp://0.0.0.0:9001 32 null
10:24:02.794 [Thread-0] INFO  JMQServer - Received socket monitoring event on monitor Receiver with data: tcp://0.0.0.0:9001 512 null

**Comment by andreaslarssen** [comment]
Could this be connected to #364?

**Comment by fredoboulo** [comment]
I do not have Windows, but could you confirm that this code is OK to demonstrate the problem? Running on Linux does not input anything, I can see a PULL socket bound on a pubUrl var, and a PUB socket bound on a subUrl var, which sounds and looks weird.

**Comment by amokranebelloui** [comment]
I have a similar issue, on Windows and Mac.
It works when communication between 2 sockets with version 0.4.1 and higher
But does't work when mixing 0.4.1 and higher and 0.4.0 and lower (corresponding to implementation of protocol V3)
I created #455 feel free to close if redundant

**Comment by trevorbernard** [comment]
#455 was closed
