### ISSUE TITLE
is Jeromq interoperable with zeromq.js with Curve?

### ISSUE THREAD

**Issue by chinababu** [zeromq/jeromq#450]
I am having Jeromq consumer and zeromq.js provider.
I am using inbuilt support for curve communication. I created keys pairs properly and set them to both client and server accordingly.
When I sent a message from Jeromq client, message has been sent correctly (I didn't get any error while sending) but server did not receive it (no response from server).
When I disable curve (by not setting the keys) it perfectly works fine.

Is Jeromq interoperable with node binding zeromq.js? Is there any specific way to generate and set the keys? I generated keys using Jeromq library. 
Note: It works fine when both consumer and provider belongs zeromq.js or Jeromq.
Stuck with this for long time. Any help is appreciated.

**Comment by trevorbernard** [comment]
@chinababu I tested the implementation against the following matrix: libzmq and jeromq alternating client and server. It produced the correct results. I would try communicating with a libzmq client with the same keys as you were using with the jeromq client to eliminate improper key propagation. If the problem persists we can look into it further.

**Comment by chinababu** [comment]
Thanks for checking trevorbernard. 
I will wait for your response after your tests complete.

**Comment by chinababu** [comment]
@trevorbernard Trevor,

I tried libzmq client (jzmq) with node. It's not working and I see same behavior as earlier. This is true even when the curve is not used. 
But the other way around is working fine with the curve. ie. node js client to libzmq server.

Since it's failing irrespective of curve, issue seems to be communication related. But communication between ports is tested with other tools and there is no problem with it (I am running this client and server in separate docker containers).

Assuming it's curve issue, is nodejs interpretation of keys is depending on charset? 
Any thoughts?

**Comment by chinababu** [comment]
This has been resolved long back. Not sure what was the fix. So closing.

**Comment by trevorbernard** [comment]
Very nice
