### ISSUE TITLE
Router interprets peer's socket identity as UTF-8 rather than raw bytes

### ISSUE THREAD

**Issue by sigiesec** [zeromq/jeromq#452]
This remains without effect as long as the identity consists of ASCII characters only, but leads to a garbage identity otherwise.

**Comment by jcoeltjen** [comment]
I will have a look at this issue later on this week / next week.

**Comment by fredoboulo** [comment]
Could you provide a minimal test case to illustrate the problem? Which version of the library are you using?

**Comment by sigiesec** [comment]
I don't have a minimal test case at hand, but we will provide one. 

Part of the problem is around Mechanism.setPeerIdentity:
```
    void setPeerIdentity(String data)
    {
        identity = Blob.createBlob(data.getBytes(ZMQ.CHARSET));
    }
```

Here, "data" is passed as a String. But the identity is no string, but simply a blob. Somewhere before, the complementary action is done. If there are only characters, these transformations are transparent, but if there are other characters, they create garbage.
