### ISSUE TITLE
Interoperability between 0.4.1+ and 0.4.0-

### ISSUE THREAD

**Issue by amokranebelloui** [zeromq/jeromq#455]
Can't make 2 sockets communicate after upgrading one side to 0.4.1+ and keeping the other on 0.4.0-

Tried PUSH/PULL PUB/SUB, with different permutations of versions, all not working.
It seems like a handshaking issue / negotiation of protocol version, 
but couldn't debug it further.

example:
 
    // 0.4.0
    public static void main(String[] args) throws Exception {
        ZMQ.Context context = ZMQ.context(1);
        logger.info("ZMQ " + ZMQ.getVersionString());
        ZMQ.Socket socket = context.socket(ZMQ.SUB);
        socket.connect("tcp://localhost:5556");
        socket.subscribe("".getBytes());

        new Thread(() -> {
            while (true) {
                String msg = socket.recvStr(0);
                logger.info("Received: " + msg);
            }
        }).start();
    }

    // 0.4.1
    public static void main(String[] args) {
        ZMQ.Context context = ZMQ.context(1);
        logger.info("ZMQ " + ZMQ.getVersionString());
        ZMQ.Socket socket = context.socket(ZMQ.PUB);
        socket.bind("tcp://localhost:5556");
        logger.info("Bound ");
        new Thread(() -> {
            while (true) {
                String data = "Data" + System.currentTimeMillis();
                socket.send(data);
                logger.info("Sending: " + data);
                try {
                    Thread.sleep(1000);
                }
                catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
            }
        }).start();
    }

**Comment by fredoboulo** [comment]
... 2 stupid mistakes coming from me. If you have the possibility to modify the sources of 0.4.1, may you verify from your side that this could be a correct fix?
In StreamEngine.java, change the enum Protocol with the values 
V0(-1),
V1(0),
V2(1),
V3(3);
If this is correct, I still don't know how to make a test that can take that into account.

**Comment by sigiesec** [comment]
Does this also affect interoperability between JeroMQ 0.4.1 and other ZMTP implementations (NetMQ, libzmq, ...)?

**Comment by fredoboulo** [comment]
Yes.
