### ISSUE TITLE
Android: Internal Router pipe is terminated when wifi is disconnected (and not restored)

### ISSUE THREAD

**Issue by krumberg** [zeromq/jeromq#456]
We use a ROUTER/DEALER setup on Android where each device in the name network keeps a ROUTER socket and multiple DEALER sockets to each remote peer. Our application joins to and disconnects from various networks while we keep the router socket and it's polling thread active. Dealers are created and destroyed as clients join/leave. Since the upgrade to v4.1.7 we have noticed that the internal pipe in the router socket gets terminated (Router.xpipeTerminated) when the devices disconnecting from a wifi but it does not reactivate when reconnecting to a wifi network. Is this a bug or an expected behaviour?

**Comment by fredoboulo** [comment]
I have many questions and thoughts about that:
1. It seems that this is related to https://github.com/zeromq/libzmq/issues/1421
2. Do you bind your ROUTER socket ?
3. May you provide some code stating the situation?
4. If you are using jeromq in Android, do you have a PR if you changed some code :) ?
5. Is it "each device in the same network" ? If so, have you considered https://github.com/zeromq/jyre ?

**Comment by fredoboulo** [comment]
After further investigation, it appears it is a bug, I'll provide a PR in next minutes to solve that.
