### ISSUE TITLE
Is jeromq 4.x fully compatible with 3.x ?

### ISSUE THREAD

**Issue by lishuai0214** [zeromq/jeromq#466]
I use jeromq in openstf, found that it works with jeromq 3.x but not with 4.x, is there any differents between 4.x and 3.x ? http://zeromq.org/ says that "all 4.x releases aim for compatibility with stable releases back to 2.2.0"

**Comment by lishuai0214** [comment]
The core code is:
```
while (!Thread.currentThread().isInterrupted()) {
    byte[] channel = app_puller.recv();
    byte[] message = app_puller.recv();
    app_dealer.sendMore(channel);
    app_dealer.send(message);
}
```

**Comment by trevorbernard** [comment]
What version of jeromq are you using? Also, have you tried the latest master? There was a recent bug in protocol handshaking that was recently fixed that isn't in a stable release yet. https://github.com/zeromq/jeromq/pull/461

**Comment by lishuai0214** [comment]
Thank you for attention, it works with 0.3.4 and 0.3.6, not work with 0.4.1 and 0.4.2
unfortunately it still doesn't work with the latest master, I'm not very sure but it seems some things block between dealer and publisher, I'll provide more information if I have

**Comment by trevorbernard** [comment]
@lishuai0214 can you try with the latest master? This commit might have fixed your issue: https://github.com/zeromq/jeromq/pull/461

**Comment by trevorbernard** [comment]
The latest jeromq downgrades successfully to ZMTP v2 (wire protocol) https://github.com/zeromq/netmq/issues/693

**Comment by LMnet** [comment]
When will this fix be released with a tag? I need it for the [reactive-zmq](https://github.com/2gis/reactive-zmq).

**Comment by trevorbernard** [comment]
Releases happen when there is enough pull from the community and the SNAPSHOT has proven to be stable

**Comment by lishuai0214** [comment]
Thanks a lot, it works with the lastest master !

**Comment by fredoboulo** [comment]
Nice to read that :) Could you tell us the now-compatible other side's version?

**Comment by prodansergiu** [comment]
@fredoboulo just checked this, I've marked below the combinations with successful protocol handshaking:

- [x] 0.3.6 REQ <-> 0.4.0 REP
- [ ] 0.3.6 REQ <-> 0.4.1 REP
- [ ] 0.3.6 REQ <-> 0.4.2 REP
- [x] 0.3.6 REQ <-> 0.4.3-SNAPSHOT REP

Is there an ETA for this fix to be included in a stable release?
