### ISSUE TITLE
How to check socket connection state ?

### ISSUE THREAD

**Issue by aldocano** [zeromq/jeromq#491]
I have update the version and wanted to know if is possible to check socket connection state periodically ?

So then i know if the socket has disconnected and then i should try another connection or restart the old one.

What is a possible workaround of this ?

**Comment by fredoboulo** [comment]
Hello, could you elaborate about your scenario? Have you considered monitoring the socket to be notified of disconnection events?

**Comment by aldocano** [comment]
Hi there i fixed using  Lazy Pirate strategy , thanks for replying.

**Comment by fredoboulo** [comment]
Good :) May we close this issue then?

**Comment by aldocano** [comment]
Yeap sorry.
