### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 256 with jeromq 0.3.6 version

### ISSUE THREAD

**Issue by fjamal21** [zeromq/jeromq#500]
I am using Jeromq in multithreaded environment as shown below. Below is my code in which constructor of `SocketManager` connects to all the available sockets first and I put them in `liveSocketsByDatacenter` map in the `connectToZMQSockets` method. After that I start a background thread in the same constructor which runs every 30 seconds and it calls `updateLiveSockets` method to ping all those socket which were already there in `liveSocketsByDatacenter` map and update the `liveSocketsByDatacenter` map with whether those sockets were alive or not.

And `getNextSocket` method is called by multiple reader threads concurrently to get the next live available socket and then we use that socket to send the data on it. So my question is are we using Jeromq correctly in multithreaded environment? Because we just saw an exception in our production environment with this stacktrace so I am not sure whether it's a bug or something else?

	java.lang.ArrayIndexOutOfBoundsException: 256
	at zmq.YQueue.push(YQueue.java:97)
	at zmq.YPipe.write(YPipe.java:47)
	at zmq.Pipe.write(Pipe.java:232)
	at zmq.LB.send(LB.java:83)
	at zmq.Push.xsend(Push.java:48)
	at zmq.SocketBase.send(SocketBase.java:590)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1271)
	at org.zeromq.ZFrame.send(ZFrame.java:131)
	at org.zeromq.ZFrame.sendAndKeep(ZFrame.java:146)
	at org.zeromq.ZMsg.send(ZMsg.java:191)
	at org.zeromq.ZMsg.send(ZMsg.java:163)

Below is my code:
	
```java
public class SocketManager {
  private static final Random random = new Random();
  private final ScheduledExecutorService scheduler = Executors.newSingleThreadScheduledExecutor();
  private final Map<Datacenters, List<SocketHolder>> liveSocketsByDatacenter = new ConcurrentHashMap<>();
  private final ZContext ctx = new ZContext();

  private static class Holder {
    private static final SocketManager instance = new SocketManager();
  }

  public static SocketManager getInstance() {
    return Holder.instance;
  }

  private SocketManager() {
    connectToZMQSockets();
    scheduler.scheduleAtFixedRate(this::updateLiveSockets, 30, 30, TimeUnit.SECONDS);
  }

  // during startup, making a connection and populate once
  private void connectToZMQSockets() {
    Map<Datacenters, List<String>> socketsByDatacenter = Utils.SERVERS;
    for (Map.Entry<Datacenters, List<String>> entry : socketsByDatacenter.entrySet()) {
      List<SocketHolder> addedColoSockets = connect(entry.getValue(), ZMQ.PUSH);
      liveSocketsByDatacenter.put(entry.getKey(), addedColoSockets);
    }
  }

  private List<SocketHolder> connect(Datacenters colo, List<String> addresses, int socketType) {
    List<SocketHolder> socketList = new ArrayList<>();
    for (String address : addresses) {
      try {
        Socket client = ctx.createSocket(socketType);
        // Set random identity to make tracing easier
        String identity = String.format("%04X-%04X", random.nextInt(), random.nextInt());
        client.setIdentity(identity.getBytes(ZMQ.CHARSET));
        client.setTCPKeepAlive(1);
        client.setSendTimeOut(7);
        client.setLinger(0);
        client.connect(address);

        SocketHolder zmq = new SocketHolder(client, ctx, address, true);
        socketList.add(zmq);
      } catch (Exception ex) {
        // log error
      }
    }
    return socketList;
  }

  // this method will be called by multiple threads to get the next live socket
  // is there any concurrency or thread safety issue or race condition here?
  public Optional<SocketHolder> getNextSocket() {
    for (Datacenters dc : Datacenters.getOrderedDatacenters()) {
      Optional<SocketHolder> liveSocket = getLiveSocket(liveSocketsByDatacenter.get(dc));
      if (liveSocket.isPresent()) {
        return liveSocket;
      }
    }
    return Optional.absent();
  }

  private Optional<SocketHolder> getLiveSocket(final List<SocketHolder> listOfEndPoints) {
    if (!CollectionUtils.isEmpty(listOfEndPoints)) {
      // The list of live sockets
      List<SocketHolder> liveOnly = new ArrayList<>(listOfEndPoints.size());
      for (SocketHolder obj : listOfEndPoints) {
        if (obj.isLive()) {
          liveOnly.add(obj);
        }
      }
      if (!liveOnly.isEmpty()) {
        // The list is not empty so we shuffle it an return the first element
        return Optional.of(liveOnly.get(random.nextInt(liveOnly.size()))); // just pick one
      }
    }
    return Optional.absent();
  }

  // runs every 30 seconds to ping all the socket to make sure whether they are alive or not
  private void updateLiveSockets() {
    Map<Datacenters, List<String>> socketsByDatacenter = Utils.SERVERS;

    for (Map.Entry<Datacenters, List<String>> entry : socketsByDatacenter.entrySet()) {
      List<SocketHolder> liveSockets = liveSocketsByDatacenter.get(entry.getKey());
      List<SocketHolder> liveUpdatedSockets = new ArrayList<>();
      for (SocketHolder liveSocket : liveSockets) { // LINE A
        Socket socket = liveSocket.getSocket();
        String endpoint = liveSocket.getEndpoint();
        Map<byte[], byte[]> holder = populateMap();
        Message message = new Message(holder, Partition.COMMAND);

        // pinging to see whether a socket is live or not
        boolean status = SendToSocket.getInstance().execute(message.getAdd(), holder, socket);
        boolean isLive = (status) ? true : false;

        SocketHolder zmq = new SocketHolder(socket, liveSocket.getContext(), endpoint, isLive);
        liveUpdatedSockets.add(zmq);
      }
      liveSocketsByDatacenter.put(entry.getKey(), Collections.unmodifiableList(liveUpdatedSockets));
    }
  }
}
```

_EDIT: code formatting - @daveyarwood_

**Comment by colini** [comment]
No, I don't think this is correct.  It seems getNextSocket() could return a 0MQ socket to thread A.  Concurrently, the timer thread may access the same 0MQ socket to ping it.  In this case thread A and the timer thread are mutating the same 0MQ socket, which will lead to problems.  OOB exception is one of those problems.

This code might work if every thread first synchronized on a socket before accessing it.  But this multithreaded approach is not very "0MQ-ish".

Another way would be for a single thread to manage all the sockets, and other threads communicate with it via a ROUTER.  That's more of a design discussion, I suggest you post it to stackoverflow.

**Comment by fjamal21** [comment]
I see so what do you think is the best and simple way as of now to get rid of this issue? Any thoughts?

**Comment by colini** [comment]
You could try synchronizing on the Socket instances before accessing them:
```
Socket socket = liveSocket.getSocket();
String endpoint = liveSocket.getEndpoint();
Map<byte[], byte[]> holder = populateMap();
Message message = new Message(holder, Partition.COMMAND);

// using the socket as its own lock
synchronized (socket) {		 
    // pinging to see whether a socket is live or not
    boolean status = SendToSocket.getInstance().execute(message.getAdd(), holder, socket);
    boolean isLive = (status) ? true : false;

    SocketHolder zmq = new SocketHolder(socket, liveSocket.getContext(), endpoint, isLive);
    liveUpdatedSockets.add(zmq);
}
```

But all the other threads would have to do the same, once they retrieve a Socket from a SocketHolder.

Per the docs 0MQ sockets are not thread safe.  But I have used them successfully in Java with multiple threads by always protecting them with a mutex.

**Comment by fjamal21** [comment]
Ok got it.

Also this is how I use `getNextSocket()` method from multiple reader threads concurrently:

	  public boolean sendAsync(final long address, final byte[] encodedRecords) {
		Optional<SocketState> liveSockets = SocketManager.getInstance().getNextSocket();
		return sendAsync(address, encodedRecords, liveSockets.get().getSocket(), false);
	  }

	  public boolean sendAsync(final long address, final byte[] encodedRecords, final Socket socket,
		  final boolean socketMessage) {
		ZMsg msg = new ZMsg();
		msg.add(encodedRecords);
		boolean sent = msg.send(socket);
		msg.destroy();
		retryQueue.put(address, encodedRecords);
		return sent;
	  }
	  
So where I need to synchronized here?

**Comment by colini** [comment]
```
public boolean sendAsync(final long address, final byte[] encodedRecords, final Socket socket,
  final boolean socketMessage) {
    ZMsg msg = new ZMsg();
    msg.add(encodedRecords);    

    // again, using the socket as its own lock while accessing it
    boolean sent;
    synchronized (socket) {
        sent = msg.send(socket);
    }
    msg.destroy();
    retryQueue.put(address, encodedRecords);
    return sent;
}
```

I'm not making any promises!  But that might work.  When you have some time, I recommend you read the whole [0MQ guide](http://zguide.zeromq.org/page:all).  It's long but very well written and would help a lot.  With a better understanding of 0MQ you could implement this w/o any synchronization and a plain HashMap.

**Comment by fjamal21** [comment]
sure will do that. So you think we can get rid of synchronization and just by using plain hash map with the same code I have or I need to use Router you said to accomplish that?

**Comment by colini** [comment]
No, sorry, I didn't mean to confuse.  You would need to redesign this to use a 0MQ ROUTER and a much different approach.

With your current implementation, try the synchronization blocks I suggested and see if that resolves the issue.

**Comment by fjamal21** [comment]
Sure.. I have made the changes and currently working on deploying the build but thing is this exception is happening very rarely and at random.. So I am not sure whether we will be able to notice whether this got fixed or not with this change?

Also do you know what does "256" means here? I know its an index but what it can tell us in terms Jeromq underneath?

java.lang.ArrayIndexOutOfBoundsException: 256

**Comment by fjamal21** [comment]
I forgot to mention one thing. In your previous suggestion you suggested to add synchronized on the socket like this in "updateLiveSockets" method:

```
	// using the socket as its own lock
	synchronized (socket) {		 
		// pinging to see whether a socket is live or not
		boolean status = SendToSocket.getInstance().execute(message.getAdd(), holder, socket);
		boolean isLive = (status) ? true : false;

		SocketHolder zmq = new SocketHolder(socket, liveSocket.getContext(), endpoint, isLive);
		liveUpdatedSockets.add(zmq);
	}
```
	
Now here is my "execute" method in "SendToSocket" class which is being used above:

```
	public boolean execute(final long address, final byte[] holder, final Socket socket) {
		boolean sent = sendAsync(address, encodedRecords, socket, true);
		// if the record was sent successfully, then only sleep for timeout period
		if (sent) {
		  try {
			TimeUnit.MILLISECONDS.sleep(500);
		  } catch (InterruptedException ex) {
			Thread.currentThread().interrupt();
		  }
		}
		return sent;
	}

	public boolean sendAsync(final long address, final byte[] encodedRecords, final Socket socket,
	  final boolean socketMessage) {
		ZMsg msg = new ZMsg();
		msg.add(encodedRecords);    

		// again, using the socket as its own lock while accessing it
		boolean sent;
		synchronized (socket) {
			sent = msg.send(socket);
		}
		msg.destroy();
		retryQueue.put(address, encodedRecords);
		return sent;
	}
	
	public boolean sendAsync(final long addr, final byte[] reco) {
	  Optional<SocketHolder> liveSockets = SocketManager.getInstance().getNextSocket();
	  return sendAsync(addr, reco, liveSockets.get().getSocket(), false);
	}	
```
  
As you can see, my "execute" method is also calling "sendAsync" method by passing the same socket and then in the "sendAsync" method I have another synchronized block. So what will happen in this scenario? Since we already put a synchronized on a socket in "updateLiveSockets" method which inturns calls "sendAsync" and there we do have another synchronized on the socket? Will it go inside?

**Comment by daveyarwood** [comment]
@fjamal21 Have you tried using the latest version of JeroMQ? It's possible that the issue may have resolved itself by now.

**Comment by daveyarwood** [comment]
Closing this for now. Feel free to reopen if it is still an issue using the latest release.
