### ISSUE TITLE
Issue with poller [Polling Continuously]

### ISSUE THREAD

**Issue by jay11ca39** [zeromq/jeromq#507]
I am using **jeromq-0.4.2** library.

Using the poller feature in my application as below:

```
import org.zeromq.ZMQ;
import org.zeromq.ZMQ.Poller;

private Poller mPoller;

While(true) {
System.out.pringln("waiting....")
mPoller.poll();
System.out.println("Got something....")
 if (mPoller.pollin(0)) {
    ......
   }
}
```

But when i run the sample, it is continuously printing: "waiting" and "Got something".

As per the documentation: 
[javadoc - JeroMQ 0.4.2](https://www.javadoc.io/doc/org.zeromq/jeromq/0.4.2)

mPoller.poll() -> Issue a poll call. If the poller's internal timeout value has been set, use that value as timeout; otherwise, block indefinitely.

But it is not blocking it indefinitely.......
In addition, I have tried;
public int poll(long tout)

with different timeout value,  but that is also not working [Not waiting till timeout happen]

Please let me know if I missed something. 

**Thanks in advance..**

**Comment by daveyarwood** [comment]
@jay11ca39 From the code you posted, it looks like you print "Got something" before you check to see if you got something.

To clarify how polling works, here are the basic steps:

1. Create a poller via the context (`Poller poller = ctx.createPoller(numberOfPollItems)`).
2. Register poll items. (`poller.register(socket, ZMQ.Poller.POLLIN)`)
3. Poll (`poller.poll()`). This updates the state of the poller, so that if a message _is available to receive_, that fact can be obtained from the poller.
4. Check to see if a message is available to receive. (`if (poller.pollin(0) { ... }`)
  - (Note that 0 is an index; we're saying, "if there is a message available to receive on the first socket that I registered...")
5. If there is a message to receive, receive it. (`byte[] msg = socket.recv()`)

Does that help?

**Comment by jay11ca39** [comment]
Hi @daveyarwood ,

Thanks for your explanation.
The code and logs I posted is just reference for issue.
I do not have problem in functionality of poller. 
I have one publisher sample and one subscriber sample and using poller, I am able to receive the event from publisher.

But the issue as I specified:

mPoller.poll();

Should wait till  it receive some event from socket.

But that is not happening.
If you see, 

```
1. While(true) {
2. System.out.pringln("waiting....")
3. mPoller.poll();
4. System.out.println("Got something....")
5. }
```

line no: 3, mPoller.poll() should wait indefinitely till it receive something on socket.
But, It is continuously printing logs, it means it is not a waiting for event to come.

**I also tested CPP binding of zeroMQ and it worked well.**

Please let me know if more info is needed.

**Comment by daveyarwood** [comment]
Oh, I see what you're saying.

Can you try a couple of things, for troubleshooting purposes?

1. Call [`poller.getTimeout()`](https://github.com/zeromq/jeromq/blob/v0.4.2/src/main/java/org/zeromq/ZMQ.java#L2843-L2853) to see if there is an internal timeout value other than -1 for some reason. This should not be the case (the default value is -1) unless you call `setTimeout(...)`.

2. Try calling `poller.poll(-1)`, providing a timeout of -1 explicitly, and see if that blocks indefinitely like we expect.

**Comment by daveyarwood** [comment]
Also, just to clarify -- you are receiving a message inside of your `if (poller.pollin(0)) { ... }` block, correct?

My thought is that perhaps there is a message to receive, but you aren't receiving it, so it's just sitting there while you continue to poll.

**Comment by jay11ca39** [comment]
Hello @daveyarwood ,

1.  I tried the poller.getTimeout() it is returning -1  , It means it should wait infinitely.
2.  I tried poller.poll(-1) also, but it also didn't work.
3. Are receiving a message inside of your if (poller.pollin(0)) { ... } block, correct?
   -- Yes I am receiving the message inside poller.pollin(0)

**Comment by fredoboulo** [comment]
@jay11ca39 Could you provide a compilable test case?

```
    @Test
    public void testPollerInfinite() {
        ZMQ.Context ctx = ZMQ.context(1);
        Socket socket = ctx.socket(ZMQ.DEALER);
        ZMQ.Poller poller = ctx.poller();
        poller.register(socket, ZMQ.Poller.POLLIN);
        int idx = 0;
        while(++idx < 10) {
            System.out.println("waiting....");
            int rc = poller.poll();
            System.out.println("Got something.... " + rc);
            if (poller.pollin(0)) {
                System.out.println("in");
           }
        }
        socket.close();
        ctx.close();
    }
```

does the job for me, the code never reaches the "Got something" trace.

However, if there is no socket registered, the poll returns immediately, with rc == 0.

Giving some code-based facts (like a compilable unit test case demonstrating the problem) will help us to dig deeper on the topic. Repeatability could also help us (systematic, once in a while, every 8 hours), as well as OS, JDK, .... information.

**Comment by daveyarwood** [comment]
> However, if there is no socket registered, the poll returns immediately, with rc == 0.

I didn't know that! That could be relevant here. @jay11ca39 Can you confirm that you registered sockets to the poller?

**Comment by jay11ca39** [comment]
Hello @daveyarwood ,

This is the  complete sample app:

```
package issue;

import org.zeromq.ZMQ;
import org.zeromq.ZMQ.Poller;

public class App 
{
     private static ZMQ.Socket mSubscriber;
     private static ZMQ.Context mContext;
     private static Poller mPoller;
     private static ZMQ.Socket mShutdownClient;
    
    public static void main( String[] args )
    {
		mContext = ZMQ.context(1);
		mShutdownClient = mContext.socket(ZMQ.PAIR);
		String address = "inproc://socket-1";
		mShutdownClient.connect(address);
		mSubscriber = mContext.socket(ZMQ.SUB);
		mSubscriber.connect("tcp://107.108.81.6:5563");
	
    	        mPoller = mContext.poller(2);
		mPoller.register(mSubscriber);
		mPoller.register(mShutdownClient);
    	
    	        System.out.println("get timeout: "+ mPoller.getTimeout());
		while (true) {
			if (null == mSubscriber || null == mPoller) {
				return;
			}

			System.out.println("waiting....");
			mPoller.poll(-1);
                         System.out.println("Got something.... ");
			if (mPoller.pollin(0)) {
                                System.out.println("got event on socket 0");
			} else if (mPoller.pollin(1)) {
				System.out.println("got event on socket 1");
			}
		}  	
    }
}

```
Please let me know if i missed anything..

**Comment by daveyarwood** [comment]
Hmm, that code looks reasonable to me. I don't see anything obvious that would cause the issue you're describing. Sorry I can't be of further help here.

**Comment by fredoboulo** [comment]
It seems to be related to POLLOUT event.

if you register to specific IN or ERR events, like: 

```
mPoller.register(mSubscriber, Poller.POLLIN | Poller.POLLERR);
mPoller.register(mShutdownClient, Poller.POLLIN | Poller.POLLERR);
```
can you confirm that you are waiting as expected?

**Comment by jay11ca39** [comment]
Hello @fredoboulo,

I verified with:
mPoller.register(mSubscriber, Poller.POLLIN | Poller.POLLERR);
mPoller.register(mShutdownClient, Poller.POLLIN | Poller.POLLERR);

It worked well. :)

But there is bug with register method without events:
mPoller.register(mSubscriber);
mPoller.register(mShutdownClient)

Is it well known?  Is anybody is going to take care of that issue?

**Comment by fredoboulo** [comment]
First of all, I checked out with 0.3.6, and it seems to behave the same, meaning that the following code does not wait. (N.B. If I change the socket type to SUB, poll() waits forever).

```
@Test
    public void testPollerInfinite() {
        ZMQ.Context ctx = ZMQ.context(1);
        Socket socket = ctx.socket(ZMQ.PAIR);
        ZMQ.Poller poller = ctx.poller();
        poller.register(socket, ZMQ.Poller.POLLOUT);
        int idx = 0;
        while(++idx < 10) {
            System.out.println("waiting....");
            int rc = poller.poll();
            System.out.println("Got something.... " + rc);
            if (poller.pollin(0)) {
                System.out.println("in");
           }
        }
        socket.close();
        ctx.close();
    }
```
So, it seems POLLOUT event is source of the problem - combined with specific types of sockets, we may have a breach of contract but I do not know where: my understanding is that when we are registering for POLLOUT events, we are interested for availability of write events (aka we are able to write some data on the socket?). Can someone else confirm or infirm this meaning?

**Comment by fredoboulo** [comment]
[http://api.zeromq.org/4-2:zmq-poll](http://api.zeromq.org/4-2:zmq-poll)
specifies that 

> ZMQ_POLLOUT
> For ØMQ sockets, at least one message may be sent to the socket without blocking. For standard sockets this is equivalent to the POLLOUT flag of the poll() system call and generally means that at least one byte of data may be written to fd without blocking.

**Comment by jay11ca39** [comment]
Thanks @daveyarwood  and @fredoboulo , It is fixed using the:

```
mPoller.register(mSubscriber, Poller.POLLIN | Poller.POLLERR);
mPoller.register(mShutdownClient, Poller.POLLIN | Poller.POLLERR);
```
So, I am closing the issue..:)
