### ISSUE TITLE
mvn package gets stuck at XpubXsubZTest

### ISSUE THREAD

**Issue by acarvajalc** [zeromq/jeromq#508]
Hello everyone,

I am trying to build jeromq in a **Windows 10** computer with the **latest versions** of Java and Maven. Unfortunately, the build gets stuck at **XpubXsubZTest**, after running several tests in a successful way. 

I tried run the build in a different computer with the same characteristics and the result was the same. I asked a friend for help and he reported the same issue, we suspect that it might be a bug in the jeromq code.

Thank you for any help you can provide.

**Comment by fredoboulo** [comment]
Hello,

It may be OS-specific, with Ubuntu and java 8 on my machine, I was able to run more than 1000 repetitions of this test class without hanging.
May you provide some more details: java used, which method is getting stuck... ?

**Comment by acarvajalc** [comment]
Hi,

I tried to run the build in another computer with the same gang on.

Details:
OS: Windows (10.0.16299.64 and .98)
Java: SE development kit 8u151 and 8u152
Maven 3.5.2

It hangs while running mvn package, at "maven-surefire-plugin:2.12.4:test (default-test) @ jeromq"

**Comment by fredoboulo** [comment]
Could you try to add some sleep, for example around line 50 between subscriber and publisher

```
ZMQ.msleep(500);
```
It may be that the test is sensitive to initialization.
I believe that's worth a shot to assess that the test is robust enough for every OS before starting to investigate into main code.

**Comment by acarvajalc** [comment]
Hi, 

I tried but it still hangs.

**Comment by mbelling** [comment]
I ran in to this issue on windows as well.  It seems to be that the publisher blows through all or most of its publishes before the subscriber starts listening.  The test was not related to what I was trying, so I just upped the publishers messages to something like 10000 to make the test pass.

It might be worth refactoring the test to not be susceptible to timing failures.

**Comment by fredoboulo** [comment]
Hello @mbelling ,

Awesome! Would you mind proposing a PR to fix it?

**Comment by mbelling** [comment]
Sure, I'll see what I can do if I can find some time.
