### ISSUE TITLE
Issue of 100%  memory usage in JeroMQ

### ISSUE THREAD

**Issue by jay11ca39** [zeromq/jeromq#509]
Hello All,
I am using **jeromq-0.4.2** library.

**Following is my setup:**
```
1. C++ Publisher  [Using 4.2.2 release of libzmq]
    - Number of publishers: 10 [Publishing at different ports: (5870 - 5879)]
    - Publishing at a delay of 10ms 
    -  Event size is 300Bytes
2.  Java Subscriber
    - 10 subscribers subscribed for events with different port publisher. (5870 - 5879)
```

**Issue**
The memory usage keep on increasing and after some time it is going out of memory:
```
java.lang.OutOfMemoryError:  Java heap space
java.lang.OutOfMemoryError:  Java heap space
```

As per this, it seems some memory leak in JeroMQ. But I could not find the exact reason where the problem is .

**Note: The same setup is worked for java publisher and java subscriber.**

**Comment by trevorbernard** [comment]
Can you confirm this is the case for v0.4.3 which is the latest stable release

**Comment by jay11ca39** [comment]
Hello @trevorbernard ,
Thanks for your suggestion. With latest version v0.4.3 this is not happening.
But was this a known problem in v0.4.2 & where was the problem exactly?

**Comment by fredoboulo** [comment]
Hello,

It was not identified per se to the extent of my knowledge, but an optimization was added in 0.4.3 to avoid getting bytes array of messages in XPub and XSub sockets. That may explain the situation, although it is mostly conjectures... I guess a 'git bisect' would help in that case to properly find the cause.

**Comment by jay11ca39** [comment]
Thanks @fredoboulo for your reply, it fixed the issue. 
I will investigate the cause, if I get time.:)
