### ISSUE TITLE
Status of ZeroMQ Java bindings.

### ISSUE THREAD

**Issue by rsanhuez** [zeromq/jeromq#513]
Hi everyone,

I would really appreciate if someone can tell me about the status of the ZeroMQ java bindings. Is JeroMQ production ready? I posted a[ similar question in stackoverflow](https://stackoverflow.com/questions/47964315/is-jzmq-deprecated), but no one answered it. 

Best regards

**Comment by daveyarwood** [comment]
I've responded to your question on SO: https://stackoverflow.com/questions/47964315/is-jzmq-deprecated/48062938#48062938

To answer the question "Is JeroMQ production ready?" I would say yes, in my opinion, but as always, use your best judgment when using open source libraries in production.
