### ISSUE TITLE
Getting CurveMQ working

### ISSUE THREAD

**Issue by owenson** [zeromq/jeromq#521]
Sorry to post this on here, I couldn't find much in the way of documentation.

I've been trying to get CurveMQ working through JeroMQ with te REQ/REP model.

Server code:

        ZMQ.Socket responder = context.socket(ZMQ.REP);
        responder.setCurveServer(true);
        responder.setCurveSecretKey(Z85.decode(serverPrivateKey));
        responder.bind("tcp://*:5555");

and client code:
        ZMQ.Socket requester = context.socket(ZMQ.REQ);
        Curve kp = new Curve();
        byte [][]kpair = kp.keypair();
        requester.setCurveServerKey(Z85.decode("..........."));
        requester.setCurvePublicKey(kpair[0]);
        requester.setCurveSecretKey(kpair[1]);
        requester.setCurveServer(false);
        requester.connect("tcp://localhost:5555");

but I can't for the life of me get it to send any data?  Are you able to point me at the problem lease?

**Comment by fredoboulo** [comment]
Hello,

did you have a look at [ZAuthTest](https://github.com/zeromq/jeromq/blob/e2794da8075443644c1f2e03231b81ca2ce9bcce/src/test/java/org/zeromq/auth/ZAuthTest.java#L323) ?
You need to have one [ZAP](https://rfc.zeromq.org/spec:27/ZAP) component in your code to handle authentication.

**Comment by owenson** [comment]
Thank you.  I saw the Curve test but didnt realise the auth requirement.

Thanks again.

**Comment by owenson** [comment]
Sorry I'm being really dense I feel.  But it is so hard to find documentation on this.  I've run the ZAPTest you supplied, which works absolutely fine.  However, there is a shared context between the client and the server and I'm having difficulty understanding 1) whether ZAuth runs on both client and server, 2) How ZAuth interacts with the socket, it seems to be attached to the content, 3) When in the normal recv-reply flow should I call nextReply() (what even is nextReply?) as I don't have connection level information?

ZAuth is attached to the context in the test, so I don't really understand whether it is interacting with the client at all.

My architecture is I have a REP server, clients send requests and get replies.  I've tried placing nextReply in various different places, on the client and the server but still banging my head against the brick wall.

I've read the spec about ZAP, but it seems to be built on REP-REQ, which I assume is one layer lower than my application.

So I guess, is it possible you could just give me some example code for client and for server separate please for a REQ server and REP client?  I have the application working, I'm just trying to bolt on the security now.

This is my server:
        ZContext context = new ZContext();
        ZAuth auth = new ZAuth(context);//, new ZCertStore.Hasher());
        auth.setVerbose(true);
        auth.configureCurve(ZAuth.CURVE_ALLOW_ANY);
        auth.replies(true);
        
        //  Socket to talk to clients
        ZMQ.Socket responder = context.createSocket(ZMQ.REP);
        responder.setZAPDomain("global");
        responder.setCurveSecretKey(Z85.decode(serverPrivateKey));
        responder.setCurveServer(true);

then a while loop, recv request and reply.  But where does ZAP nextReply go?

This is my client.

       ZContext context = new ZContext();

        ZMQ.Socket requester = context.createSocket(ZMQ.REQ);

        Curve kp = new Curve();
        byte [][]kpair = kp.keypair();

        requester.setCurveServerKey(Z85.decode("..35Q!Q2YZw8m1PAg>!!F)<AK-hq5XY0e%ii+y/A"));
        requester.setCurvePublicKey(kpair[0]);
        requester.setCurveSecretKey(kpair[1]);
        requester.setCurveServer(false);

        requester.connect("tcp://localhost:5555");

does the client need ZAuth and nextReply?

**Comment by trevorbernard** [comment]
Here is a working example I made months ago before ZAuth was implemented. YMMV https://gist.github.com/trevorbernard/6e3a8af0092cdced0f8b3e757a5b6b16

**Comment by fredoboulo** [comment]
Don't be sorry, the documentation for that part seems ... well, light.

I can tell you what is my understanding so far:

- to connect with CURVE, you need a ZAP component that will authenticate the connection for you.
- this ZAP component is related to the context of the "server" (the socket where code calls setCurveServer(true))
- all ZAP components have to provide an inproc REP socket bound on a predefined endpoint "inproc://zeromq.zap.01". So one ZAP component per context at max.

- ZAuth is a basic example of a ZAP component that will let you handle various authentication schemes. 
- ZAuth provides a fancy way to be notified of authentication responses when a client socket tries to create an authenticated connection to the "server", aka the replies. These replies are not mandatory so your code can always call ZAuth.replies(false), and all authentication attempts will still happen but with no notifications (if you are not interested in the replies, it is actually much better to turn them off; if you want to check if your client connects to the "server" it may be useful at the beginning and you can call nextReply AFTER the "server" sent the first message).

- with CURVE, your code needs proper keys configured on both client and server, and on ZAuth, if your code uses it.

**Comment by owenson** [comment]
Thanks very much for your detailed reply. That clears a lot up for me and I've now managed to get it working.

Thanks ever so much.
