### ISSUE TITLE
testProtocolVersion1short or testProtocolVersion2short fail indeterministically

### ISSUE THREAD

**Issue by Boskovits** [zeromq/jeromq#524]
I sometimes get a test failure where testProtocolVersion1short or testProtocolVersion2short fails. The reason of failure is timeout. Rising the timeout value does not help. testProtocolVersion1long and testProtocolVersion2long passes. Could you give me some pointers what can go wrong here?

**Comment by fredoboulo** [comment]
Hello,

these are some of the latest tests introduced in Jeromq, introducing some coverage about handshake and protocol negotiation.

I tried to change the tests a bit, basically by connecting after binding for the monitoring socket, and waiting for monitor to complete. Could you have a try with the fix I referenced?

**Comment by fredoboulo** [comment]
I may have found a condition, after setting several repetitions of the test: it seems that after the handshake, data may be present inside handshake buffer and was not decoded. Well, that's my diagnostic so far...

**Comment by Boskovits** [comment]
Thank you very much for looking into this. I will try the fix, and report back with the result.

**Comment by Boskovits** [comment]
The fix referenced seems to solve this issue. However I notice other test failures after applying the fix. For example now zmq.socket.pipeline.PushPullSpecTest fails an assertion in testSpecPullFairQueueIn, with expected 0, but was 2. Can this be related to this, or is it something totally different?

**Comment by Boskovits** [comment]
I also have the assertion on line 177 in PubSubHwmTest failing with a value 0...

**Comment by Boskovits** [comment]
Acutally it is quite indeterministic which test fails...

**Comment by fredoboulo** [comment]
It works for me (which is not a proper answer).
I may be wrong, but I doubt it is related: the fix is related to the handshake downgrade to protocols version 1 and 2. The test you are talking about uses protocol v3 (the latest).

**Comment by fredoboulo** [comment]
I proposed a PR with no merge instruction, to be sure.
Every PR runs all the tests 4 times: 2 times with java 7, 2 times with java 8.

To gather extra information, what is your OS, java version ... ?

**Comment by Boskovits** [comment]
I agree, this fix solves the issue. The problem I mentioned is probably unrelated, as I also experience it in 0.4.2. Thank you very much. I'm currently running a git bisect, so that I can find where that gone wrong.
My current os version GuixSD, with Guix version cb723be5b98a57...
Java version is: icedtea7 2.6.12

**Comment by Boskovits** [comment]
Sorry, I reopen this, as I have seen that the pull request is not merged yet. Please close when merged.
