### ISSUE TITLE
REQ-REP pattern hangs with message size 16373

### ISSUE THREAD

**Issue by DavidRobb** [zeromq/jeromq#532]
Have an SSCE that shows request reponse message hangs when the message size is 16373 (just shy of 16K?). Appears to be a problem since version 0.4.1:

`package uk.co.comsci.client;

import java.io.IOException;
import java.util.Arrays;
import org.zeromq.ZMQ;

public class Server {

    public static void main(String[] args) throws IOException {

        ZMQ.Context ctx = ZMQ.context(1);
        final ZMQ.Socket responder = ctx.socket(ZMQ.REP);

        System.out.println("Binding server socket");
        responder.bind("tcp://*:6556");

        // Response message data. content irrelevant
        byte[] repMsg = new byte[1024*1024];
        Arrays.fill(repMsg, (byte)'e');

        // Sens a message response of the requested size
        while (!Thread.currentThread().isInterrupted()) {
            String msg = responder.recvStr();
            System.out.println("Server got " + msg);
            int size = Math.min(Integer.parseInt(msg.substring(5)), repMsg.length);
            responder.send(repMsg, 0, size, 0);
        }

        responder.close();

        ctx.term();
    }

    
}

package uk.co.comsci.client;

import java.io.IOException;
import org.zeromq.ZMQ;

public class Client {

    public static void main(String[] args) throws IOException {

        ZMQ.Context ctx = ZMQ.context(1);
        ZMQ.Socket sock = ctx.socket(ZMQ.REQ);

        String serverStr = "tcp://localhost:6556";
        System.out.println("Connecting to server" + serverStr);
        sock.connect(serverStr);

        for (int msgSize = 0; msgSize < 20000; msgSize++) {
            String msg = "tick " + msgSize;
            sock.send(msg.getBytes());
            byte[] response = sock.recv();
            System.out.println("Tick " + msgSize + " got " + response.length);
        }
        
        ctx.term();
    }

}
`

**Comment by fredoboulo** [comment]
Could you give a try with 0.4.3-SNAPSHOT ? A fix has been made in this area lately, and I could not reproduce your error with latest code (0.4.1 and 0.4.3 have the error)

**Comment by DavidRobb** [comment]
Still hangs for me with 0.4.3-SNAPSHOT from

`<repositories>
      <repository>
        <id>sonatype-nexus-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
          <enabled>false</enabled>
        </releases>
        <snapshots>
          <enabled>true</enabled>
        </snapshots>
       </repository>
    </repositories>`

**Comment by trevorbernard** [comment]
the snapshot on nexus is likely older. I would clone the repo and `mvn install`

**Comment by trevorbernard** [comment]
Also, it would be 0.4.4-SNAPSHOT since the last stable release is v0.4.3

**Comment by DavidRobb** [comment]
OK. Works fine with the latest 0.4.4-SNAPSHOT built from the repo.

Which is likely to be the most stable out of 0.3.6, 0.4.0, 0.4.4-SNAPSHOT?

**Comment by fredoboulo** [comment]
@DavidRobb may you check if the test in #533 reflects correctly your SSCE ?

**Comment by DavidRobb** [comment]
Yes. That does cover the issue. Many thanks.

**Comment by fredoboulo** [comment]
awesome :) would you mind closing this issue?

**Comment by DavidRobb** [comment]
No problem. Thanks for the quick response.
