### ISSUE TITLE
A FAQ is missing

### ISSUE THREAD

**Issue by fbacchella** [zeromq/jeromq#541]
A simple FAQ would be helpful.

When someone starts on jeromq, there is some simple questions what will help peoples identify pitfall.

There is a least three wrappers: zmq.Ctx, ZMQ.Context, ZContext. Which one to use ?
There is two pollers: ZPoller and ZMQ.Poller, which is the one returned by ZContext. Again, which one to use ?

A sample to use Curve can be found at https://gist.github.com/trevorbernard/6e3a8af0092cdced0f8b3e757a5b6b16, but it's not in src/test/java/guide. It could be part of the FAQ.

There is a lot of defined exceptions, that overlap and are declared in different ways:
```
org/zeromq/ZMQException.java:public class ZMQException extends RuntimeException
zmq/ZError.java:    public static class CtxTerminatedException extends RuntimeException
zmq/ZError.java:    public static class InstantiationException extends RuntimeException
zmq/ZError.java:    public static class IOException extends RuntimeException
```
Is there any guide about that ?

What about the package org.zeromq versus zmq. Why two root packages ? Is there any meaning about that ?

**Comment by daveyarwood** [comment]
I completely agree that it is not intuitive how to get started with JeroMQ. It is particularly confusing to newcomers the fact that there are 3 classes (the ones you mention) that sound like ZMQ contexts, and it isn't clear which one to use.

A FAQ is a good idea, but I think possibly better would be some structured docs for JeroMQ in particular (not just ZMQ in general -- there are plenty of good docs for that). We could at least use a "quick start" guide that walks you through using a ZContext to create some sockets and pollers and reproduce an example or two from the zguide. The quick start guide could also explain (or perhaps link to other documents that explain) things like the difference between the org.zeromq and zmq packages, and the different error types.

In my mind, we have three options for where to put these docs:

1. In the javadocs.
2. As a series of Markdown files in a `doc` folder at the root of this repo.
3. In the GitHub wiki. (We do already have some random information there, but it is unstructured and of questionable validity at this point, given its age)

**Comment by daveyarwood** [comment]
Not to mention ZSocket :)

**Comment by daveyarwood** [comment]
I might take an initial stab at these docs whenever I have some time.
