### ISSUE TITLE
ZMQ_NOBLOCK is deprecated

### ISSUE THREAD

**Issue by fbacchella** [zeromq/jeromq#548]
Looking at http://api.zeromq.org/2-1:zmq-send, I see that I can have no blocking send using the flag `ZMQ_SNDMORE`. I'm using  `ZMQ.Socket.send(byte[] data, int flags)`  I went hunting for flags value in the javadoc and found `zmq.ZMQ.ZMQ_NOBLOCK`. But it's deprecated. What should I use instead ? It should be in the javadoc.

**Comment by mollicaw** [comment]
I may be wrong, but could that be `boolean ZMQ.Socket.setSendTimeOut(int)`/`boolean ZMQ.Socket.setReceiveTimeOut(int)`?

**Comment by fbacchella** [comment]
I found it reading the source code, it's zmq.ZMQ.ZMQ_DONTWAIT. But it should be in Javadoc, not needing to dig in the code.

**Comment by fredoboulo** [comment]
Latest code is based on 4.1, please look at http://api.zeromq.org/4-1:zmq-send instead.

**Comment by fbacchella** [comment]
That's the rational for the change, I don't argue about that. But the javadoc should give hint where to look when something is deprecated. Just add a little "changed to DONTWAIT, to comply with 4.1 API", that should be enough.

**Comment by fredoboulo** [comment]
Pour la petite histoire, it's part of the C4 explanation by Pieter Hintjens: 
http://zguide.zeromq.org/page:all#Evolution-of-Public-Contracts

Jeromq started by implementing 3.x, so NOBLOCK may never have been present, it was already deprecated from the very beginning.

More constructively, adding javadoc in send and recv methods may even make more sense, but it would be kinda duplicated in several places: zmq.ZMQ static methods, zmq.SocketBase, org.zeromq.ZMQ.Socket, and I may have forgotten some of them.

**Comment by sigiesec** [comment]
What does "comply with 4.1 API" mean? Do you refer to the libzmq API? There is no language-neutral API specification AFAIK, so the JeroMQ API can only be "inspired by" some version of the libzmq API.
