### ISSUE TITLE
jeromq 0.4.3 may have memory leak issue

### ISSUE THREAD

**Issue by ymmihw** [zeromq/jeromq#574]
when use jeromq 0.4.3, i occasionally found that the old gen takes lots of memory.

i dump the heap twice, and found that there are some items in the YQueue seems unchanged. i guess this may be an issue.

![1](https://user-images.githubusercontent.com/12890433/42143625-b16fbccc-7de8-11e8-9033-a9dcc02e90e1.jpg)

![2](https://user-images.githubusercontent.com/12890433/42143626-b1c05aec-7de8-11e8-9ac6-6b5b8d97f054.jpg)

**Comment by fredoboulo** [comment]
Hi,
do your sockets communicate normally? Which type of sockets are you using?

If you could provide an example of code, we could investigate a bit further.

The YQueue normally nullifies references to messages when popped. There is still a case when unflushing the queue but this part of code seems to be activated in case of socket termination or error in the session.

**Comment by ymmihw** [comment]
@fredoboulo 
I use PUB/SUB socket and don't call the ```disconnect(connectAddr)``` or ```close()``` of the PUB socket when not use them any more.

is this a misuse ?

**Comment by fredoboulo** [comment]
If you do not read from them and they are still connected, sockets will continue to receive messages that will not be read, so be kept in memory.
Does it happen in the PUB or the SUB sockets?

**Comment by ymmihw** [comment]
It happens in the PUB socket.

```
socket.send(topicBytes, ZMQ.SNDMORE);
socket.send(dataBytes); // <---------------- interrupted
```
the PUB thread may be interupted at the line above and throws ClosedByInterruptException. I catch the exception and may still use the interrupted socket send data.

**Comment by fredoboulo** [comment]
You should not interrupt a thread using a socket, this feature is still unsupported.
There are other patterns to properly stop a running thread; usually using a control pipe.

**Comment by ymmihw** [comment]
@fredoboulo
thank you
