### ISSUE TITLE
at zmq.socket.pubsub.Dist.terminated(Dist.java:102)  ERROR

### ISSUE THREAD

**Issue by xixifeng** [zeromq/jeromq#579]
zmq.socket.pubsub.Dist.java line: 102
```Collections.swap(pipes, pipes.indexOf(pipe), eligible - 1); ```
The length of '(eligible - 1)' may bigger than length of pipes, that must cause the java exception of IndexOutOfBoundsException.

```java
java.lang.IndexOutOfBoundsException: Index: 172, Size: 172
     at java.util.ArrayList.rangeCheck(ArrayList.java:653)
     at java.util.ArrayList.set(ArrayList.java:444)
     at java.util.Collections.swap(Collections.java:497)
     at zmq.socket.pubsub.Dist.terminated(Dist.java:102)
     at zmq.socket.pubsub.XPub.xpipeTerminated(XPub.java:156)
     at zmq.SocketBase.pipeTerminated(SocketBase.java:1123)
     at zmq.pipe.Pipe.processPipeTermAck(Pipe.java:397)
     at zmq.ZObject.processCommand(ZObject.java:91)
     at zmq.Command.process(Command.java:75)
     at zmq.SocketBase.processCommands(SocketBase.java:936)
     at zmq.SocketBase.send(SocketBase.java:696) 
```

**Comment by trevorbernard** [comment]
Can you provide a repeatable test that causes this issue?

**Comment by fredoboulo** [comment]
@xixifeng are you using the socket in a threadsafe way (all operations like send, receive, getting options and closing the socket have to be performed in the same thread) ?

**Comment by daveyarwood** [comment]
Blocked pending answers from @xixifeng.

**Comment by xixifeng** [comment]
是线程不全造成的,此问题已经解决,谢谢大家!

**Comment by daveyarwood** [comment]
Google translation:

> This is caused by incomplete threads. This problem has been solved. Thank you!

**Comment by xixifeng** [comment]
@daveyarwood 
亲爱的朋友,你发现中文的魅力了吗?极少数的字可以表达更广的意思.当然,英语也很美.zeromq也很棒.

**Comment by daveyarwood** [comment]
@xixifeng 其实，我在大学学过一点中文！但是，很久没练习了。:sweat_smile:

**Comment by xixifeng** [comment]
@daveyarwood 
作为一个外国人,你这句中文说得非常好。“其实”表示承上文，“但是”表示转折的语气，这个你都知道，就连标点符号都用对了，很了不起！中文博大精深，她是立体、多维的。就算是我们这些把中文当作母语的人都很难掌握，你的智力非凡，如果你愿意继续学习中文，一定能更上一层楼。
一次偶然机会，我听到 clojure 之父 Rich Hickey 的演讲,他说,“建议年轻人应该追求其它的学习兴趣去帮助理解在编程中的各种问题”。我知道你也使用 clojure，学习中文的思维，可能对编程有帮助，就像我学习英文一样，从中受益匪浅。

**Comment by xixifeng** [comment]
@daveyarwood 
Hi, dave yarwood。
我想认识你，你给我的印象很深刻。我想向你学习，你有微信（WeChat）吗？

**Comment by daveyarwood** [comment]
我没有WeChat，但是我很喜欢电子邮件通信。 你可以给我写电子：dave.yarwood@gmail.com

Zoom，Skype或者Google Hangouts 也可以。但是，我说中文说的不太好！很多久没联系了。:sweat_smile:  你的英语好不好？

(Sorry to whomever might be getting notifications for each of these messages back and forth between me and @xixifeng ! Let's switch to email.)

**Comment by xixifeng** [comment]
Dear Dave Yarwood, I have ritten to you.
Let's switch to eamil.
@daveyarwood
