### ISSUE TITLE
ZMTP 3.0 implementation

### ISSUE THREAD

**Issue by miniway** [zeromq/jeromq#59]
zmtp 3.0 implementation in JeroMQ

https://github.com/zeromq/libzmq/pull/552

**Comment by daveyarwood** [comment]
ZMTP 3.0 spec: https://rfc.zeromq.org/spec:23/ZMTP

> ## Changes from ZMTP 2.0
>
> The changes in version 3.0 of the specification are a simpler version numbering scheme, the addition of security mechanisms, the removal of hard-coded connection metadata (socket type and identity) from the greeting, the addition of connection metadata, and the addition of commands.

The spec explains the above changes in much greater detail.

I'm not sure how much of this may have already been implemented. As a first step, I propose that we break out the individual 2.0 => 3.0 changes into separate issues that are smaller and more manageable. Each issue would involve digging into the JeroMQ codebase and determining what changes, if any, are necessary in order for that aspect of JeroMQ to be compatible with ZMTP 3.0.
