### ISSUE TITLE
support for jigsaw modules

### ISSUE THREAD

**Issue by damnms** [zeromq/jeromq#591]
is there any plan to move to java9 modules? because this is now a killer for my project. would love to use jeromq but i see no way to use it on java 11.

**Comment by damnms** [comment]
i use it now with automatic modules, but would really love to have a module-info

**Comment by trevorbernard** [comment]
@damnms If you submit a pull request with module-info, we'd be more than happy to merge it in

**Comment by damnms** [comment]
it is not that easy to just provide a module-info, this is a big thing

**Comment by trevorbernard** [comment]
@damnms I over simplified, my apologies, but the original thesis still applies. If you submit a pull request with support or jigsaw modules, we'd be happy to merge it in. Otherwise, you'll have to wait until someone is suffering from the same problem and decides to fix it themselves.
