### ISSUE TITLE
simple server/client example

### ISSUE THREAD

**Issue by damnms** [zeromq/jeromq#593]
is there some simple client/server example? i did not find one. i am currently trying to get the basics working.
```
import org.zeromq.ZContext;
import org.zeromq.ZMQ;

public class Server {

    ZContext context = new ZContext(1);
    ZMQ.Socket socket = context.createSocket(ZMQ.PAIR);

    public static void main(String args[]) {
        Server server = new Server();
        server.start();

    }

    public void start() {

        // Socket to talk to clients
        socket.bind("tcp://*:10101");
        byte[] recv = socket.recv();
        System.out.println("Received " + new String(recv));
    }

    public void stop() {
        socket.close();
        context.close();
    }
}

```
```
import org.zeromq.ZContext;
import org.zeromq.ZMQ;

public class Client {

    ZContext context = new ZContext(1);
    ZMQ.Socket socket = context.createSocket(ZMQ.PAIR);

    public void sendMessage() {
        socket.connect("tcp://127.0.0.1:10101");
//        byte[] recv = socket.recv();
//        if (recv != null) {
//            System.out.println("received: " + new String(recv));
//        }
        boolean b =  socket.send("hi");
        System.out.println("Sent with return: " + b);
    }

    public static void main(String args[]) {
        Client client = new Client();
        client.sendMessage();
    }

}
```

Can someone tell me why this is not working? The client sends the data and "b" is true, so i assume it is sent. But the server never receives it.

**Comment by daveyarwood** [comment]
The README has a [Getting Started](https://github.com/zeromq/jeromq#getting-started) with a simple "hello world" client/server example.

Off-hand, I'm not sure why your example isn't working. It seems reasonable enough to me, although you'll probably want to at least add a loop to the server code, so that it continuously receives and prints messages. I would start with the code in the Getting Started example and go from there.

**Comment by damnms** [comment]
Thanks, but that example also did not work. The server is running, my client (unfortunately there is no client example) connected and sent a message but the server does not respond to it. I set a breakpoint at line ```
System.out.println(
                        "Received: [" + new String(reply, ZMQ.CHARSET) + "]"
                );
```
which got never reached.

I use openjdk-10.0.2 on win7 x64 with intellij ultimate 2018.2

**Comment by daveyarwood** [comment]
Hmm, it's starting to sound like there could be some OS or JDK-specific issue there. Have you tried other JDKs? I think we've mainly just been using Oracle or OpenJDK 8. JDK 10 is fairly new, I wouldn't be surprised if there are some edge cases there that make JeroMQ not work out of the box.

**Comment by daveyarwood** [comment]
Can you show the code you are trying to run? I'm surprised it doesn't work on Linux with Java 8.

**Comment by damnms** [comment]
??
The code is above

**Comment by daveyarwood** [comment]
I mean the code you're running that's adapted from the example.

Another thing to try: cloning this repo and running `mvn test`. If most/all of the test suite fails, then you probably have a some OS-specific networking issue.

**Comment by damnms** [comment]
> I mean the code you're running that's adapted from the example.
There is no simple client example, only a server example. The server is more or less equal to the example. The client i made myself.

> try: cloning this repo and running mvn test
Thats a good idea. Will try that this evening

**Comment by fredoboulo** [comment]
Hi, I noticed you did not close the context of the client and did not set linger of the socket to -1.

The meaning of send() true is more like "Ok, I queued the message and will make best efforts to actually send it".

As the client is stopped straight after queuing the message, this message might not have processed by the I/O thread.

Closing the context with linger -1 will block until all pending messages have been sent to a peer.

**Comment by fredoboulo** [comment]
Oh, no do not use context that way. A simple sleep would have been enough.

The missing part in client code was still closing the context, as it releases machine resources. This part is quite mandatory unless you want to be forced to regularly reboot your computer.
But the critical point for sending was that client was sending and shutting down straight away, thus leaving no chance to actually send it on the wire.
 
But, at the end of the life of the client, closing the context with a -1 linger will ensure waiting until all remaining messages have been sent.
I hope I did not send contradictory signals here: closing the context is not a necessary step to send your messages.
