### ISSUE TITLE
Ctx tries to close sockets that are not listed in ZContext anymore

### ISSUE THREAD

**Issue by MoeweX** [zeromq/jeromq#595]
Hi,

I have the problem that my code hangs when calling `context.destroy()` (context is a ZContext). I made sure that the only part of ZeroMQ I access concurrently is this very ZContext.

When closing my sockets, I wait until `context.getSockets()` returns an empty list before calling `context.destroy()`. However, Ctx has still one [pending connection](https://github.com/zeromq/jeromq/blob/54396e9957d77400b08b11c1f1ff24e48956df06/src/main/java/zmq/Ctx.java#L222), and [sockets](https://github.com/zeromq/jeromq/blob/54396e9957d77400b08b11c1f1ff24e48956df06/src/main/java/zmq/Ctx.java#L241) also contains one socket. 

The code than finally hangs at the [reveive](https://github.com/zeromq/jeromq/blob/54396e9957d77400b08b11c1f1ff24e48956df06/src/main/java/zmq/Ctx.java#L256).

So I wonder, why does `context.getSockets()` return an empty list and how do I prevent the hang?

Quick note: I use the latest stable release, 0.4.3.

**Comment by fredoboulo** [comment]
Hi,

do you have some simple code to demonstrate the issue?

Do you use any shadow context? What is the type of the socket that is not closed?

**Comment by MoeweX** [comment]
Hi, sorry for the late response, I am currently traveling. The socket is a dealer socket, and I should mention that I think I only have this problem when I create two dealer sockets that try to  connect to the same router socket, which I do not create. So In other words, I try to start two dealer sockets, and shut them down again, without a router socket that is bind to the dealer sockets’ target port .

**Comment by fredoboulo** [comment]
Ok, I think I get it, please tell me if I'm missing something.

You are connecting 2 INPROC dealer sockets, and there is no router in the bind side.
And when closing the context, one of the 2 connecting sockets is still in "pending mode" and not closed, thus making the context wait forever.

If that is so, there is a problem in the code handling pending connections. I can make a PR about that. A workaround with the current release would be to fall back in the previous behaviour of ZMQ, where users need to bind THEN connect the inproc sockets.
If that's not it, please tell us so we can move forward on the topic.

**Comment by MoeweX** [comment]
Yes! Exactly that is the issue, you described it perfectly.

**Comment by MoeweX** [comment]
Hi, I can confirm, that the issue is resolved, thanks!
