### ISSUE TITLE
ZMQ.Socket send doesn't work properly

### ISSUE THREAD

**Issue by yleyvag** [zeromq/jeromq#613]
I have this piece of code. When I try with two devices I can send messages from on device to the other one. But then I disconnect one of them and I try to send a message again. The socket.send(...) method stills returning true, and there's no way to know if some exception happened and the message couldn't be delivered. I need to be sure the message was sended correctly, otherwise I need to send it again or store it and send it latter.

```
String message = "hello";
ZMQ.Context context = ZMQ.context(1);
ZMQ.Socket socket = context.socket(ZMQ.REQ);
socket.connect("tcp://" + ipAddress + ":28005");
socket.send(message.getBytes(), 0);
socket.close();
context.term();
```

**Comment by daveyarwood** [comment]
In the ZMQ model, when you send a message, it gets put onto an internal queue waiting for the recipient to receive it. So like you mentioned, you really have no idea if it gets delivered successfully or not.

This is actually an inherent problem that needs to be handled when you're working with distributed systems. You can never assume that a message reaches where it's supposed to go, so you just have to handle that scenario in your code.

Does that help?

**Comment by yleyvag** [comment]
Sorry but this doesn't help me. I'm programming a message queue and I need to be sure if the message was correctly delivered, if not, as I told before, I need to store that message and send it again latter when it become possible.
On the tests I made the messages that wasn't sended never were delivered when the connection became available.
So, how can I be sure that the message wasn't delivered? if I don't receive any message or exception.

**Comment by daveyarwood** [comment]
ZMQ is low-level in the sense that it doesn't try to handle these things for you. Instead, it gives you the building blocks you need to build architectures that can handle these points of failure like messages not being delivered.

The zguide has some very good guidance on how to build systems that are reliable. You might find [this section](http://zguide.zeromq.org/page:all#Chapter-Reliable-Request-Reply-Patterns) useful, in particular.

From the code you posted, it seems like you are asking about the client side of a request/reply connection. The ["lazy pirate pattern"](http://zguide.zeromq.org/page:all#Client-Side-Reliability-Lazy-Pirate-Pattern) described in this section of the zguide can help you there. Basically, you keep checking to see if there's been a reply until a timeout elapses, at which point you retry the request.

**Comment by yleyvag** [comment]
Thank you. That's really good. But I noticed there's a difference between method ZMQ.poll(...) provided by jeromq and the example on http://zguide.zeromq.org/java:lpclient. ZMQ.poll(...) on jeromq expects three parameters poll(Selector selector, PollItem[] items, long timeout) otherwise the example expects two poll(PollItem[] items, long timeout)

**Comment by daveyarwood** [comment]
The Java examples in the zguide are out of date for what we're doing with JeroMQ. This is partially because the JeroMQ API has diverged from jzmq.

At any rate, see the corresponding [zguide examples in this repo](https://github.com/zeromq/jeromq/tree/master/src/test/java/guide) for recommended usage of JeroMQ.
