### ISSUE TITLE
ZMQ.poll  cpu 100%

### ISSUE THREAD

**Issue by lsk569937453** [zeromq/jeromq#615]
```
"Thread-2" Id=14 RUNNABLE
    at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
    -  locked sun.nio.ch.Util$2@7433a0f1
    -  locked java.util.Collections$UnmodifiableSet@698b69d0
    -  locked sun.nio.ch.EPollSelectorImpl@3fd00cd2
    at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
    at zmq.ZMQ.poll(ZMQ.java:705)
    at zmq.ZMQ.poll(ZMQ.java:618)
```

This is my code 

```java
PollItem[] items = new PollItem[ZmqConfig.ZMQ_POLLITEM_SIZE];
items[ZmqConfig.ZMQ_FRONTEND_POLLIN] = new PollItem(frontend.base(), zmq.ZMQ.ZMQ_POLLIN);
items[ZmqConfig.ZMQ_BACKEND_POLLIN] = new PollItem(backend.base(), zmq.ZMQ.ZMQ_POLLIN);
PollItem[] itemsout = new PollItem[ZmqConfig.ZMQ_POLLITEM_SIZE];

itemsout[ZmqConfig.ZMQ_FRONTEND_POLLOUT] = new PollItem(frontend.base(), zmq.ZMQ.ZMQ_POLLOUT);
itemsout[ZmqConfig.ZMQ_BACKEND_POLLOUT] = new PollItem(backend.base(), zmq.ZMQ.ZMQ_POLLOUT);

Selector selector = ctx.createSelector();

while (!Thread.currentThread().isInterrupted()) {
  //  Wait while there are either requests or replies to process.
  zmq.ZMQ.poll(selector, items, ZmqConfig.ZMQ_MSG_POLLIN_TIMEOUT);

  if (frontend != backend) {
    zmq.ZMQ.poll(selector, itemsout, ZmqConfig.ZMQ_MSG_POLLOUT_TIMEOUT);
  }
```

The result is that  the application was blocked in the zmq.ZMQ.poll and  the cpu is 100%.It is likely that the application was hang and could not accept any  request.

**Comment by daveyarwood** [comment]
I don't understand this line:

```java
if (frontend != backend)
```

I assume these are two sockets? Aren't they always not equivalent to each other because they are different objects?

It's also worth pointing out that this type of low-level usage of `PollItem` and `zmq.ZMQ.poll` is not recommended. There are higher-level constructs in the org.zeromq package that are more reliable as they handle the lower-level things properly for you. See the [mspoller](https://github.com/zeromq/jeromq/blob/master/src/test/java/guide/mspoller.java) example for the recommended way to do polling with JeroMQ.

**Comment by fredoboulo** [comment]
Hi @lsk569937453 did you try with the lastest SNAPSHOT? Fixes where committed in that area after the 0.4.3 release.

**Comment by milosonator** [comment]
> Hi @lsk569937453 did you try with the lastest SNAPSHOT? Fixes where committed in that area after the 0.4.3 release.

Do you mean `0.4.4-SNAPSHOT` or `0.5.0-SNAPSHOT`? I can't seem to find `0.5.0-SNAPSHOT` in the sonatype snapshot repository.

**Comment by trevorbernard** [comment]
@milosonator if you clone the latest snapshot of JeroMQ, you can simply `mvn install` and `0.5.0-SNAPSHOT` will be installed in your .m2 repository cache.

**Comment by milosonator** [comment]
@trevorbernard Thanks, that will work for local development, so I can try it. (We can't then run our CI against it, though).

**Comment by daveyarwood** [comment]
I'm going to assume that the issue has been fixed, given what @fredoboulo said above and the fact that this issue was created 1-1/2 years ago.

Feel free to open if the issue persists in the latest release version.
