### ISSUE TITLE
Problem: pollTestTcp is flakey

### ISSUE THREAD

**Issue by trevorbernard** [zeromq/jeromq#621]
`server.accept()` returns null when it's non-blocking mode (which it appears to be) and when no connection is available to be accepted

**Comment by fredoboulo** [comment]
I assume you refer to PollTest#testPollTcp

Would changing the mode to be blocking solve the flakiness?
Something like
```
ServerSocketChannel server = ServerSocketChannel.open();
assertThat(server, notNullValue());
server.configureBlocking(true);
```
around lines 34-36

**Comment by trevorbernard** [comment]
I briefly tried to turn it off but something else broke down the line in PollTest. I didn't have time to debug it.
