### ISSUE TITLE
ZMQ messages not arriving at destination

### ISSUE THREAD

**Issue by kmualem** [zeromq/jeromq#624]
Hi Guys,

We have a very strange and critical problem that I need your help!
The scenario is that we send a message in client application and for some reason, it didn't arrive to the server application.

- We use version 0.4.3
- In the client application, we use DEALER socket (TCP)
- In the server application, we have a ROUTER socket and Reactor thread that catches the incoming events. 
- In the client application we have one Zcontext and each thread that sends a message from the client creates a shadow socket, creates the DEALER socket, s**end the message to the server and waits 5 sec for ACK message from the server.**

Part of the client code:
`
ZMsg msg = createMessage() ;
msg.send(socket);
socket.setReceiveTimeOut(5000);
response = socket.recvStr(); 
`
In case that we didn't get answer from the server, we assume that there is a network / load issues on the server. **BUT in our case! we don't see the message in the server side at all!**

We have some traffic captures and I need your help in order to understand the problem.
**In a good scenario, we see that the client push data to server:**
C->S [SYN]
S->C [SYN, ACK]
C->S [ACK]
**C->S [PSH, ACK]**
S->C [ACK]
S-C [PSH, ACK]
C->S [ACK]
C->S [PSH, ACK
...
**In a bad scenario, which we don't see traffic in the server and not getting ACK message in the client:**
C->S [SYN]
S->C [SYN, ACK]
C->S [ACK]
**S-C [PSH, ACK]**
C->S [ACK]
 **C->S [RST, ACK]**
The reset from the client is after the timeout of 5 min.. that we didn't get ACK response.
Then, we close the socket in the client with linger 0

Can you please help? 
What can be the reason that the messages don't arrive to the server ?

Thanks!
Kobi.

**Comment by kmualem** [comment]
Hi,
Any news about this issue?
Can someone please review it and help us to understand what can be the reason for the issue that we're facing?

**Comment by daveyarwood** [comment]
Are you seeing this occasionally, or consistently? It's definitely the case that networking is not 100% reliable. Packets can get lost, etc. So you should design your systems in a way that is robust in the face of potentially lost messages, etc.

**Comment by trevorbernard** [comment]
ZeroMQ provides atomic message delivery AKA all or nothing. Unless it's a bug in DEALER/ROUTER sockets, it feels like a symptom of a networking problem. I would ask these sorts of questions on the ZeroMQ mailing, IRC, or StackOverflow.

Providing a minimal test case that recreates the issue goes a long way in helping to diagnose the underlying issue.

**Comment by kmualem** [comment]
The big problem is that this is not consistent and currently I don't have a way to reproduce it... 

We use the ZMQ messaging in multiple components. We use the native jeromq C++ library, the Python binging library, the jeromq for java and currently, it seems like we are not facing such behavior in the other ZMQ libraries.

Do you have an idea how can we prove that this is a networking issue? 
What is the best practice solution for jeromq in such case? when there is no response from the server... should we destroy and re-create the socket and try to send the message again?

**Comment by daveyarwood** [comment]
I would recommend reading chapter 4 of the zguide: [Reliable Request/Reply Patterns](http://zguide.zeromq.org/page:all#Chapter-Reliable-Request-Reply-Patterns). The "lazy pirate" pattern, in particular, is a good one to use for client-side reliability. In a nutshell, you can never assume that a message you send will reach its destination successfully, so you need some sort of retry loop as described in the zguide.

**Comment by kmualem** [comment]
Thanks for the suggestion. We do have some retries mechanism, meaning, we wait for X sec in the client to get a response from the server, BUT, we don't destroy, re-create the socket and send the message again.

For each ZMQ message, we create a new socket, send a message and then closing the socket and the shadow context.
Is it something that could lead us to the described issue? 
I mean, Is it possible that this is not a networking issue, but some other Jeromq problem while creating multiple shadow context and sockets?

Please note that we do see communicate between the client and the server (As described in the tcp dump above) 
C->S [SYN]
S->C [SYN, ACK]
C->S [ACK]
S-C [PSH, ACK]
C->S [ACK]
C->S [RST, ACK]

Do you still think that this is a Networking issue?

**Comment by trevorbernard** [comment]
> For each ZMQ message, we create a new socket, send a message and then closing the socket and the shadow context.

Idiomatic usage are that zeromq sockets are long lived. It's not advisable to be constantly creating and destroying sockets.

> I mean, Is it possible that this is not a networking issue, but some other Jeromq problem while creating multiple shadow context and sockets?

Certainly anything's possible but when getting RST-ACK, it typically means the port you're trying to connect to is unavailable for whatever reason. Which leads me to believe it's a networking issue or simply, your server isn't running. This looks like a TCP thing rather than a zeromq thing.

https://github.com/zeromq/zmtpdump

This tool may or may not help.

**Comment by daveyarwood** [comment]
Destroying the context is probably causing problems for you.

In general, you should create the context at the start of your program and destroy it at the very end.

**Comment by kmualem** [comment]
Ok... So, I added a retries mechanism, I have a loop of 3 retries, In each iteration, I'm destroying the socket and create it again...  **BUT sometimes this is not helpful and I still don't see the messages in the server side!**

When sending the message, I'm waiting 2.5 sec to get a response back from the SERVER (waiting for ACK) in case that there is no response, there is a sleep of 1.5 sec then destory and re-create of the socket.. and send again.

I need your advise again.. I don't understand what is the next step and will appreciate your help.
This is a production environment, so if there will be no solution, unfortunately.. I will have to think about a different messaging framework :(

Thanks.

**Comment by daveyarwood** [comment]
@kmualem Could you post your client and server code? I'm curious about how you're doing the retries.

**Comment by kmualem** [comment]
@daveyarwood  I posted the major part of the client code in one of my comments "12 days ago"

The server code is very straightforward.  There is a Router socket, with PollItem ZMQ.Poller.POLLIN and a reactor ZLoop.
Once we get the message in the pollItem handler, we send ACK to the client.

**Comment by daveyarwood** [comment]
The edited version of your code above looks sensible to me. It sounds like the issue might be on the server side.

Also worth noting: do you absolutely need a shadow context? That could be complicating things. I've never found the need to use a shadow context, FWIW.

**Comment by kmualem** [comment]
Re. the server code, this is more simple than the client...  the thing is that we don't see the messages arrive at the server side at all.  

This is the major part of the server side:
```java

this.router = this.shadowContext.createSocket(ZMQ.ROUTER);
this.router.setRouterMandatory(true);

this.reactor = new ZLoop(this.shadowContext);

PollItem routerPollItem = new PollItem(this.router, ZMQ.Poller.POLLIN);
this.reactor.addPoller(routerPollItem, routerHandler, this);

this.reactor.start();
```

The reason for having the shadow context is because of the multiple threads. My understanding is that each thread that has its own socket should have a shadow context. Using the shadow context the thread creates and destroy the sockets, etc.
Is it wrong?

**Comment by daveyarwood** [comment]
No, it's not necessarily wrong to use a shadow context. I think it probably makes sense to do so in some cases where you have to use multiple threads and you'd like to coordinate shutdown at the end, so that the contexts used in the threads will shut down when the context in the main thread shuts down.

My suspicion is that there's some issue with the ZLoop.

One thing you can try in order to troubleshoot is to use a simpler server that does not use ZLoop, and instead, just runs in a `while` loop and continually receives and prints messages. If this doesn't work, it would point to there being a problem with the client, and if it does work, then it would point to there being a problem with either ZLoop or the way you're using ZLoop.

**Comment by kmualem** [comment]
Re. the suspicion in the server side / ZLoop... I will have to think about how to fully change the ZLoop code that I have now on the server side because I have multiple sockets on the same reactor and I'm also using Timer.

Did you read the TCP dump messages above? from the dump it seems like the client does not send the data for some reason, more client side issue than server side.
But, if you still think that there might be some problem on the server side, I will try to change the ZLoop...

**Comment by daveyarwood** [comment]
I'm just grasping for straws here... the problem could very well be on the client side, for all we know. I was only speaking to the way the code looks to my eyes and what I know about JeroMQ. I don't see anything obviously wrong with the client code, and I've never used ZLoop (and ZLoop is a higher level abstraction, which could be hiding something going wrong at a lower level), so I think going down a level on the server side might help us rule out whether this is an issue on the server side or the client side.

**Comment by daveyarwood** [comment]
To the point about handling multiple sockets: have you tried polling? [mspoller](https://github.com/zeromq/jeromq/blob/master/src/test/java/guide/mspoller.java) is a good example of how to do polling with JeroMQ.

**Comment by kmualem** [comment]
Thanks @daveyarwood 
I will review the example and will try to write some code as a replacement for the existing server ZLoop.

It will take me some to write it and to check it on our environment, So I will update once I will have more details, of course.

**Comment by lukcn** [comment]
I think we've managed to reproduce this issue (the commit above).

From analyzing the traffic it seems that ZMQ handshake sometimes hangs in the middle. We can observe the same pattern as @kmualem:
```
C->S [SYN]
S->C [SYN, ACK]
C->S [ACK]
S-C [PSH, ACK]
C->S [ACK]
C->S [RST, ACK]
```
Please notice that first 3 lines are part of TCP handshake, which seems to be completed successfully. Next 2 lines are part of ZMQ handshake. Please notice that it's a client who does not send his part of the handshake.

It looks to me as a race condition. I don't know implementation details, but I have a feeling that client queues the ZMQ handshake messages, but they never got sent (until some other event cause them to be sent/flushed, i.e. recv timeout?).

Two additional observations:
1) since communication hangs in the middle of ZMQ handshake, then adjusting maximum handshake interval via `setHandshakeIvl` seems to help (unless at the same time `setImmediate(false)` will also be set)
2) it seems that `setImmediate(false)` considers connection to be completed before ZMQ handshake is completed (shouldn't it be after?)
