### ISSUE TITLE
socket close crash 

### ISSUE THREAD

**Issue by mozeat-sun** [zeromq/jeromq#625]
hi
   i have a problem with socket close. 
   there are two type socket which zmq_poll in a thread.one socket controls loop quit.another is process events.
   when call shutdown interface,the program crash :
        "terminate called after throwing an instance of 'zmq::error_t'
           what():  Socket operation on non-socket
         Aborted (core dumped)"

   part code as bellow:

   CLIENT_MODEL_CLASS::CLIENT_MODEL_CLASS()
    :m_context(1)
    ,m_subscriber(m_context,ZMQ_SUB)
    ,m_sender(m_context,ZMQ_DEALER)
    ,m_pusher(m_context,ZMQ_PUSH)
    ,m_shutdown_watcher(m_context,ZMQ_PAIR),m_bind_state(false)
    {
        this->m_recv_flag = ZOO_TRUE;
        this->m_send_flag = ZOO_FALSE;
    }

    void CLIENT_MODEL_CLASS::connect_to_server(const std::string server_name)
    {
        this->m_subscriber.setsockopt(ZMQ_SUBSCRIBE,"",0);
        this->m_subscriber.connect(this->m_ps_server);
        this->m_shutdown_watcher.bind(this->get_shutdown_server_address(server_name));
    }
   void CLIENT_MODEL_CLASS::loop_event(void)
    {
        zmq::pollitem_t items [] = {{ this->m_subscriber, 0, ZMQ_POLLIN, 0 },
                                    { this->m_shutdown_watcher, 0, ZMQ_POLLIN, 0 }};
        __MQ_EVENT_LOOP_BEGIN
        {
            zmq::poll(&items[0], 2, -1);

             /**
             * @brief listen message from publish server
             */
            if(items[0].revents & ZMQ_POLLIN)
            {
                CALLBACK_CONTEXT_STRUCT context = CALLBACK_CONTEXT_STRUCT();
                this->receive_callback_context(this->m_subscriber,context);
                this->check_has_subscribed(context);
                this->execute_callback_function(context);
            }

            /**
             * @brief shutdown listen server
             */
            if(items[1].revents & ZMQ_POLLIN)
            {
                std::cout << "shutdown :" << this->m_server_name << " ..." << std::endl;
                break;
            }
        }
        __MQ_EVENT_LOOP_END
	std::cout << "shutdown :" << this->m_server_name << " ..." << std::endl;
    }
void CLIENT_MODEL_CLASS::shutdown()
    {
	try
	{
		if(this->m_bind_state)
		{
		    std::cout << "CLIENT_MODEL_CLASS::shutdown() >" << std::endl;
		    std::string shutdown("shutdown");
		    zmq::message_t message(shutdown.size());
		    memcpy(message.data(),shutdown.data(),shutdown.size());
		    zmq::socket_t requester(m_context,ZMQ_PAIR);
		    requester.connect(this->get_shutdown_server_address(this->m_server_name));
		    requester.send(message);
		    this->m_bind_state = false;
		    requester.close();
		}
		sleep(2);
		this->m_subscriber.close();
		this->m_shutdown_watcher.close();// always crash here ???
		this->m_context.close();
	}
	catch(...)
	{
	}
        std::cout << "CLIENT_MODEL_CLASS::shutdown() <" << std::endl;
    }

       //initiliaz like this some where ....
       this->connect_to_server(server_name);
        this->m_thread.reset(new std::thread(std::bind(&CLIENT_MODEL_CLASS::loop_event,this)));

**Comment by mozeat-sun** [comment]
anyone who can help me to figure out what's the problem? thanks.

**Comment by daveyarwood** [comment]
@mozeat-sun This looks like C++ code. I assume you are using [libzmq](https://github.com/zeromq/libzmq), not jeromq?

**Comment by trevorbernard** [comment]
This is libzmq and not jeromq. I would ask StackOverflow, IRC, or the ZeroMQ mailing list.
