### ISSUE TITLE
ZBeacon uses "final byte[]" for beacon data

### ISSUE THREAD

**Issue by kylemallory** [zeromq/jeromq#626]
I would like to be able to update the beacon data on the fly, without tearing down the entire ZBeacon instance.  I noticed that the beacon data in ZBeacon is declared "final" and am curious if there is a particular reason for this that isn't currently clear to me.

**Comment by daveyarwood** [comment]
cc: @c-rack

**Comment by trevorbernard** [comment]
There is no real reason. Also the bytes passed in are copied by reference so the final doesn't really make much sense. I would just submit a PR to remove the final.

**Comment by kylemallory** [comment]
Cool.  I'll start pulling one together.
