### ISSUE TITLE
Need XPub support token based authentication

### ISSUE THREAD

**Issue by JingchengLao** [zeromq/jeromq#628]
Hi guys,

Currently we use ZeroMQ for a project with JeroMQ as server side and NetMQ as client side.
Everything works perfectly and now we need consider security, however NetMQ goes a different way and it doesn't support CURVE. As checked the source code of handshake part, it seems only support ZMTP 1.0.
Ref: 
https://github.com/zeromq/netmq/issues/75

The author suggested to have token based authentication as a solution which is lower security but better than nothing.
Ref: 
https://github.com/zeromq/netmq/issues/620
https://somdoron.com/2014/12/token-pubsub/

For this situation, do you have any solutions?

BTW, as a quick solution, we extend JeroMQ in fork copy to add XTPub socket to support token based authentication.
https://github.com/JingchengLao/jeromq

Do you think if it is right direction?

Many thanks

**Comment by trevorbernard** [comment]
No, I don't believe this is the right direction for JeroMQ. In lieu of security support in netmq, I would just tunnel zeromq over TLS if you want to secure it over the wire.

**Comment by JingchengLao** [comment]
TLS solution is not working for NetMQ so far. 

https://groups.google.com/forum/#!topic/netmq-dev/9iBp48v942A
https://somdoron.com/2013/05/securing-netmq/

Please correct me if I am wrong.
Thanks

**Comment by JingchengLao** [comment]
FYI:
I found a similar question from NetMQ issue list:
https://github.com/zeromq/netmq/issues/762

**Comment by trevorbernard** [comment]
@JingchengLao I was referring to using something like stunnel on top of zeromq. I'm not knowledgable about netmq's security, but until netmq supports https://rfc.zeromq.org/spec:23/ZMTP/ and https://rfc.zeromq.org/spec:25/ZMTP-CURVE, there really isn't anything JeroMQ can do about it.

Also, I would suggest asking these types of questions on StackOverflow, IRC, or the ZeroMQ mailing list for help and advice.
