### ISSUE TITLE
Set up Travis CI to test Android SDK versions

### ISSUE THREAD

**Issue by daveyarwood** [zeromq/jeromq#629]
Spun off of #472.

@fredoboulo:

> Right now the code is compatible with Android API level 10. The thing is that JDKs are not fully implemented depending on the versions (some classes, some methods are missing depending on this level). Is it possible to setup Travis so we can at least run a compilation of the project on Android environment ([distribution of devices is here](https://developer.android.com/about/dashboards/index.html))?

@daveyarwood:

> Re: Travis CI for Android, it looks like that ought to be fairly easy to set it up so that we run the build and tests on a variety of Android SDK versions: https://docs.travis-ci.com/user/languages/android/

**Comment by fredoboulo** [comment]
Especially that now we are using Java 8, which is not fully supported in Android. That would help to clarify the situation.

**Comment by daveyarwood** [comment]
Closed via #711, as well as several subsequent PRs where we've made improvements to the Travis Android build.
