### ISSUE TITLE
Connect jeromq-jms subscriber to zeroMQ Publisher

### ISSUE THREAD

**Issue by mueller-jens** [zeromq/jeromq#636]
I am trying to connect a jms based subscriber to a plain ZeroMQ Publisher. But the subscriber does not recive any message. Is there any way to achive this?

Publisher:

        Context context = ZMQ.context(1);

        final Socket publisherSocket = context.socket(ZMQ.PUB);

        publisherSocket.bind("tcp://*:9714");
        Thread t = new Thread(() -> {
            while (true) {

                // Write two messages, each with an envelope and content
                publisherSocket.sendMore("evt");
                publisherSocket.send("TestEvent");

            }

JMS Template configuration:

      final JmsTemplate template = new JmsTemplate();

        template.setPubSubDomain(true);
        template.setConnectionFactory(connectionFactory());
        template.setDefaultDestinationName(getPubServerUri(null));
        template.setPubSubNoLocal(false);
        template.setReceiveTimeout(100);
        return template;

  ```
 private TopicConnectionFactory connectionFactory() {

        final TopicConnectionFactory connectionFactory = new ZmqConnectionFactory(
                new String[] { getPubServerUri(null)});

        return connectionFactory;
    }


    private ConnectionFactory connectionFactory() {

        final ConnectionFactory connectionFactory = new ZmqConnectionFactory(
                new String[] { getPubServerUri(null)});

        return connectionFactory;
    }

   private String getPubServerUri(ZMQ_CHANNEL channel)
    {
        return "jms:topic:all?gateway.addr=tcp://*:9714&socket.addr=tcp://*:9714";
    }
```

Subscriber:

               System.out.println(jmsTemplate.receiveAndConvert());

**Comment by Ma0110** [comment]
Hello, is your problem solved? I also have a similar problem. I want to use the PC as the publisher and the Android app as the subscriber. Then I want to use Zmq and Jmq to complete this work. I don't know if it will work.
