### ISSUE TITLE
A System.out usage

### ISSUE THREAD

**Issue by fbacchella** [zeromq/jeromq#639]
In line : https://github.com/zeromq/jeromq/blob/7d53a816e65e0a0243c69bd7a005a11c6ae1831f/src/main/java/zmq/io/mechanism/Mechanism.java#L337

It can't be deactivated.

**Comment by fredoboulo** [comment]
ah yes, these prints were on libzmq 4.1.7. They could be removed. Feel free to propose a PR for that!
