### ISSUE TITLE
wrong assert in curve mechanism

### ISSUE THREAD

**Issue by fbacchella** [zeromq/jeromq#641]
I think this line https://github.com/zeromq/jeromq/blob/7d53a816e65e0a0243c69bd7a005a11c6ae1831f/src/main/java/zmq/io/mechanism/curve/CurveClientMechanism.java#L61
matches issue #605.

If someone set the private key but forget to set the public key, I'm afraid this line will throw a dirty exception. See [Options.setCurveKey](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/Options.java#L600). Setting either public or private key is enough to activate a call to Curve mechanism.

**Comment by fredoboulo** [comment]
That's a good finding!
I would keep the assert there, changing it to a pre-condition checking would result in another exception in a thread that is out of reach of the users. Maybe check these preconditions during bind and connect could allow better feedback to the calling code.

**Comment by fbacchella** [comment]
Close as PR was merged.
