### ISSUE TITLE
Jeromq snapshots are not published

### ISSUE THREAD

**Issue by fbacchella** [zeromq/jeromq#644]
Issue #325 is back but for 0.5.0, see https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/

**Comment by fbacchella** [comment]
As I really needed a snaphost publication, I made my own:
https://oss.sonatype.org/service/local/repositories/snapshots/content/fr/loghub/jeromq/0.5.0-SNAPSHOT/

**Comment by daveyarwood** [comment]
We really ought to automate this. I can look into this myself, but first I'm lacking some general info about how JeroMQ artifacts are deployed. Will ping @trevorbernard in #384.

**Comment by fbacchella** [comment]
I've automated this in this branch: https://github.com/fbacchella/jeromq/tree/publishing
I've switch from travisci to circleci, because travis is slow and unreliable.

**Comment by trevorbernard** [comment]
@fbacchella re: travisci - I agree. I was in the middle of configuring circleci but I see you've already done that in your branch. Submit a PR and I'll get it configured in master

**Comment by fbacchella** [comment]
My setup is now quite ready. It can only publish snapshots, and dont handle PR well. I will need to find a way to disable mvn deploy for PR. Without that all PR will fails.
And publish of release is still an open problem.

**Comment by trevorbernard** [comment]
We're going to release `v0.5.0` shortly then we'll go on to solve the snapshot problem. I'll evaluate bintray with regards to managing the credentials/tokens/keys for the oss sonatype as I'm generally wary with 3rd parties keeping my secrets safe.

**Comment by fbacchella** [comment]
I have upgraded the build using circleci and sonarcloud. It should detect PR and not publish them, to avoid error. It also publish sonar cloud report to https://sonarcloud.io/dashboard?id=fr.loghub%3Ajeromq.
The branch were I put my publishing tweaks is here: https://github.com/fbacchella/jeromq/tree/publishing.
circle build reports: https://circleci.com/gh/fbacchella/jeromq.
The snapshot are published in the same place than the previous one: https://oss.sonatype.org/content/repositories/snapshots/fr/loghub/jeromq/

**Comment by somdoron** [comment]
Any update on this? I can help set up an automatic release (travis or github actions?) on every commit to the snapshots repository. 
I would need someone to configure the secrets with the credentials to the snapshots repository.

**Comment by fbacchella** [comment]
I'm working on it. I discuss it in issue #780

**Comment by trevorbernard** [comment]
Thanks to @fbacchella CircleCi work, we publish the snapshots on a successful build
