### ISSUE TITLE
Too much final in PollItem ?

### ISSUE THREAD

**Issue by fbacchella** [zeromq/jeromq#648]
Why all the public method  in PollItem are final ?
https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/poll/PollItem.java.
It's not very common in jeromq and some was removed in #446.
I don't plan to have a custom implementation, I just wanted to debug some code and wrapping method with custom check.
Will you accept a PR to remove them ?

**Comment by trevorbernard** [comment]
Jeromq follows https://rfc.zeromq.org/spec:44/C4/. As long as it follows what a good patch is, we'll always merge it.

**Comment by fbacchella** [comment]
Created PR #651
