### ISSUE TITLE
Multiple register in ZPoller fails

### ISSUE THREAD

**Issue by fbacchella** [zeromq/jeromq#649]
I tried to do multi-register of call back in ZPoller, each time with a different context.

So I wrote the following test code:

```java
    @Test
    public void testChannel() throws IOException
    {
        Selector s = Selector.open();
        AtomicInteger count = new AtomicInteger();
        AtomicInteger error = new AtomicInteger();

        EventsHandler cb1 = new EventsHandler() {

            @Override
            public boolean events(Socket socket, int events) {
                throw new UnsupportedOperationException("Not registred for Socket");
            }

            @Override
            public boolean events(SelectableChannel channel, int events) {
                assert (events & ZPoller.IN) > 0;
                try {
                    Pipe.SourceChannel sc = (Pipe.SourceChannel) channel;
                    sc.read(ByteBuffer.allocate(5));
                    count.incrementAndGet();
                    return true;
                } catch (IOException e) {
                    return false;
                }
            }

        };
        EventsHandler cb2 = new EventsHandler() {

            @Override
            public boolean events(Socket socket, int events) {
                throw new UnsupportedOperationException("Not registred for Socket");
            }

            @Override
            public boolean events(SelectableChannel channel, int events) {
                assert (events & ZPoller.IN) > 0;
                try {
                    Pipe.SourceChannel sc = (Pipe.SourceChannel) channel;
                    sc.read(ByteBuffer.allocate(5));
                    count.incrementAndGet();
                    return true;
                } catch (IOException e) {
                    return false;
                }
            }

        };
        EventsHandler cberr = new EventsHandler() {

            @Override
            public boolean events(Socket socket, int events) {
                throw new UnsupportedOperationException("Not registred for Socket");
            }

            @Override
            public boolean events(SelectableChannel channel, int events) {
                error.incrementAndGet();
                return false;
            }

        };

        try (ZPoller poller = new ZPoller(s)) {
            Pipe pipe1 = Pipe.open();
            Pipe.SourceChannel source1 = pipe1.source();
            source1.configureBlocking(false);
            poller.register(source1, cb1, ZPoller.IN);
            poller.register(source1, cb2, ZPoller.IN);
            poller.register(source1, cberr, ZPoller.ERR);

            Pipe pipe2 = Pipe.open();
            Pipe.SourceChannel source2 = pipe2.source();
            source2.configureBlocking(false);
            poller.register(source2, cb1, ZPoller.IN);
            poller.register(source2, cb2, ZPoller.IN);
            poller.register(source2, cberr, ZPoller.ERR);

            pipe1.sink().write(ByteBuffer.wrap(new byte[] {1,2,3}));
            pipe2.sink().write(ByteBuffer.wrap(new byte[] {1,2,3}));
            while (poller.poll(100) > 0) {
                
            }
            assertThat("Not all events handlers checked", count.get(), is(equalTo(2)));
            assertThat("Not all events handlers checked", error.get(), is(equalTo(0)));
        }
    }
```
It creates two generic call back, and one error callback.
It creates two pair of SelectableChannel, register each call back for each and wrote data in each.
The AtomicInteger count check how many time at least one of the generic callback was called.

We can expect a value of :
 - 2 once data was read in a channel, the next callback is not called in the same poll.
 - 4 once data was read in a channel, the next callback is still read during the same poll, even if there is not any more data to read.

But the test fails with a value of 1. The least expected value.

Am I doing something wrong ? Or is that a bug ?

**Comment by fredoboulo** [comment]
This is what I understand: The counter should return 2. 

ZPoller is using zmq.ZMQ.poll internally. With your code, the implementation will register the channel with the current selector several times (one per each poll item created by each call to register() in ZPoller), the last one will overwrite all previous interestOps. 
If the last one is the handler for errors, you will receive nothing, as there is no operation for error in selection keys.
It's technically possible to register multiple times a channel but this is not the way it works. We should protect code from such multiple registrations (that would also make the code simpler). Same problem within zmq.ZMQ.poll ATM.

**Comment by fbacchella** [comment]
If the last register for error override all registration for the channel, why I didn't get 0 ? I have two channel with exactly the same registration. So I should only get an even value.

More, I have another problem.

If I run this code from eclipse, it fails:
```
java.lang.AssertionError: Not all events handlers checked
Expected: is <2>
     but: was <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.zeromq.TestZPoller.testChannel(TestZPoller.java:477)
....
```
But I got success from maven:
```
$ JAVA_HOME=$(/usr/libexec/java_home -v 1.8) mvn clean package site
...
Results :

Tests run: 491, Failures: 0, Errors: 0, Skipped: 14
...
$ cat target/surefire-reports/TEST-org.zeromq.TestZPoller.xml
<testsuite tests="12" failures="0" name="org.zeromq.TestZPoller" time="0.141" errors="0" skipped="0">
...
  <testcase classname="org.zeromq.TestZPoller" name="testChannel" time="0.103"/>
...
``

**Comment by fredoboulo** [comment]
I got different results on my machine.
Counter is:
 - 1 when running testChannel method alone
 - 2 when running the class (I added the method in TestZPoller)
 - 0 when running via maven.

It means to me the behaviour of the test is unpredictable and non repeatable.
Internally, all PollItems are put in a Set then in an array: the order of the items is undefined.

I'd rather focus now on how to prevent user doing multiple registrations on the same channel.

**Comment by fbacchella** [comment]
I replaced all the Set usage in ZPoller by List and got a consistent result: 0 or 2, depending of the order of the declaration.
But  if only one registration for each channel or socket is allowed, why the following declaration in ZPoller :
```
    private final Map<Object, List<ItemHolder>> items;
``` 

A simple  Map<Object, ItemHolder > items will provide the same functionnality, and a check will reject multiple declaration in add(Object socketOrChannel, final ItemHolder holder).

**Comment by fredoboulo** [comment]
Implementation is half-way towards what you are suggesting: multiple registrations should be possible. I will propose a PR for that possibility. It sounds more interesting than restricting the usage to a single registration per socket or channel.
