### ISSUE TITLE
Problem: testConnectDelay randomly fails

### ISSUE THREAD

**Issue by trevorbernard** [zeromq/jeromq#669]
Port solution from libzmq

https://github.com/zeromq/libzmq/commit/1a5937750c0f6080c3fefe64f611c1a427048dc9

> Solution: use a monitor to wait for a disconnect instead of a sleep,
and retry to send a message until it fails since the state machine
might be delayed due to the I/O thread being pre-empted on busy
systems.
Also set a receive timeout to avoid random hangs.

**Comment by fbacchella** [comment]
Might be fixed in PR #689

**Comment by daveyarwood** [comment]
It looks like this was fixed by #689.
