### ISSUE TITLE
Problem: TestTermEndpoint randomly fails

### ISSUE THREAD

**Issue by trevorbernard** [zeromq/jeromq#670]
This is related to https://github.com/zeromq/jeromq/issues/669

The same solution applies. Term is an async process on sleeps don't suffice.

>Solution: use a monitor to wait for a disconnect instead of a sleep,
and retry to send a message until it fails since the state machine
might be delayed due to the I/O thread being pre-empted on busy
systems.
Also set a receive timeout to avoid random hangs.

**Comment by fbacchella** [comment]
Perhaps some CountDownLatch could be helpfull.

**Comment by fbacchella** [comment]
Might be fixed in PR #689

**Comment by daveyarwood** [comment]
It looks like this was fixed by #689.
