### ISSUE TITLE
Socket leaks

### ISSUE THREAD

**Issue by fbacchella** [zeromq/jeromq#678]
This line (https://github.com/zeromq/jeromq/blob/7f476dd5c8715cb3aec36e88a0cacdd0cc48d5d7/src/main/java/zmq/io/net/tcp/TcpConnecter.java#L263
)

generate a leak of unfinished TCP socket. It open a socket that is not used neither closed, so it eats all file descriptor. I'm finished to test this hypothesis and will generate a PR for that correction. I think a 0.5.1 will be needed soon, as it can kill service quite fast in some conditions, for example when associated with issue #676.

**Comment by daveyarwood** [comment]
It does look like at least _some_ code path could possibly be closing the socket at some point, when `TcpConnector#close` gets called ( https://github.com/zeromq/jeromq/blob/7f476dd5c8715cb3aec36e88a0cacdd0cc48d5d7/src/main/java/zmq/io/net/tcp/TcpConnecter.java#L357 ), so it's a bit complicated.

Have you looked for invocations of `TcpConnector#close`?

**Comment by fbacchella** [comment]
The problem is that one socket is always open using `fd = SocketChannel.open();`
But if you look at the following if clause:
```
        //  Create the socket.
        if (options.selectorChooser == null) {
            fd = SocketChannel.open();
        }
        else {
            fd = options.selectorChooser.choose(resolved, options).openSocketChannel();
        }
```
Another socket channel is always open, the first is gone, but never closed !

And to add insult to injury, it was my PR #614 that add this bug.

**Comment by daveyarwood** [comment]
Aha, yes! Good find, even if you were the one who perpetrated it! :smile:
