### ISSUE TITLE
Bug in zmq.Msg.getBytes(int, byte[], int, int)

### ISSUE THREAD

**Issue by Cyboot** [zeromq/jeromq#682]
In the Method zmq.Msg.getBytes(int, byte[], int, int) there is a Bug. Instead of writing into the given buffer, the given buffer is actually written into a internal buffer.

`dup.put()` should be replaced by `dup.get()`
![grafik](https://user-images.githubusercontent.com/2717515/53750718-d925b400-3eaa-11e9-8cfa-83291c462103.png)

**Comment by trevorbernard** [comment]
There also appears to be a bounding issue for count

**Comment by trevorbernard** [comment]
That is a such an awkward function. It seems to only work for 0 index values
