### ISSUE TITLE
Zconfig, and so ZCert silently erase config file.

### ISSUE THREAD

**Issue by fbacchella** [zeromq/jeromq#690]
If you like at https://github.com/zeromq/jeromq/blob/master/src/main/java/org/zeromq/ZConfig.java#L229, one can see that if a config file already exists, it's silently deleted.

It's a very dangerous comportment, as it can destroy data without warning or check.It should at least be an option.

**Comment by fredoboulo** [comment]
That's roughly the same behaviour as C++ equivalent: https://github.com/zeromq/czmq/blob/master/src/zconfig.c#L495
Users still have the opportunity to use save(Writer).

**Comment by fbacchella** [comment]
But is that a sensible default  option for curve key ?

**Comment by fredoboulo** [comment]
I would vote for adding a save(Writer) method in ZCert and deprecate or at least document the overwriting behaviour in save(String) when it describes a filename.

**Comment by fredoboulo** [comment]
Thinking of it, I would not deprecate the method and rather document the behaviour.
