### ISSUE TITLE
Context termination fails in camel-zeromq

### ISSUE THREAD

**Issue by mbe24** [zeromq/jeromq#699]
I have created a small Apache Camel example, that uses the camel-zeromq component. JeroMQ is configured as ZMQ implementation. 

There is following IllegalStateException when the context is terminated:

> 2019-03-24 18:52:23.676 ERROR 28923 --- [ - ShutdownTask] o.a.camel.component.zeromq.Listener : Could not terminate context during stop() [{}]
> 
> java.lang.IllegalStateException: null
> at zmq.Ctx.terminate(Ctx.java:198) ~[jeromq-0.4.0.jar:na]
> at org.zeromq.ZMQ$Context.term(ZMQ.java:316) ~[jeromq-0.4.0.jar:na]
> at org.apacheextras.camel.component.zeromq.Listener.stop(Listener.java:130) ~[camel-zeromq-2.22.0.jar:2.22.0]
> at org.apacheextras.camel.component.zeromq.ZeromqConsumer.doStop(ZeromqConsumer.java:63) [camel-zeromq-2.22.0.jar:2.22.0]
> at org.apache.camel.support.ServiceSupport.stop(ServiceSupport.java:119) [camel-core-2.23.1.jar:2.23.1]
> at org.apache.camel.util.ServiceHelper.stopService(ServiceHelper.java:142) [camel-core-2.23.1.jar:2.23.1]
> at org.apache.camel.impl.DefaultShutdownStrategy.shutdownNow(DefaultShutdownStrategy.java:381) [camel-core-2.23.1.jar:2.23.1]
> at org.apache.camel.impl.DefaultShutdownStrategy$ShutdownTask.run(DefaultShutdownStrategy.java:577) [camel-core-2.23.1.jar:2.23.1]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_40]
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_40]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
> at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]

The question is also on [StackOverflow](https://stackoverflow.com/q/55327518/1809463), the example project can be found [here](https://github.com/mbe24/camel-jeromq).

**Comment by fredoboulo** [comment]
https://github.com/camel-extra/camel-extra/blob/master/components/camel-zeromq/src/main/java/org/apacheextras/camel/component/zeromq/Listener.java#L130

The listener class tries to terminate the context, while a socket is being operated in another thread.
Multi-threading operations like this are not supported by org.zeromq.ZMQ.Context.

The code in this class needs to find other ways to deal with the situation. It might be achieved by a control pipe and a poller, or other solution, except interrupting the running thread.

**Comment by mbe24** [comment]
@fredoboulo Thanks for the information!

**Comment by mbe24** [comment]
Maybe a`org.zeromq.ZMQ.Poller` for non-blocking I/O is enough. I don't know what`zmq.pipe.Pipe` is doing? What would I need it for?

**Comment by fredoboulo** [comment]
``zmq.pipe.Pipe`` is internal, you should normally be never touching it.
A control pipe is a PAIR socket with inproc:// protocol, that allows one thread to communicate with another one where all sockets operations are performed.
One of the most basic example of it is in the [ZThread.fork method](https://github.com/zeromq/jeromq/blob/master/src/main/java/org/zeromq/ZThread.java#L89), which allows a code to 'live' in a separate thread, while allowing to communicate with it with the returned socket. A [higher-level abstraction](https://github.com/zeromq/jeromq/blob/master/src/main/java/org/zeromq/ZActor.java) is available, you can find some usage examples in [EspressoTest](https://github.com/zeromq/jeromq/blob/master/src/test/java/org/zeromq/guide/EspressoTest.java#L207)

**Comment by mbe24** [comment]
Thanks again for the help! Also found sth. in the guide: http://zguide.zeromq.org/java:mtrelay and enhanced it. Since camel-zeromq uses multiple contexts, I did so, too. I have a working example now: https://gist.github.com/mbe24/14850d46dbeb9069aba42247d275e371

I'll add it to camel-zeromq when I have time.

**Comment by mbe24** [comment]
I've added a fix in https://github.com/camel-extra/camel-extra/pull/22. Can you please take a look, @fredoboulo. I've used a shared context and a pipe based on `inproc://`. 

Also, how can I increase the used ZMQ version? Bump the version of `zeromq-scala-binding_2.10` to `2.11-M3` (also `akka-zeromq_2.10`)?

**Comment by trevorbernard** [comment]
closing as this isn't a jeromq bug

**Comment by VaughnVernon** [comment]
Hey, I have attempted to find the Apache Camel support for JeroMQ, but the Camel docs don't refer to it. I would like to include JeroMQ here:

- https://github.com/vlingo/xoom-lattice-exchange-camel

If JeroMQ is indeed not supported by Camel, I can create a new repository such as this one:

- https://github.com/vlingo/xoom-lattice-exchange-rabbitmq

Please advise. Thanks!
