### ISSUE TITLE
Message loss on high frequency send (Dealer Router Connection)

### ISSUE THREAD

**Issue by sdoeringNew** [zeromq/jeromq#703]
Possibly related to #695 I experience message loss, too.

After successfully intialiazing a Dealer and a Router socket the Router sends a burst of 10.000 messages to the Dealer. Not all of them will be received by the Dealer.

Only if I add a wait for at least 0.01ms between the single sends all messages will be successfully received by the Dealer.

There is no high water mark or send timeout set.

```java
import org.zeromq.SocketType;
import org.zeromq.ZContext;
import org.zeromq.ZMQ;
import org.zeromq.ZMsg;

import java.nio.charset.StandardCharsets;
import java.util.UUID;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class DealerFailsToReceive {

    private static final int NUMBER_OF_MESSAGES = 10_000;

    public static void main(final String[] args) {
        final ExecutorService routerThread = Executors.newSingleThreadExecutor();
        try (final ZContext ctx = new ZContext()) {
            routerThread.submit(() -> {
                final ZMQ.Socket router = ctx.createSocket(SocketType.ROUTER);
                router.bind("tcp://*:5555");

                final ZMsg init = ZMsg.recvMsg(router, true);
                final String dealerId = init.popString();
                if (init != null) {
                    System.out.println("ROUTER: Start sending messages.");
                    for (int i = 0; i < NUMBER_OF_MESSAGES; ++i) {
                        final ZMsg response = new ZMsg();
                        response.add(dealerId);
                        response.add(String.valueOf(i).getBytes(StandardCharsets.UTF_8));
                        response.send(router);

                        // uncomment this busy wait to ensure all responses will be received by the dealer
//                        long start = System.nanoTime();
//                        while (start + 20_000L >= System.nanoTime()) ;
                    }
                    System.out.println("ROUTER: Done sending messages.");
                }
            });

            final ZMQ.Socket dealer = ctx.createSocket(SocketType.DEALER);
            dealer.setIdentity(UUID.randomUUID().toString().getBytes(StandardCharsets.UTF_8));
            dealer.setReceiveTimeOut(10_000);
            dealer.connect("tcp://127.0.0.1:5555");

            final ZMsg init = new ZMsg();
            init.add("init".getBytes(StandardCharsets.UTF_8));
            init.send(dealer);

            System.out.println("DEALER: Start receiving messages.");
            int counter = 0;
            while (counter < NUMBER_OF_MESSAGES) {
                final ZMsg response = ZMsg.recvMsg(dealer, true /* a timeout is set */);
                if (response != null) {
                    ++counter;
                } else {
                    throw new IllegalStateException("Unable to receive all expected response messages. Expected: " + NUMBER_OF_MESSAGES + ", Got: " + counter);
                }
            }
            System.out.println("DEALER: Done receiving messages.");
        } finally {
            routerThread.shutdownNow();
        }
    }
}
```

Tested with JeroMQ v0.5.0, Java 8 and Manjaro Linux.

**Comment by fredoboulo** [comment]
This may be related to HWM.

According to the specs of ROUTER socket:

> When a ROUTER socket enters the mute state due to having reached the high water mark for all peers, then any messages sent to the socket shall be dropped until the mute state ends. 
> Likewise, any messages routed to a peer for which the individual high water mark has been reached shall also be dropped, unless org.zeromq.ZMQ.Socket.setRouterMandatory(boolean) socket option is set to true. 

To quote some other components in the ZMQ galaxy:

> By default the router socket will discard outgoing messages above the HWM of 1,000. This isn't helpful for high-volume streaming.

Unbounding the router Send HWM by setting it to 0 `router.setSndHWM(0)`, or setting it to a much higher value (number of messages/4, let's say) was one way for me to make it work on my machine.


The problem occurs with inproc:// as well, so it's not related to IO operations.

The situation seems different from #695.

**Comment by sdoeringNew** [comment]
Awesome.

That totally explains it. After setting the send high water mark to ```0``` the test class finished successfully for me, too.

Thanks. I close this none-issue.
