### ISSUE TITLE
ZMQ.Socket.close() not working all the time

### ISSUE THREAD

**Issue by Christewart** [zeromq/jeromq#721]
Hi all, I'm experiencing behavior of `ZMQ.Socket.close()` not working. It is my understanding that proper tear down is closing our socket, and then calling `context.term()`

This might be related to #448 

Here is a link to the code I am running to shut down my zmq subscriber properly

https://github.com/Christewart/bitcoin-s-core/blob/361f44ce670263e7dd238ed5756bb6ea06586066/zmq/src/main/scala/org/bitcoins/zmq/ZMQSubscriber.scala#L92-L106

```scala
  def stop(): Unit = {
    //i think this could technically not work, because currently we are blocking
    //on Zmsg.recvMsg in our while loop. If we don't get another message we won't
    //be able toe evaluate the while loop again. Moving forward with this for now.
    running = false
    logger.warn(s"Attempting to close subscriber")

    subscriber.close()
    
    logger.warn(s"Terminating zmq context")
    context.term()

    logger.warn(s"Done with closing zmq")
    ()
}
```

logs:

```
2019-04-18 08:46:36.850 DEBUG o.b.d.w.CreateWallet.$anonfun$res_53$1(148) - Stopping zmq
2019-04-18 08:46:36.851 WARN  o.b.z.ZMQSubscriber.stop(97) - Attempting to close subscriber
2019-04-18 08:46:36.851 WARN  o.b.z.ZMQSubscriber.stop(101) - Terminating zmq context
```

As you can see, `context.term()` hangs forever -- which from what I understand is expected behavior if you are not closing the socket. As you can see, I am closing the socket with `subscriber.close()` so I don't know what is wrong here?

Am I missing something? I am using jermomq `0.5.1` and 
```
$ javac -version
  javac 1.8.0_191
```

**Comment by daveyarwood** [comment]
The context should handle closing sockets for you, such that you only need to close the context. I believe in your code, when you call `context.term()`, it's trying to re-close all of its sockets, at least one of which (your subscriber) you have already closed manually, so maybe that's causing unexpected behavior.

**Comment by Christewart** [comment]
I tried removing `subscriber.close()` and I still got the same behavior

**Comment by daveyarwood** [comment]
OK, that's a good data point.

I took a look at your code and it looks pretty sensible to me. Not sure why it would hang when the context is terminating. There have been at least several issues filed in the past re: context hanging upon termination, and I have observed this behavior myself from time to time. See https://github.com/zeromq/jeromq/issues/598, for example.

**Comment by Christewart** [comment]
@daveyarwood if you want to reproduce this and have the scala toolchain locally (sbt) you can clone this branch https://github.com/bitcoin-s/bitcoin-s-core/pull/430/commits/bd715c445dd0d75320d02024152a1baa402c06b2

and then run the script with this

```
$ sbt project/doc 
sbt:bitcoin-s-doc> run doc/src/main/scala/org/bitcoins/doc/wallet/create-wallet.sc
```

That will run the `.sc` file as a ammonite script

**Comment by entangled90** [comment]
I have the same issue with version 0.4.3.
I found out that when socket type is PUB setting the linger to 0 fixes the issue, but I have no clue why it's happening for SUB sockets.

**Comment by MuhammadShifa** [comment]
Its working fine, when I closed the socket first and then term the context like
socket_name_in_context.close()
context_name.term()
