### ISSUE TITLE
ZPoller.poll returning -1 with v0.5.1

### ISSUE THREAD

**Issue by normano** [zeromq/jeromq#729]
Jeromq v0.5.1
MacOSX 10.14.4

```
var inPoller = new ZPoller(context);
inPoller.register(new ZPoller.ZPollItem(inprocSocket, null, ZPoller.POLLIN));
int inPollEventsCount = inPoller.poll(-1);
```

Not sure what happened between the upgrade, but I get 1 on poll on v0.5.0, but -1 on v0.5.1, so something went wrong somewhere. Something undocumented?

**Comment by esahekmat** [comment]
I test this and I found out this bug is related to ComposedPollerItem, I have wrote a test which does pass on v0.5.0 but does not pass on master, I will make a PR for this test tonight
