### ISSUE TITLE
PUSH/PULL socket no communication

### ISSUE THREAD

**Issue by josipanas** [zeromq/jeromq#734]
Hi,

Our application is using jeromq 0.4.3 within java process and communicates with zeromq within cpp process.
We implemented PUSH/PULL method through 2 sockets.

First socket: CPP is server and Java is client.
Second socket: Java is server and CPP is client.

It has been working fine for over 50 days and now the problem appeared in 4 different servers running this setup, after the approximately same period of running. Our sockets are under a load of a couple of thousand messages per second.

When looking through netstat (we are using RHEL OS), we can see that socket status is ESTABLISHED (both of them), but when collecting tcpdump, we can see that there are no tcp messages on the second socket.

In our code, we can see that this condition is statisfied:
sender.send(jsonInString, ZMQ.DONTWAIT) == false

Client restart didn't resolve this issue. The issue was resolved only after a server restart, but this is not a valid solution if the software is used by customers.

What would be the possible reason for socket communication not working even though OS says that socket is established?

Thank you in advance!

**Comment by narendraj9** [comment]
+ Adding myself to this conversation.

**Comment by josipanas** [comment]
Could it be possible that my issue is somehow connected with this issue that was fixed in jeromq 0.5.0?
From CHANGELOG.md:
"#634: We are now using a 64-bit long, instead of a 32-bit integer, as a cursor in the internal java.zmq.Signaler class. This change should not affect the library user, except that it will now take longer for the value to overflow. Previously, with the 32-bit integer cursor, the Signaler could overflow within a month or so under heavy load, causing serious problems such as a server being unable to accept new client connections."

**Comment by daveyarwood** [comment]
@josipanas Can you confirm if the issue is still present in the latest release?

**Comment by josipanas** [comment]
The issue is not present in the 0.5.1 release that we currently use.
