### ISSUE TITLE
Using zeromq communication, a thread has an exception, how to ensure that it returns to the client

### ISSUE THREAD

**Issue by changetoblow** [zeromq/jeromq#738]
The server side of zeromq opens 20 threads, and then I customize an exception capture for each thread. However, when an exception occurs in a thread, it is not returned to the customer service. Below is the code, is to catch the exception handling, there is a return value, but did not return to the client,Can you help me, thank you
`/**
     *Exceptions that occur in the catch exception thread will be caught here
     */
    @Override
    public void uncaughtException(Thread t, Throwable e) {
        logger.info("************FAILED************");
        logger.info(t.currentThread().getName() + e.getMessage());

        while (skt.hasReceiveMore()){
            skt.recvStr(0).trim();
        }
        skt.send("FAILED", 2);
        skt.send("FAILED:" + e.getMessage(), 0);

    }`

**Comment by narendraj9** [comment]
Sockets are not thread safe. The `uncaughtExceptionHander` will be executed by the JVM in a different thread so I think the behavior in this case isn't defined. My best guess would be to handle the exception right in the thread itself and use the socket within the thread that created it.

**Comment by changetoblow** [comment]
@narendraj9 Thank you very much for your answer
