### ISSUE TITLE
for ZMQ.SUB, subscriber.subscribe function does not exist

### ISSUE THREAD

**Issue by andreireiand** [zeromq/jeromq#740]
this calls the MVN repository 0.5.1 jar file from within matlab ... nonetheless problem is valid:

import org.zeromq.*
ctx = zmq.Ctx();
subscriber = ctx.createSocket(ZMQ.SUB);
subscriber.connect('tcp://127.0.0.1:5555');

function: 
subscriber.subscribe

does not exist. 
I can see one can use setSocketOpt, but good luck w/ finding the right sintax/etc. 
Some examples & adding subscribe would do great.

**Comment by andreireiand** [comment]
Is there a way to hook an event handler ... such that subscriber.recv doesn't get blocked ... but an event gets generated for each message received?

thanks

**Comment by daveyarwood** [comment]
See the [wuclient zguide example](https://github.com/zeromq/jeromq/blob/master/src/test/java/guide/wuclient.java) for an example of using a subscriber socket. Note that ZContext is the public API for a ZMQ context in JeroMQ. zmq.Ctx is an implementation detail, and I wouldn't recommend using it directly in your application code.

ZMQ.Socket.subscribe is defined [here](https://github.com/zeromq/jeromq/blob/fccf4e7487b8b8b96d64b3cb1617457812e35494/src/main/java/org/zeromq/ZMQ.java#L2092).

Re: event handlers, I would recommend reading about polling in the zguide. There is also a small amount of JeroMQ-specific information about pollers [here](https://github.com/zeromq/jeromq/blob/master/doc/pollers.md).

Hope that helps!

**Comment by narendraj9** [comment]
Why does JeroMQ have ZContext? I think it made sense to have ZContext if it was made thread-safe which it isn't. It only adds complexity to the API and doesn't provide any real benefit to be honest. It encourages people to not care about closing their sockets.

**Comment by daveyarwood** [comment]
ZContext is the higher-level, public API. The major benefit is that it _allows_ you to not care about closing sockets and other resources like polling selectors.

I'm not totally sure why ZContext is not thread-safe. It seems like it ought to be, given that there are references in the ZMQ API docs to [ZMQ contexts being thread-safe](http://api.zeromq.org/2-1:zmq). If the JeroMQ context is not thread-safe, then we should probably fix that.

**Comment by narendraj9** [comment]
It is not thread-safe because ZeroMQ sockets are not threadsafe and it deals with sockets that could possibly be from a different thread.

**Comment by daveyarwood** [comment]
According to the API doc I linked above, sockets are not thread-safe, but contexts are:

> A ØMQ context is thread safe and may be shared among as many application threads as necessary, without any additional locking required on the part of the caller.
>
> Individual ØMQ sockets are not thread safe except in the case where full memory barriers are issued when migrating a socket from one thread to another. In practice this means applications can create a socket in one thread with zmq_socket() and then pass it to a newly created thread as part of thread initialization, for example via a structure passed as an argument to pthread_create().

**Comment by narendraj9** [comment]
ZeroMQ context is not JeroMQ ZContext.

**Comment by daveyarwood** [comment]
I know what you mean, but the JeroMQ ZContext is at least intended to be an implementation of the ZMQ context.

If there are important aspects of a ZMQ context that the ZContext fails to implement, then I think those should be treated as bugs in JeroMQ.

(By the way, I'm closing this issue as the original issue re: the `subscribe` method has been addressed. I'm happy to keep chatting about this, though.)
