### ISSUE TITLE
cannot resolve symbol Zhelper

### ISSUE THREAD

**Issue by gh936687045** [zeromq/jeromq#741]
import org.zeromq.SocketType;
import org.zeromq.ZMQ;
import org.zeromq.ZMQ.Socket;
import org.zeromq.ZContext;
import org.zeromq.*;

/**
 * Demonstrate identities as used by the request-reply pattern.
 */
public class identity
{

    public static void main(String[] args) throws InterruptedException
    {
        try (ZContext context = new ZContext()) {
            Socket sink = context.createSocket(SocketType.ROUTER);
            sink.bind("inproc://example");

            //  First allow 0MQ to set the identity, [00] + random 4byte
            Socket anonymous = context.createSocket(SocketType.REQ);

            anonymous.connect("inproc://example");
            anonymous.send("ROUTER uses a generated UUID", 0);
            ZHelper.dump(sink);

            //  Then set the identity ourself
            Socket identified = context.createSocket(SocketType.REQ);
            identified.setIdentity("Hello".getBytes(ZMQ.CHARSET));
            identified.connect("inproc://example");
            identified.send("ROUTER socket uses REQ's socket identity", 0);
            ZHelper.dump(sink);
        }
    }
}

when I used this demo in the document,my project cannot find ZHelper class,I cannot find this class in my jeromq package,the jeromq I used is 0.5.1.What causes this?

**Comment by daveyarwood** [comment]
[ZHelper](https://github.com/zeromq/jeromq/blob/master/src/test/java/guide/ZHelper.java) is defined in the guide package to provide utilities for testing. It is not part of the JeroMQ library.

**Comment by gh936687045** [comment]
I do,Thank you very much~.
