### ISSUE TITLE
Is there a message pool in the ZMsg class?

### ISSUE THREAD

**Issue by gh936687045** [zeromq/jeromq#745]
when I receiving a message by  ZMsg.recvMsg() method with blocking, I used ZMsg.send() method to send message, I received message until I sent a lot of message.what case this? Is there a message pool in the ZMsg class?

Besides,Where can I see ZMQ use cases other than zguide,because after I had read the Zguide,I still understand how to use API to solve my problem.

Looking forward to your reply ! Best wishes~

**Comment by daveyarwood** [comment]
I'm not sure why you wouldn't immediately receive the message that is sent. I don't think there is any pooling / buffering going on. Do you have some small example code that demonstrates the problem?

See [Getting Started](https://github.com/zeromq/jeromq#getting-started) for a simple example and a link to all of the [JeroMQ translations of the zguide examples](https://github.com/zeromq/jeromq/tree/master/src/test/java/guide).

**Comment by gh936687045** [comment]
thanks for your reply,I solved the question, my thread will end after sending message,when the recvMsg method receive msg, the deaded thread will cause the message been abandon.  
Besides,is it ok for me to ask questions in issue? Is there another community to discuss?

**Comment by daveyarwood** [comment]
Raising issues here is fine! I think StackOverflow might also be a good place to post questions about ZeroMQ / JeroMQ, I've seen questions there before. You're likely to get faster / better responses here though.

**Comment by ChengYongchao** [comment]
yeah，I get it, Thank you very much for your reply~
