### ISSUE TITLE
Android - dealer connect crash "No virtual method clear()Ljava/nio/ByteBuffer"

### ISSUE THREAD

**Issue by Laurnet35** [zeromq/jeromq#748]
Hi,
I'm trying to use jeromq for an android project. I need to connect to another dealer device. Here is my code :

```
ZContext zcontext = new ZContext(1);
ZMQ.Socket zsocket = zcontext.createSocket(ZMQ.DEALER);
String identity = "S61_phone";
zsocket.setIdentity(identity.getBytes(ZMQ.CHARSET));
zsocket.connect("tcp://my_other_device");
zsocket.send("test",0);
```
At the connect call, an error occurs :

> 2019-09-26 16:59:53.033 18347-18379/? E/AndroidRuntime: FATAL EXCEPTION: Thread-4
>     Process: com.flir.flironeexampleapplication, PID: 18347
>     java.lang.NoSuchMethodError: No virtual method clear()Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)
>         at zmq.Signaler.send(Signaler.java:97)
>         at zmq.Mailbox.send(Mailbox.java:71)
>         at zmq.Ctx.sendCommand(Ctx.java:517)
>         at zmq.ZObject.sendCommand(ZObject.java:382)
>         at zmq.ZObject.sendPlug(ZObject.java:185)
>         at zmq.ZObject.sendPlug(ZObject.java:175)
>         at zmq.Own.launchChild(Own.java:115)
>         at zmq.SocketBase.addEndpoint(SocketBase.java:590)
>         at zmq.SocketBase.connect(SocketBase.java:582)
>         at org.zeromq.ZMQ$Socket.connect(ZMQ.java:2531)
>         at com.flir.flironeexampleapplication.GLPreviewActivity.onDeviceConnected(GLPreviewActivity.java:115)
>         at com.flir.flironesdk.EmbeddedDevice$4.run(EmbeddedDevice.java:512)
>         at java.lang.Thread.run(Thread.java:764)

My environment :
- jeromq 0.5.2
- Android 8.1 (Oreo) 
- Compiling in Android Studio with JDK 1.8.0_66 / ndk r10e

Any idea of what is the problem ? Thanks a lot.

**Comment by trevorbernard** [comment]
It appears that the jeromq library you're using was built with a SDK that was greater than java 8. In java 9 `ByteBuffer.clear()` returns a `ByteBuffer` where java 8 or lower, it returns a `Buffer`. The resulting error is the one you described.

Also the latest stable release is 0.5.1 and I verified in the manifest.mf that it was built with  1.8.0_19

**Comment by Laurnet35** [comment]
Thank you for your help. Looks like that was the problem. I've rebuilt the library with JDK 8. I'm now facing another problem but it's probably not related to the first.
When I try to build the project, it is saying that one classe of zeromq is duplicated but I'm not sure why (I'm new to Android dev).

> AGPBI: {"kind":"error","text":"Program type already present: 
> org.zeromq.ManagedContext$1","sources":[{}],"tool":"D8"}
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
> Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
> Program type already present: org.zeromq.ManagedContext$1
> at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java 131)

**Comment by daveyarwood** [comment]
Unclear if this is an issue with JeroMQ or not, and this issue has been inactive for a while, so I'm closing it. Feel free to reopen if needed.
