### ISSUE TITLE
JeroMQ subscriber connection breaks when recv-ing in Matlab

### ISSUE THREAD

**Issue by kmlancaster** [zeromq/jeromq#756]
Using JeroMQ in Matlab, my subscriber connection drops when I try to `recv` a message. I have verified this with Wireshark. I also note that the closing of the TCP connection is initiated by my subscribing port, not the publishing port. 

```
javaclasspath('jeromq-0.5.1.jar') 
import org.zeromq.*;

ctx = zmq.Ctx();
socket = ctx.createSocket(ZMQ.SUB);
socket.connect('tcp://127.0.0.1:5996')
message = socket.recv(1) %this is when the connection gets dropped
```
My .jar file is from the [MVNRepository](https://mvnrepository.com/artifact/org.zeromq/jeromq/0.5.1).

[Wireshark screenshot showing connection being closed](https://i.stack.imgur.com/QJ9ha.png)

I don't know for sure if it would help, but I have investigated using this,
```
socket.setSocketOpt(ZMQ.ZMQ_TCP_KEEPALIVE,1)
```
but Matlab reports that ZMQ_TCP_KEEPALIVE is an unrecognized function or variable.

I am indebted to the folks on [this](https://stackoverflow.com/questions/38060320/how-to-use-jeromq-in-matlab/44865494#44865494) thread for getting me started on the right foot with JeroMQ in Matlab.

**Comment by daveyarwood** [comment]
I'm not sure off-hand what the problem might be, but I would try to use ZContext instead of Ctx. Ctx is a low-level implementation detail, not intended to be used directly.

See: https://github.com/zeromq/jeromq/blob/master/doc/contexts.md

**Comment by fredoboulo** [comment]
+1 for Dave's suggestion.
You import `org.zeromq.ZMQ`. ZMQ_TCP_KEEPALIVE is part of `zmq.ZMQ`.
Instead, please use org.zeromq.ZMQ.Socket.setTCPKeepAlive(1)

As you are using a SUB socket, you need to subscribe to something first. You could start by inserting the code `socket.subscribe(ZMQ.SUBSCRIPTION_ALL);` before connecting. Or subscribe to the topic you want to receive.

When it comes to `message = socket.recv(1)`, the 1 parameter (ZMQ.DONTWAIT) implies you are not blocking for the arrival of a message. If there is nothing to be received, the call returns immediately. To block until reception of a message, use `message = socket.recv()`

**Comment by kmlancaster** [comment]
I did some more research and factored in the above suggestions (thanks!). Turns out that my socket wasn't closing until later in the code at my `close()` function. Here is my working code for others looking to get started using JeroMQ in Matlab.

```
javaclasspath('jeromq-0.5.1.jar')
import org.zeromq.*;

%subscribe to ZMQ feed
context = ZContext();
socket = context.createSocket(ZMQ.SUB); 
success = false;
while(~success)
    success = socket.connect('tcp://127.0.0.1:5996');
end
socket.subscribe("");
socket.setTCPKeepAlive(1);

%receive a message
message = socket.recv(0); %nonblocking receive uses argument (1)

%when done
socket.close();
```
