### ISSUE TITLE
Updating from 3.X to 5.X breaks

### ISSUE THREAD

**Issue by SElab2019** [zeromq/jeromq#762]
When I try to upgrade jeromq from 3.X to the version after 4.X. The following code breaks.
```
import org.zeromq.ZMQ;
import org.zeromq.ZMQ.PollItem;
import org.zeromq.ZMQ.Poller;
import org.zeromq.ZMQ.Socket;

public class Demo {
	
	
	private Socket socket;
	
	public void test() {
		
		PollItem items[] = { new PollItem(socket, Poller.POLLIN) };
		int rc = ZMQ.poll(items, -1);
		
	}

}
```

The code should pass, but it throws an error:
```
Demo.java:[17,29] no suitable method found for poll(org.zeromq.ZMQ.PollItem[],int)
[ERROR] method org.zeromq.ZMQ.poll(java.nio.channels.Selector,org.zeromq.ZMQ.PollItem[],long) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.zeromq.ZMQ.poll(java.nio.channels.Selector,org.zeromq.ZMQ.PollItem[],int,long) is not applicable
[ERROR] (actual and formal argument lists differ in length)
```

**Comment by daveyarwood** [comment]
This was a deliberate breaking change made in JeroMQ 0.4.0.

For reference:

* https://github.com/zeromq/jeromq/blob/master/CHANGELOG.md#v040-2017-03-22
* https://github.com/zeromq/jeromq/pull/387

To summarize, using sockets and polling creates system resources (selectors, etc.), and we want to make sure that the resources get cleaned up, so you must use create sockets and pollers via a context.

For more information about how to poll, see:

* https://github.com/zeromq/jeromq/blob/master/doc/pollers.md

* https://github.com/zeromq/jeromq/blob/master/src/test/java/guide/mspoller.java
