### ISSUE TITLE
Jeromq does not support UNIX domain sockets.Does JZMQ have support for UNIX domain sockets?

### ISSUE THREAD

**Issue by changetoblow** [zeromq/jeromq#766]
Jeromq does not support UNIX domain sockets.Does JZMQ have support for UNIX domain sockets?

**Comment by fbacchella** [comment]
Comming soon to openjdk :https://openjdk.java.net/jeps/380. But not sure about android.

**Comment by fbacchella** [comment]
One possible solution for that explained in #404.

**Comment by trevorbernard** [comment]
This is a JZMQ question
