### ISSUE TITLE
zmq missing some message from JeroMq

### ISSUE THREAD

**Issue by nhunh585** [zeromq/jeromq#768]
I have server on Nodejs (PULL)

> `// worker.js
> var zmq = require('zmq')
>   , sock = zmq.socket('pull');
>  
> sock.connect('tcp://0.0.0.0:3000');
> console.log('Worker connected to port 3000');
>  
> sock.on('message', function(msg){
>   console.log('work: %s', msg.toString());
> });`

and client on Java (JeroMq)

> try (ZContext context = new ZContext()) {
> 			// Socket to talk to clients
> 			ZMQ.Socket socket = context.createSocket(ZMQ.PUSH);
> 			socket.bind("tcp://*:3000");
> 			int i = 0;
> 			while (!Thread.currentThread().isInterrupted()) {
> //				socket.send(response.getBytes(ZMQ.CHARSET), 0);
> 				socket.send("from java aaa" + i);
> 				i++;
> 				if(i == 5000) {
> 					break;
> 				}
> 			}
> 		}

When I run the server logging like this:

work: from java aaa2050
work: from java aaa2051
work: from java aaa2052
work: from java aaa2053
work: from java aaa2054
work: from java aaa2055
work: from java aaa2056
work: from java aaa2057
work: from java aaa2058
work: from java aaa2059
work: from java aaa2060
work: from java aaa2061
work: from java aaa2062
work: from java aaa2063
work: from java aaa2064
work: from java aaa2065
.....

The message from 0 - 2049 is missing. I think socket need some miliseconds to connect to the server so message from 0 to 2049 was missed

**Comment by esahekmat** [comment]
According to this chart: http://zguide.zeromq.org/page:all#toc52
You need to start Subscribers before the publisher.
also note this part of ZGuide:

> This "slow joiner" symptom hits enough people often enough that we're going to explain it in detail. Remember that ZeroMQ does asynchronous I/O, i.e., in the background. Say you have two nodes doing this, in this order:
> 
>     Subscriber connects to an endpoint and receives and counts messages.
>     Publisher binds to an endpoint and immediately sends 1,000 messages.
> 
> Then the subscriber will most likely not receive anything. You'll blink, check that you set a correct filter and try again, and the subscriber will still not receive anything.
> 
> Making a TCP connection involves to and from handshaking that takes several milliseconds depending on your network and the number of hops between peers. In that time, ZeroMQ can send many messages. For sake of argument assume it takes 5 msecs to establish a connection, and that same link can handle 1M messages per second. During the 5 msecs that the subscriber is connecting to the publisher, it takes the publisher only 1 msec to send out those 1K messages.

http://zguide.zeromq.org/page:all#Getting-the-Message-Out

**Comment by nhunh585** [comment]
Hi @esahekmat,

I am using PUSH/PULL pattern.

**Comment by fredoboulo** [comment]
Could you try to use setImmediate(false) on the PUSH socket?

https://github.com/zeromq/jeromq/blob/master/src/main/java/org/zeromq/ZMQ.java#L2525

**Comment by nhunh585** [comment]
@fredoboulo Thank you very much. It's worked.
