### ISSUE TITLE
Monitor ZMQ.Socket--How should I use (ZMQ.Socket)req.monitor(final String addr, int events)？？？

### ISSUE THREAD

**Issue by dunkboy** [zeromq/jeromq#770]
this code I write like this req.monitor("inproc://reqmoniter", ZMQ.EVENT_ALL );
but  I do not know how to get  msg from "ZMQ.EVENT_ALL"???
I found that monitor of ZMQ.Socket hava create SocketBase.
public boolean monitor(String addr, int events)
        {
            return base.monitor(addr, events);
        }
 monitorSocket = getCtx().createSocket(ZMQ.ZMQ_PAIR);

I can't use the monitorSocket  in the SocketBase.

I need to create one more ZMQ.Socket for get  monitor in a separate thread???

please tell me how to monitor the Socket ???

I will be deeply grateful! thank you vevry much!

**Comment by fredoboulo** [comment]
You could make use of [org.zeromq.ZMonitor](https://github.com/zeromq/jeromq/blob/master/src/main/java/org/zeromq/ZMonitor.java).
There is [some simple example in the unit test of the class ZMonitorTest](https://github.com/zeromq/jeromq/blob/master/src/test/java/org/zeromq/ZMonitorTest.java#L41)

That won't exonerate you from consuming the events in a separate thread, but the setup may be simpler.

**Comment by dunkboy** [comment]
ok thank you vevry much!
