### ISSUE TITLE
req-rep###How to get req ip addr???

### ISSUE THREAD

**Issue by dunkboy** [zeromq/jeromq#771]
Can you tell me how to get req(clinet) ip addr in the rep(server)?

**Comment by fredoboulo** [comment]
Hi, would the client identity be enough for you?
Could you expand your use case?

**Comment by dunkboy** [comment]
rep(server) can be get  identity of req(clinet) from req(clinet)?

**Comment by dunkboy** [comment]
I don't know what's different about them（ZMQ.Socket and ZSocket）? Which one should I use?
Or who do you suggest to use first？

**Comment by dunkboy** [comment]
Can I limit the number of  req connections for ZMQ.Socket?

**Comment by trevorbernard** [comment]
@dunkboy I would suggest asking how-to questions on the ZeroMQ mailing list or on stackoverflow. I'm going to close as this isn't a bug with JeroMQ. Best of luck.
