### ISSUE TITLE
ZContext.destroySocket might forget socket

### ISSUE THREAD

**Issue by fbacchella** [zeromq/jeromq#776]
This method says:
```
    public void destroySocket(Socket s)
    {
        if (s == null) {
            return;
        }
        s.setLinger(linger);
        s.close();
        this.sockets.remove(s);
    }
```

It the thread is interrupted, s.close() will throws a zmq.ZError$IOException, but before the sockets.remove(s);

So the socket is closed anyway because of the `isClosed.compareAndSet(false, true)` in ZMQ.Socket.close() code, but it's still in  ZContext.sockets Set. So I think the code could be:
```
try {
    s.close();
}  finally {
    this.sockets.remove(s);
}
```

**Comment by daveyarwood** [comment]
I agree -- if you don't mind putting together a PR, I'll merge it!

**Comment by fbacchella** [comment]
Merge #777
