### ISSUE TITLE
android lint

### ISSUE THREAD

**Issue by fbacchella** [zeromq/jeromq#784]
I tried to play with android lint and jeromq, and one of the first problem I met was a missing `android:minSdkVersion` in src/android/Jeromq/app/src/main/AndroidManifest.xml. What is the expected value it should be ?

I run android lint with:
```
rm src/android/Jeromq/app/build.gradle
/tmp/androidsdk/tools/bin/lint --showall --xml $PWD/target/lint-results/lint-results.xml --sources $PWD/src/main/java $PWD --exitcode --disable Assert ; echo $?
```

**Comment by daveyarwood** [comment]
Looks like we went with 19 in #785?

**Comment by fbacchella** [comment]
That's the version I found to be compatible. But I found inconsistent results trying to build it using circleci.
