### ISSUE TITLE
False sens of security in org.zeromq.ZPoller.dispatch(Collection<? extends ItemHolder>, int)

### ISSUE THREAD

**Issue by fbacchella** [zeromq/jeromq#794]
I found this code in the method [org.zeromq.ZPoller.dispatch(Collection<? extends ItemHolder>, int)](https://github.com/zeromq/jeromq/blob/master/src/main/java/org/zeromq/ZPoller.java#L712):

```
        ItemHolder[] array = all.toArray(new ItemHolder[all.size()]);
        // protected against handlers unregistering during this loop
        for (ItemHolder holder : array) {
```

It tried a simple replacement:
```
        for (ItemHolder holder : all) {
```

But it generats a lot of ` java.util.ConcurrentModificationException` because the the collection `all` is modified by another thread.

But I don't think that `all.toArray(new ItemHolder[all.size()]);` is a good protection. It just reduce the possibility of failure as the toArray call is much shorter. But the possibility of failure still exists. So the ZPoller.all Set should be  concurrent (https://github.com/zeromq/jeromq/blob/master/src/main/java/org/zeromq/ZPoller.java#L472)
```
all = new HashSet<>();
```

changed to
```
 all = Collections.synchronizedSet(new HashSet<>());
```

This kind of collection don't have a very good performance, but I don't think that's a big problem for the current use case.

**Comment by trevorbernard** [comment]
We should refrain from using integrators in any hot parts of the jeromq codebase as well because they generate garbage.

**Comment by fbacchella** [comment]
Integrators ? You mean iterator ?

**Comment by trevorbernard** [comment]
Yes, a typo. I'm not familiar with how ZPoller operates and whether it's meant to be thread-safe or now

**Comment by fbacchella** [comment]
Do you have reference on what kind of garbage iterators generate ? The current code generate a full array each time it's called ?
The failing test is `org.zeromq.guide.AsyncServerTest` and the failure stack is:
```
Exception in thread "proxy" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at org.zeromq.ZPoller.dispatch(ZPoller.java:712)
	at org.zeromq.ZPoller.dispatch(ZPoller.java:691)
	at org.zeromq.ZPoller.poll(ZPoller.java:678)
	at org.zeromq.ZPoller.poll(ZPoller.java:654)
	at org.zeromq.ZActor$Double.breathe(ZActor.java:562)
	at org.zeromq.ZStar$Plateau.showMustGoOn(ZStar.java:557)
	at org.zeromq.ZStar$Plateau.run(ZStar.java:495)
	at org.zeromq.ZThread$ShimThread.run(ZThread.java:56)
```

So probably ZPoller  is used in a mutli-thread context in this case.

**Comment by trevorbernard** [comment]
I guess after java 8 the compiler can use escape analysis to put the iterator on the stack. http://psy-lob-saw.blogspot.com/2014/12/the-escape-of-arraylistiterator.html

**Comment by fredoboulo** [comment]
I interpret that not as concurrency problem here, but as the fact that handlers can unregister a socket DURING the loop.
so if you iterate on a collection, and processing one element removes or adds something in that collection, that leads to ConcurrentModificationException when iterating to the next element.
The transformation to Array is to prevent that. ZPoller is not thread-safe, and was not intended to be. I'd expect much more work to be done if this is the direction that wants to be given to that class.

**Comment by fbacchella** [comment]
Ok, I got it. You're talking about the call to handler.events(socket, events) ? If that's the case, indeed the Set.toArray is enough.
By the way, java.util.AbstractCollection.toArray(T[]) uses an iterator internally. So no difference in garbage generated here.
