### ISSUE TITLE
Proposal: Integrate Github releases with publishing to Maven Central

### ISSUE THREAD

**Issue by trevorbernard** [zeromq/jeromq#807]
Currently, releasing a stable release is a very manual process and subject to human error. We should integrate an automated process to build, sign and deploy to maven central.

**Comment by fbacchella** [comment]
In my other project (rrd4j) I have a dedicated branch called release. Maven is configured to publish on bintray (https://bintray.com/rrd4j/RRD4J/org.rrd4j:rrd4j), on a custom maven repo. When I want to publish a revision, I merge the master branch in it. I change the revision in the pom.xml  and release not and publish it. If the publication succeed, I can put a tag. Then I go to bintray, and sync the specific maven repo to maven central. GPG signin is done by bintray, so I don't have to handle the secret key myself.
