### ISSUE TITLE
Problem: No way to access/set routing-id for Server/Client communication from high level API

### ISSUE THREAD

**Issue by trevorbernard** [zeromq/jeromq#808]
zmq.Msg supports getting and setting of the routing-id for Server/Client communication. There is currently no way to get org.zeromq.ZMQ API to work with Client/Server

**Comment by somdoron** [comment]
I would add that in order to keep it thread safe it must be atomic, meaning arrive with the data in the same API call. We would also need it for group in the radio/dish pattern

**Comment by somdoron** [comment]
I think ZFrame is the best option. We can also have thread local on ZSocket with the routing id, however that would break in frameworks that switch the execution thread automatically.

**Comment by trevorbernard** [comment]
Yeah it makes sense in there. Only problem is that it deviates from the libzmq API a bit

**Comment by somdoron** [comment]
czmq is using zframe as well for the routing id and group.
