### ISSUE TITLE
ZSocket.unbind() throws exception

### ISSUE THREAD

**Issue by relict007** [zeromq/jeromq#824]
I have just started with ZeroMQ and was doing some experiments and found that calling `ZSocket.unbind()` always throws the exception when we try to unbind after usage.

Here's the sample (in Kotlin):
```kotlin
import org.zeromq.ZSocket
import zmq.ZMQ

fun main() {
    val push = ZSocket(ZMQ.ZMQ_PUSH)
    val pull = ZSocket(ZMQ.ZMQ_PULL)
    push.connect("tcp://0.0.0.0:12345");
    pull.bind("tcp://127.0.0.1:12345");
    for (i in 0..5) {
        push.sendStringUtf8("msg:$i")
        println(pull.receiveStringUtf8())
    }
    pull.unbind("tcp://127.0.0.1:12345")
    push.close()
}
```

Here's the exception:
```
Exception in thread "main" org.zeromq.ZMQException: Errno 48 : Address already in use
	at org.zeromq.ZSocket.mayRaise(ZSocket.java:254)
	at org.zeromq.ZSocket.unbind(ZSocket.java:99)
	at PushpullKt.main(pushpull.kt:18)
	at PushpullKt.main(pushpull.kt)
```

Here's my analysis. 
The code in the master branch. `ZSocket.unbind()` internally calls
`socketBase.bind()` , however, it should be calling `socketBase.unbind()`.
```
public boolean unbind(final String endpoint)
    {
        final boolean result = socketBase.bind(endpoint);
        mayRaise();
        return result;
    }
```

**Comment by fbacchella** [comment]
When I read https://github.com/zeromq/jeromq/blob/master/doc/sockets.md, it make me think that the socket class to use is org.zeromq.ZMQ.Socket. Perhaps org.zeromq.ZSocket should be deprecated ?

**Comment by relict007** [comment]
Yes, the problem is not seen with `ZContext.Socket'
This works and doesn't throw exception:
```kotlin
import org.zeromq.SocketType
import org.zeromq.ZContext

fun main() {
    val context = ZContext()
    val push = context.createSocket(SocketType.PUSH)
    val pull = context.createSocket(SocketType.PULL)

    push.connect("tcp://0.0.0.0:12345");
    pull.bind("tcp://127.0.0.1:12345");
    for (i in 0..5) {
        push.send("msg:$i")
        println(pull.recvStr())
    }
    pull.unbind("tcp://127.0.0.1:12345")
    push.close()
}
```

**Comment by daveyarwood** [comment]
> When I read https://github.com/zeromq/jeromq/blob/master/doc/sockets.md, it make me think that the socket class to use is org.zeromq.ZMQ.Socket. Perhaps org.zeromq.ZSocket should be deprecated ?

I would currently recommend using `ZContext.createSocket` to create sockets. I think ZSocket has promise, though. I like the idea of not having to worry about contexts at all, and instead just creating ZSocket and ZPoller instances and everything just works™.

I've written a little about ZSocket / ZPoller and some of the rough edges in #394 and #396.

**Comment by fbacchella** [comment]
Is there any plan to « finish » ZSocket ? There is no way to set many options. The API is very poor. It's not used anywhere. Test coverage is poor. This class looks dead to me.

**Comment by fredoboulo** [comment]
I've never been using ZSocket, and do not intent to. Mostly because it's using ManagedContext under the hood, and I individually identify as an anti-pattern the usage of ThreadLocal for holding resources that can leak  (@daveyarwood if you remember the old situation about the selectors...). Other APIs are fine for me.

**Comment by daveyarwood** [comment]
I agree about the perils with ThreadLocal - I remember the issues that has caused with selectors.

Does ManagedContext really need to use ThreadLocal, though? It could just be a global state in the JVM process.

**Comment by fbacchella** [comment]
There is a lot of anti-pattern in ManagedContext.

Singloton are painful to test. The created context can only handle a fixed number of IOThread (1).

But I don't see any use of ThreadLocal in it. Did I miss something ?

**Comment by fredoboulo** [comment]
Oops, my bad memory ... And I did not check before answering. I was rather thinking about the static code Runtime.getRuntime().addShutdownHook closing the context.

Nevertheless: Using a shutdown hook to release resources that can leak is something that I'm trying to avoid.

**Comment by daveyarwood** [comment]
I feel like there should be a public method to allow us to explicitly close
the ManagedContext, and another to re-open it. That would also facilitate
testing.

**Comment by fbacchella** [comment]
I did try a small experiment. I removed ManagedContext.java, ZSocket.java and ZSocketTest.java and the test testIssue338 in org.zeromq.TestPushPullThreadedTcp.

Nothing broke. Do they worth being repaired ?

**Comment by fredoboulo** [comment]
It's published API, we need to keep it.

@daveyarwood that means we are getting away from the convenience of everything works without caring about the context. but that could be a beginning.

**Comment by daveyarwood** [comment]
My thought is that the common case would be to not worry about the ManagedContext at all. It would continue to work the way it does now, where it starts automatically upon initialization, and there is a shutdown hook that shuts it down when the JVM exits.

But I'm thinking that to facilitate testing, we could also provide methods to allow us to manually stop and restart the context.
