### ISSUE TITLE
Race condition in ZLoop

### ISSUE THREAD

**Issue by artembilan** [zeromq/jeromq#853]
Looks like there is some issue in `ZLoop`: as long as I interrupt the thread for loop, the `ZContext` cannot be destroyed. It is stuck on waiting for in the `Ctx`:
```
//  Wait till reaper thread closes all the sockets.
Command cmd = termMailbox.recv(WAIT_FOREVER);
```

Sometimes it can pass though, but in most cases it looks like in dead lock situation.
Here is some test-case to reproduce:
```
	@Test
	public void test() throws InterruptedException {
		ExecutorService executorService = Executors.newFixedThreadPool(1);

		ZContext ctx = new ZContext();

		ZMQ.Socket socket = ctx.createSocket(SocketType.PULL);
		socket.bind("ipc://test");

		ZLoop zLoop = new ZLoop(ctx);

		ZMQ.PollItem pollItem = new ZMQ.PollItem(socket, ZMQ.Poller.POLLIN);

		zLoop.addPoller(pollItem, (loop, item, arg) -> 0, null);

		Future<Integer> future = executorService.submit(zLoop::start);

		Thread.sleep(1000);

		future.cancel(true);

		socket.close();
		ctx.close();

		executorService.shutdownNow();
	}
```

JeroMQ version is `0.5.2`.

I won't mind though if I use this API wrong way: I'm just in the beginning of ZeroMQ journey.

Thanks in advance for any hints!

**Comment by artembilan** [comment]
I have another test to demonstrate issue:

```
@Test
	public void test() throws InterruptedException {
		ZContext context = new ZContext();

		ZMQ.Socket inSocket = context.createSocket(SocketType.PULL);
		inSocket.bind("inproc://test.in");
		ZMQ.Socket outSocket = context.createSocket(SocketType.PUSH);
		outSocket.bind("inproc://test.out");

		Future<?> queueFuture =
				Executors.newSingleThreadExecutor()
						.submit(new ZMQQueue(context.getContext(), inSocket, outSocket));

		ZMQ.Socket pushSocket = context.createSocket(SocketType.PUSH);
		pushSocket.connect("inproc://test.in");

		ZMQ.Socket pullSocket = context.createSocket(SocketType.PULL);
		pullSocket.connect("inproc://test.out");

		Thread.sleep(1000);

		pushSocket.close();
		pullSocket.close();
		inSocket.close();
		outSocket.close();

		queueFuture.cancel(true);

		context.close();
	}
```
If I comment out the `queueFuture.cancel(true);`, test passes. Otherwise it is blocked.

Forgot to mention that my OS is Windows.

**Comment by artembilan** [comment]
Yeah... I see same dead lock problem on Linux, too...

**Comment by fredoboulo** [comment]
Hi, I'm not an active user of ZLoop, but Jeromq is not interruptible-friendly.
I would advise to add a command socket (usually a PAIR), to send a termination message to end the reactor (handler returning -1):

**Comment by artembilan** [comment]
> is not interruptible-friendly

Sounds scary, because many samples they demonstrate really based on thread interruption.
For example this one: http://zguide.zeromq.org/java:interrupt.

So, what I see in my app is a `java.nio.channels.ClosedByInterruptException` in the `Signaler.send()`. Therefore the `context` in main thread is blocked waiting for that signal.

Let me see what is that `control` in the proxy! If that will help to break the loop and let me to close sockets gracefully!

Thank you for your feedback!

**Comment by artembilan** [comment]
So, yes, the interruption is not the way to go.
Here is the working test:
```
@Test
	public void test() throws InterruptedException {
		ZContext context = new ZContext();

				Executors.newSingleThreadExecutor()
						.submit(() -> {
							ZMQ.Socket inSocket = context.createSocket(SocketType.PULL);
							inSocket.bind("inproc://test.in");
							ZMQ.Socket outSocket = context.createSocket(SocketType.PUSH);
							outSocket.bind("inproc://test.out");
							ZMQ.Socket controlSocket = context.createSocket(SocketType.PAIR);
							controlSocket.bind("inproc://test.control");
							try {
								zmq.ZMQ.proxy(inSocket.base(), outSocket.base(), null, controlSocket.base());
							}
							finally {
								inSocket.close();
								outSocket.close();
								controlSocket.close();
							}
						});

		ZMQ.Socket pushSocket = context.createSocket(SocketType.PUSH);
		pushSocket.connect("inproc://test.in");

		ZMQ.Socket pullSocket = context.createSocket(SocketType.PULL);
		pullSocket.connect("inproc://test.out");

		Thread.sleep(1000);

		pushSocket.close();
		pullSocket.close();

		ZMQ.Socket command = context.createSocket(SocketType.PAIR);
		command.connect("inproc://test.control");
		command.send(zmq.ZMQ.PROXY_TERMINATE);
		command.close();

		Thread.sleep(1000);

		context.close();
	}
```
and what is interesting my main code works well, too.
More typing though because we can't just call `cancel(true)` 😄 

But yeah, I'll try to promote the feature in my project and will see what community thinks about ZeroMQ.

Closing with the fact that fix is to not use thread interruption for JeroMQ components.
