### ISSUE TITLE
jeromq for fault-tolerant systems

### ISSUE THREAD

**Issue by ayedo** [zeromq/jeromq#873]
Hello,

first of all, I would like to thank the maintainers of the project for writing such a nice ZeroMQ Java integration library.

We are evaluating jeromq for usage in a medical device, and I would like to get input from the community on that.

Would you consider this library production ready to the extend it you would personally use it in a fault-tolerant system?
 
Anybody here in the community knows of large industry players using jeromq in production?

I know this is a lot to ask for, and we are thankful for any insight or input that you have no matter how small.

**Comment by fbacchella** [comment]
I'm using it in a high-throughput environment, reaching a maximum traffic of  27 000 ev/s (https://github.com/fbacchella/LogHub). But it's for logs, so I can afford to loose a few events and don't put strict measurement of that.

**Comment by ayedo** [comment]
Thanks for your reply. What do you mean with "losing a few events"? Does JeroMq drop messages?

**Comment by fbacchella** [comment]
It means that I don't know, because that's not a critical point for me. Performance is much more important for me.
But some socket type will loose event: PUB/SUB is made to do that rather than block.

**Comment by fredoboulo** [comment]
Hi @ayedo, please have a look at the [summary of the sockets](https://github.com/zeromq/jeromq/blob/master/src/main/java/org/zeromq/SocketType.java) to find out which types are dropping messages and which ones are not.

The [Guide](https://zguide.zeromq.org/) or [this site](https://zeromq.org/socket-api/#high-water-mark) could be useful as well.

**Comment by ayedo** [comment]
Hi @fredoboulo, thanks for you reply, and the clarification.
