### ISSUE TITLE
Build with ant fails

### ISSUE THREAD

**Issue by jplee-metaframe** [zeromq/jeromq#875]
[junit] Testcase: initializationError took 0.002 sec
    [junit]     Caused an ERROR
    [junit] Invalid test class 'org.zeromq.auth.TestUtils':
    [junit]   1. Test class should have exactly one public constructor
    [junit]   2. No runnable methods
    [junit] org.junit.runners.model.InvalidTestClassError: Invalid test class 'org.zeromq.auth.TestUtils':
    [junit]   1. Test class should have exactly one public constructor
    [junit]   2. No runnable methods
    [junit]     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    [junit]     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
    [junit]     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    [junit]     at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
    [junit]     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
    [junit]

BUILD FAILED

**Comment by fredoboulo** [comment]
Hi, I never got that one, I assume it could only be a matter of renaming the class by removing the "Test" thingy.

Please feel free to submit a PR.

**Comment by jplee-metaframe** [comment]
How do you usually build the jar?  I did just did `mvn ant:ant; ant`.

**Comment by trevorbernard** [comment]
Ant isn't a supported way to build jeromq. Issue `mvn package`
