### ISSUE TITLE
Possible Bug with IPC socket type

### ISSUE THREAD

**Issue by zooptwopointone** [zeromq/jeromq#877]
I ran into a problem with using IPC socket type when upgrading from 0.3.6 -> 0.5.2
Before my system worked perfectly.  After changing the system eventually runes out of "TCP" sockets.  As IPC seems to on this deployment just use a TCP port.   (12496)    Some basic info.  This is Running with OpenJDK 11 inside of a Alpine linux Docker image.   I am really just submitting this bug report for your information. I just gave up and changed it to use a TCP socket via localhost.  as I can make sure it disconnects properly etc.  FYI I was doing a Destroy on the IPC with the Context.

tcp        0      0 10.0.31.113:51984       10.0.31.113:12496       ESTABLISHED 
tcp        0      0 10.0.31.113:12496       10.0.31.113:53222       ESTABLISHED 
tcp        0      0 10.0.31.113:12496       10.0.31.113:52592       ESTABLISHED 
tcp        0      0 10.0.31.113:12496       10.0.31.113:53456       ESTABLISHED 
tcp        0      0 10.0.31.113:12496       10.0.31.113:54928       ESTABLISHED 
tcp        0      0 10.0.31.113:12496       10.0.31.113:59962       ESTABLISHED 
tcp        0      0 10.0.31.113:12496       10.0.31.113:52162       ESTABLISHED 
tcp        0      0 10.0.31.113:12496       10.0.31.113:55514       ESTABLISHED 
tcp        0      0 10.0.31.113:55768       10.0.31.113:12496       ESTABLISHED 

Let me know if you would like any more information.  Otherwise feel free to Just close this.

Thank you.

**Comment by fredoboulo** [comment]
Hi, do you have an example of code that demonstrates the problem?

**Comment by zooptwopointone** [comment]
Sorry I don't really have something that is easy to provide.  
Basics of what I have done is built a broker which has a listening IPC port on a REQ/REP socket type.  then the broker code itself creates clients for HELLO type purposes to connect and send messages through the system.  But what I found is that it was using TCP to do this vs anything else.  While there might be bugs in my code to make this not respond etc.  the issues I see is that it is using TCP vs using a UNIX socket or something else.  Details is this was Running in GKE under an Apline linux container.  

Sorry I am going to be unable to provide more information than this.

**Comment by trevorbernard** [comment]
IPC isn't actually supported yet. A design decision was made to translate it to a TCP socket. You're observations are correct.
