### ISSUE TITLE
ZContext.destroy() hanging indefinitely if connection failed

### ISSUE THREAD

**Issue by jowilkes** [zeromq/jeromq#878]
I've read through all the documentation and earlier issues, but couldn't find the solution to this.
Note this is not about threading, context sharing, or such.
Library: org.zeromq:jeromq:0.5.2

Consider this code:
```
public class TestMinimalZMQClientGettingStuck
{
    private static final int DEFAULT_CLIENT_RECEIVE_TIMEOUT_MS = 1000;
    public static final String DEFAULT_URL = "tcp://localhost:9999"; // we *do not* have a service running here.
    private ZContext zmqContext;
    private org.zeromq.ZMQ.Socket clientSocket;

    @Test  
    public void jeroMQgettingStuck() throws Exception
    {
    zmqContext = new ZContext(1);
    clientSocket = zmqContext.createSocket(SocketType.REQ);
    clientSocket.setReceiveTimeOut(DEFAULT_CLIENT_RECEIVE_TIMEOUT_MS);
    if (clientSocket.connect(DEFAULT_URL) == false) // there's nothing at that URL to connect to, though.
        throw new Exception("client failed to connect()"); // doesn't happen.

    // we're trying to send something there
    clientSocket.send("test");
    // and trying to receive, but will time out.
    final String response = clientSocket.recvStr();
    System.out.println("response = " + response); // will be null, because there is no-one there.

    clientSocket.disconnect(DEFAULT_URL);
    zmqContext.destroySocket(clientSocket);
    System.out.println("context destroy:");
    zmqContext.destroy(); // this is where it hangs.
    System.out.println("finally.");
    }
}
```

If we omit the send/recv part, things work fine, including shutdown.

But if we run it as above, without a counterpart, to connect to, this client times out as expected.
That's OK.
But the zmqContext.destroy() then hangs indefinitely.

Looks like a bug to me; but is it?

**Comment by fredoboulo** [comment]
Hi, it sure looks like a bug.

0.5.2 seems to suffer from it, while HEAD works well. 
After a bisect, I found out that [this commit](https://github.com/zeromq/jeromq/commit/bf8fb0bcc9c29bc440e0c7bf1c1ca1c1c780ae48) seems to have fixed the situation. 

To fix the bug using 0.5.2, you can set the linger to a small value between the creation of the socket and before the call to disconnect.
```
    clientSocket = zmqContext.createSocket(SocketType.REQ);
...
    clientSocket.setLinger(100);
...
    clientSocket.disconnect(DEFAULT_URL);
```

Setting the linger AFTER the disconnect makes the code hang on 0.5.2. At least that's the repeatable result on my machine.

Hope that helps

**Comment by fredoboulo** [comment]
I can confirm the disconnect is the cause of your symptoms with 0.5.2.
ZContext normally takes care of closing its sockets, passing a 0 linger (meaning the socket will not wait until all messages are queued to be sent). In 0.5.2 and in your example, this 0 linger is passed in the destroySocket method. Before that, sockets have a -1 linger (infinite wait until all messages are queued), and this is the value that is passed in your disconnect operation.

You can consider several options:
- use the latest Jeromq
- set a positive linger BEFORE the disconnect
- remove the disconnect call
I might have missed some, but these are the obvious ones.

**Comment by jowilkes** [comment]
In using your options, I tried to be forward-compatible to next release 0.5.3, while making it work with current 0.5.2 (not snapshot).
So, I
1. set a positive linger before the disconnect,
2. then perform the disconnect, 
3. replaced the subsequent `zmqContext.destroySocket(clientSocket)` by a `clientSocket.close()`, which, to my understanding and from the examples, should match the style intended for the future.

I hope I'm correct in my understanding re: destroySocket/close.
It works with 0.5.2 now. Thank you for your help!

**Comment by fredoboulo** [comment]
🎉 

Can the issue be considered to be closed then?

**Comment by jowilkes** [comment]
Yes. Thank you!
