### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by trevorbernard** [zeromq/jeromq#881]
Hi,

I'm been the Java steward for ZeroMQ since about 2012. I no longer have the time nor desire to give to this project anymore.  It's been a wonderful ride and I've worked with many amazing people. I will create one more stable release then hand off the reigns to the other ZeroMQ maintainers. 

Best of luck,
Trev

**Comment by jimrthy** [comment]
Thank you for all your hard work and contributions over the years.

**Comment by rca0007** [comment]
Thanks Trevor for all your work. Will ZeroMQ support this product and what is the expected lifetime?

**Comment by BillBarnhill** [comment]
Thank you Trevor for your many contributions and hard work.

**Comment by alopukhov** [comment]
It looks like there will be release 0.5.3 according to #920 and recent activity.
@trevorbernard could you please describe current project status?

**Comment by trevorbernard** [comment]
Working with @somdoron to show him the release process so the responsibly can be taken from my hands. The ultimate goal is to completely automate the process and have a new trusted set of signing keys.
