### ISSUE TITLE
How to get ZMsg as byte array?

### ISSUE THREAD

**Issue by ottmar-zittlau** [zeromq/jeromq#888]
Dear all,

I'm trying to receive messages using the PUB-SUB-pattern.
My first attempt was to use ZMQ.socket.recv() - which gave me the data as byte array.
Then I realized that the messages seem to arrive in multiple parts. Therefore, I started to use
ZMsg.recvMsg(socket) which seems to do the right thing (there are two frames to each message).

Now my question is, how can I convert a ZMsg to a byte array? Do I need to loop through the frames and 
combine them manually? I don't necessarily need the byte array - I just want to remove the topic prefix
and convert to data to a protobuf afterwards - so a simpler solution would be welcome, of course.

Thanks in advance
oz

**Comment by trevorbernard** [comment]
The underlying data structure is a `ArrayDeque`. You can call `poll()` on the `ZMsg` and you'll get a `ZFrame` which you can call `getData()` on
