### ISSUE TITLE
Q: release of new '0.5.3' tag to Maven Central

### ISSUE THREAD

**Issue by RalphSteinhagen** [zeromq/jeromq#890]
There are many changes and useful improvements that have been pushed to the main branch since the last '0.5.2' release. 

Would it be conceivable to push them also, for example, as '0.5.3' to Maven Central?

Many thanks in advance! And keep up the good work! :+1:

**Comment by ThomasCraigNelson** [comment]
We also would very much like this.

**Comment by trevorbernard** [comment]
We need to update the changelog then we'll issue a new release. This issue tracks the work. #923
