### ISSUE TITLE
why not supported ZMQ_TCP_KEEPALIVE_CNT, ZMQ_TCP_KEEPALIVE_IDLE ZMQ_TCP_KEEPALIVE_INTVL

### ISSUE THREAD

**Issue by tengpeter** [zeromq/jeromq#907]
If I want to support these features,Is that ok!

![微信截图_20211231112008](https://user-images.githubusercontent.com/26103906/147801287-3cf2aeaf-c2b9-492c-9003-5090609e9568.png)

**Comment by fbacchella** [comment]
That's not possible with the current version of Jeromq. This library aims to support Android API level 19, that is quit old. The next version will.

**Comment by trevorbernard** [comment]
Resolved in https://github.com/zeromq/jeromq/pull/931
