### ISSUE TITLE
Thread Pinning of IO threads in zeromq

### ISSUE THREAD

**Issue by rajputChaturya** [zeromq/jeromq#910]
Can we pin IO threads to dedicated cpu's, I am currently using pub-sub pattern for fanning out a stream to 25 subscribers. Though the results are fair, but I want to optimize further by pinning the IO threads to dedicated cpus. can we achieve this ?

**Comment by fbacchella** [comment]
Do you think that a ThreadFactory could do the job ? It could generate a thread with a custom run method that pin the thread and then run super.run() ?

**Comment by fbacchella** [comment]
Implemented in #942
