### ISSUE TITLE
ZError Error number description

### ISSUE THREAD

**Issue by jason199101** [zeromq/jeromq#917]
Currently I'm learning this jeromq lib. for error handling we found that we can identify different exception by zmq_errorno.
However, I didn't find any cleared description for different error number in this class ZError.class. is there any documentation descriptions for different zmq error numbers?

**Comment by trevorbernard** [comment]
http://api.zeromq.org/3-2:zmq-errno
http://api.zeromq.org/3-2:zmq-strerror
