### ISSUE TITLE
Will there be another release?

### ISSUE THREAD

**Issue by divadpoc** [zeromq/jeromq#922]
Hi, 
will there be another release? 
I see 0.5.3-SNAPSHOT is currently under development, but there hasn't been any release yet.

Thanks and regards

**Comment by somdoron** [comment]
@trevorbernard if you update me on how to release a version I can try and do that going forward.

**Comment by trevorbernard** [comment]
@somdoron I sent you a DM on my slack

**Comment by trevorbernard** [comment]
This will be addressed in #923
