### ISSUE TITLE
socket.CLIENT does not seem to do anything in java8

### ISSUE THREAD

**Issue by AnthonyJClink** [zeromq/jeromq#926]
The following code seems to connect and send data however even without a running SERVER does not work.
This seems to only apply to java 8.

`		ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

		LossMessage lossMessage = buildLossMessage(); 
		lossMessage.writeTo(outputStream);
		
		try (ZContext context = new ZContext()) {
			// Socket to talk to clients
			ZMQ.Socket socket = context.createSocket(SocketType.CLIENT);
			if(socket.connect("tcp://127.0.0.1:" + String.valueOf(5555))) {
				if(socket.send(outputStream.toByteArray(), 0)) {
					System.out.println("sent message to " + socket.getLastEndpoint());
				}else {
					System.out.println("Could not send");
				}
			}else {
				System.out.println("could not connect");
			}
		}`

**Comment by trevorbernard** [comment]
A problem with the above code is that the result of send doesn't mean you've successfully sent the message, rather that it has been enqueued internally. So in essence send is async.

As for the CLIENT/SERVER socket types, you can read the [RFC](https://rfc.zeromq.org/spec/41/) for the semantics.

**Comment by AnthonyJClink** [comment]
adding a thread.sleep after the send method seemed to have addressed my problem. I was closing the context before it was flushed
