### ISSUE TITLE
issue with kvmsg get/set operation

### ISSUE THREAD

**Issue by ThomasCraigNelson** [zeromq/jeromq#940]
Note the following test
   @Test
   public void showKmsgIssueTest()
   {
       kvmsg msg = new kvmsg(0);
       msg.setKey("mykey");
       kvmsg clone = msg.dup();
       clone.setKey(clone.getKey() + "theirkey");
       // This should pass but does not in 0.5.3:
       assert(clone.getKey().equals("mykeytheirkey"));
   }
However with the following change in kvmsg it passes:
    //  Set message getKey as provided
    public void setKey(String key)
    {
        byte[] msg = new byte[key.length()];
        System.arraycopy(key.getBytes(ZMQ.CHARSET), 0, msg, 0, key.length());
        frame[FRAME_KEY] = msg;
        present[FRAME_KEY] = true;
        this.key = null;// THIS LINE FIXES the test.  Used in later getKey optimization....
    }

**Comment by trevorbernard** [comment]
Feel free to submit a PR fixing this issue

**Comment by trevorbernard** [comment]
Resolved
