### ISSUE TITLE
NPE after uplift jeromq from 0.5.2 to 0.5.3

### ISSUE THREAD

**Issue by todaviaCaliente** [zeromq/jeromq#943]
After changing jeromq version from 0.5.2 to 0.5.3 we observe NPE in Thread which monitors state of connection:

java.lang.NullPointerException: null
	at org.zeromq.ZMQ$Event.recv(ZMQ.java:4264) ~[jeromq-0.5.3.jar:?]
	at org.zeromq.ZMQ$Event.recv(ZMQ.java:4301) ~[jeromq-0.5.3.jar:?]

It looks like problem introduced in [this commit](https://github.com/zeromq/jeromq/commit/c0fbdbd64f4cae1050f63169ec6fbee540acbabf#diff-b59409e571d3af9103f4578cc5fc9457eabdc2fd7b9a0bfd4d2ec2822b57890d) where null-check was removed.

Javadoc for ZMQ.Event.recv(Socket, int) states:
@return the received event **or null if no message was received**.

**Comment by fbacchella** [comment]
It’s back in commit 9dbe4136e6f93286177269986ee4f1e31bfda834

**Comment by fbacchella** [comment]
O.5.4 has been released.
