### ISSUE TITLE
ipc

### ISSUE THREAD

**Issue by jinyuttt** [zeromq/jeromq#953]
Cppzmq, jerozmq cannot communicate using ipc

**Comment by trevorbernard** [comment]
This is a known issue. Under the covers in JeroMQ, IPC gets converted to TCP. This was a decision made way before Java supported UNIX Domain Sockets. This issue is being worked on.

**Comment by eelcocramer** [comment]
@trevorbernard great to hear this is being worked on. Any idea when this might become available? Is there help needed?

**Comment by fbacchella** [comment]
I started to play with a generic solution on this branch: https://github.com/fbacchella/jeromq/tree/networkprotocolserviceprovider.

But I am out of time to make any progress on it.
