### ISSUE TITLE
[Question] Message Persistence

### ISSUE THREAD

**Issue by pandaapo** [zeromq/jeromq#965]
Does JeroMQ support message persistence? If so, are there any relevant documentation or examples for me to learn about?

Thanks!

**Comment by fbacchella** [comment]
Did you read https://zguide.zeromq.org ?

**Comment by fbacchella** [comment]
That’s an accurate and definitive answer, even if you don’t like it.

**Comment by fbacchella** [comment]
Yes. That’s the spirit of ZMQ.

**Comment by trevorbernard** [comment]
jeromq's job is to send opaque bytes across some interface. It doesn't much care how you serialize or deserialize the bytes. It provides certain guarantees like: atomicity when sending or receiving multipart messages. You can achieve different workflows by applying patterns described in the zguide as @fbacchella mentioned.
