### ISSUE TITLE
SocketType

### ISSUE THREAD

**Issue by jinyuttt** [zeromq/jeromq#986]
Why cannot sockettype be used when creating a socket? Development tool not found

**Comment by fbacchella** [comment]
Please describe your problem with sample code.

**Comment by jinyuttt** [comment]
![屏幕截图 2024-05-01 221009](https://github.com/zeromq/jeromq/assets/13539621/b0fa9450-75e4-4a81-8330-457914874ef7)
![屏幕截图 2024-05-01 220941](https://github.com/zeromq/jeromq/assets/13539621/b3dcbd23-49ba-4fad-9034-44f13719e0b4)
![屏幕截图 2024-05-01 220811](https://github.com/zeromq/jeromq/assets/13539621/eb40d7d7-c2ad-4a16-a8d0-7d656e1153d7)
i can not find!
