### ISSUE TITLE
SocketType enum not present in 0.6.0

### ISSUE THREAD

**Issue by Ivan8or** [zeromq/jeromq#990]
follow up to this issue (which admittedly had next to no info) https://github.com/zeromq/jeromq/issues/986

in JMQ version 0.5.4, `import org.zeromq.SocketType;` resolves in intellij as expected, and I am able to run code like
```
public static void main(String[] args) {
        try (ZContext context = new ZContext()) {
            ZMQ.Socket socket = context.createSocket(SocketType.SUB);
            socket.connect("tcp://192.168.1.22:18082");
        }catch (Exception e) {
            e.printStackTrace();
        }
    }
```
with no issues.

Upon upgrading to JMQ version 0.6.0, `import org.zeromq.SocketType;` cannot be resolved by intellij / glows red.
However, the above code still runs as expected, despite SocketType not being recognized as an existing class.

I appreciate the JMQ group taking the time to look into and resolve issues like these, OSS is what make the world turn!

**Comment by fbacchella** [comment]
That’s a problem with Intellij, not with JeroMQ.

**Comment by FuadEfendi** [comment]
This is really annoying, it is NOT problem with IntelliJ. I recompiled and installed in local repo 0.7.0-SNAPSHOT and the issue does not happen.

Even assuming the issue with IntelliJ (and for sure it does have issues with Maven): it does not happen with properly compiled (using proven JDK and latest Maven) v.0.7.0-SNAPSHOT.

Something wrong this this SocketType.class (or artifact in general). Not compatible with IntelliJ "whatever", but can be compiled in terminal, no issues.

Which JDK did you use to install & release 0.6.0? Which Maven version? etc.

I had so much experience with IntelliJ Maven "cleanup" and "reimport" with so many projects, and I never experienced this kind...

Could you please release 0.7.0? Perhaps with higher bytecode compatibility? I cannot use my own custom "snapshot" in corporate environment. Thank you!

**Comment by FuadEfendi** [comment]
Ok, I upgraded corporate version of outdated "IntelliJ Ultimate" (fortunately it allows to install without admin); it works no... really annoying issue ;( 

Leaving mo post here, I am not alone ;)
