### ISSUE TITLE
Unix socket support?

### ISSUE THREAD

**Issue by marekkrk** [zeromq/jeromq#992]
Any chance of supporting Unix domain sockets? Java supports it with thirdparty libraries like junixsocket which PostgreSQL JDBC driver can use to connect to a DB server: https://jdbc.postgresql.org/documentation/use/

**Comment by fbacchella** [comment]
The work has been started https://github.com/fbacchella/jeromq/tree/ipc_unix_socket

**Comment by trevorbernard** [comment]
IPC is now supported using Java 16 and above in `master`. Support was added with this PR: https://github.com/zeromq/jeromq/pull/998

**Comment by maxandersen** [comment]
@trevorbernard  any plans for a release that includes this?

also, any docs on how to use/enable it as readme states it is not available...
