### ISSUE TITLE
Support: Updating from 5.2 to 5.3+ causes: Shadow contexts don't cast shadows

### ISSUE THREAD

**Issue by krukow** [zeromq/jeromq#994]
Hey, I have a non urgent support request. I've taken over maintaining a library which has historically used version 5.2 of 
zeromq/jeromq. Recently I tried to update and found that updating from 5.2 to 5.3+ causes an IllegalStateException "Shadow contexts don't cast shadows"

I believe I've traced it back to this PR: https://github.com/zeromq/jeromq/pull/829 which introduces that exception, but unfortunately I don't quite understand what that means. Are there any requirements from client code that need to be obeyed to avoid that exception?

Thanks

**Comment by trevorbernard** [comment]
Reading the PR, a shadow attempted the call shadow method. It only goes one level deep. Make sure when creating shadows it must come from the top level ZContext.

**Comment by krukow** [comment]
Thx - I did identify a place with nested calls and that fixed it. I appreciate the quick support
